### PR TITLE
#5849 Improve stack trace tests

### LINKED ISSUE #5849: ZIO 2.0: Create test suite for Cause.prettyPrint
A simple test suite can verify that useful traces are captured in multi-method scenarios.

An example:

```scala
object TraceExample extends ZIOAppDefault {
  def otherFailure =
    for {
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.fail("Uh oh!").ensuring(ZIO.dieMessage("other failure"))
    } yield ()

  def deepFailure =
    for {
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- ZIO.succeed(123)
      _ <- otherFailure
    } yield ()

  def run = deepFailure.catchAllCause(cause => Console.printLine(cause.prettyPrint))
}
```

We want to see the `run`, `otherFailure`(inside `deepFailure`), and `ZIO.fail` (inside `otherFailure`) in the stack trace, together with the finalizer failure (inside `ensuring`) as a `Suppressed` cause.

A few simple examples like this which test tracing and pretty printing together can constitute our test suite.

### PR DESCRIPTION
**Pull request by baldram**
Added:
- checks for Fiber ID,
- checks for existence of stack trace (also for each failure point if embedded)

Overall we have now the following cases. If we miss something, please do not hesitate to let me know.

```
+ StackTracesSpec
  + captureSimpleCause
    + captures a simple failure
  + captureMultiMethod
    + captures a deep embedded failure
    + captures a deep embedded failure without suppressing the underlying cause
    + captures the embedded failure
Ran 4 tests in 595 ms: 4 succeeded, 0 ignored, 0 failed
```

resolves #5849

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
@baldram Thanks for adding this! It looks like the test is brittle now and is failing on Scala 3. If we can fix that this will be good to go!

**Comment by baldram** [comment]
Yes, I fixed it, but couldn't run it from console locally (computer is overloaded). So I push a fix and we will see the pipeline.

**Comment by adamgfraser** [comment]
Sounds good!

**Comment by baldram** [comment]
@adamgfraser It's fixed successfully. 
Unfortunately pipeline failed. 
The 2.11 and some unrelated `ZStreamSpec`. 
Not sure this is a flaky test and retry would fix it. 

```
[info] - ZStreamSpec
[info]   - Combinators
[info]     - onExecutor
[info]       - shifts and does not shift back if there is no previous locked executor
[info]         `thread1` = Thread[ForkJoinPool-1-worker-1,5,main] did not satisfy equalTo(Thread[ForkJoinPool-1-worker-3,5,])
[info]         at /home/runner/work/zio/zio/streams-tests/shared/src/test/scala/zio/stream/ZStreamSpec.scala:1997
[info] 
[info] Done
[error] Failed tests:
[error] 	zio.stream.ZStreamSpec
[error] (streamsTestsJVM / Test / test) sbt.TestsFailedException: Tests unsuccessful
```

**Comment by adamgfraser** [comment]
@baldram Yes that is a flaky test.

**Pull request merged**
