### PR TITLE
Build ZIO Test for Scala Native

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
One flaky build that needs restarting, otherwise good :+1:

**Comment by sideeffffect** [comment]
@adamgfraser @mijicd could I humbly ask one of you guys to restart that one red build, please? :bow:

**Comment by mijicd** [comment]
@sideeffffect done :)

**Comment by adamgfraser** [comment]
@sideeffffect What was the failure you saw and had you merged upstream changes? Want to make sure we are more on top of flagging these build failures as they occur and addressing the underlying causes so we don't get back in the situation of having flakiness in the build.

**Comment by sideeffffect** [comment]
It was a timeout this time.
Don't worry, no logtrace is lost!
https://app.circleci.com/pipelines/github/zio/zio/9096/workflows/31bf0ebe-a9db-4cea-af57-11138190c6db/jobs/92716

Ha! I branched off of `Update izumi-reflect to 1.0.0-M8 (#4254)` `93527f2f`. I didn't have `harden TestClock (#4248)` `1774c8e3` :thinking: But shouldn't CircleCI test against the _PR merge_ branch anyway?

**Comment by adamgfraser** [comment]
@sideeffffect I'm pretty sure it doesn't do that.

**Comment by sideeffffect** [comment]
@adamgfraser :disappointed: you're right
It uses `refs/pull/4260/head`, but need it to use `refs/pull/4260/merge` :thinking:

**Review by adamgfraser — APPROVED** [review]

**Comment by sideeffffect** [comment]
this PR deserves the [`scala-native` badge](https://github.com/zio/zio/issues?q=label%3Ascala-native)
@adamgfraser :pray:

**Pull request merged**
