### PR TITLE
Remove redundant final modifier. For methods and vals.

### PR DESCRIPTION
**Pull request by saraiva132**
Continue work towards finishing #2509

### CODE REVIEW

**Comment by jdegoes** [comment]
I feel like we should document this in the contributor guide...

**Comment by regiskuckaertz** [comment]
Yes. Perhaps it deserves its own page? (just saw [this one](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines) 🤣 )

**Comment by saraiva132** [comment]
@jdegoes @regiskuckaertz I will document all of this. I have this in a sublime document with (I think I am up to 25 rules now). I can create an issue already today so you guys do not think I am forgetting! :DDD

**Comment by adamgfraser** [comment]
Great work!

**Pull request merged**
