### PR TITLE
Added ZSink.toQueue and ZSink.toQueueWithShutdown (#3735)

### LINKED ISSUE #3735: Add ZSink.toQueue
There is `ZStream#into` operator that allows for writing elements of a stream into a queue.
Would be better to have this functionality as a `ZSink` instead because sinks can be composed.

This sink could also take a boolean parameter like `shutdownWhenFinished` to decide if the queue should be terminated after the stream is done.

I also feel that it's possible to remove `Take` from the queue type w/o loss of functionality.

### PR DESCRIPTION
**Pull request by arnoldlacko**
Closes #3735

### CODE REVIEW

**Review by adamgfraser — APPROVED** [review]
Looks great!

**Comment by arnoldlacko** [comment]
Thank you @adamgfraser  🙂

**Review by adamgfraser — APPROVED** [review]

**Comment by iravid** [comment]
@adamgfraser @arnoldlacko Sorry to nitpick - I think this should be named `fromQueue`, as the queue is used to create a sink. `toQueue` would be used for converting an existing sink to a queue.

What do you think?

**Comment by adamgfraser** [comment]
@iravid Makes sense to me.

**Pull request merged**
