### PR TITLE
Update Copyright Notice

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by jdegoes** [comment]
@adamgfraser Only the latest date should be changed, not the earliest (e.g. `2017 - 2021` instead of `2020 - 2021`), because some lines of code created in 2017 survive and were still copyrighted in that year.

**Comment by adamgfraser** [comment]
@jdegoes Sorry I think I misunderstood your comment [here](https://github.com/zio/zio/pull/4538#issuecomment-756529275).

**Comment by adamgfraser** [comment]
@jdegoes Fixed now!

**Review by jdegoes — APPROVED** [review]
Thank you!

**Pull request merged**
