### PR TITLE
Fix `ZStream#zip`

### LINKED ISSUE #3513: ZStream#zip loses data
Testcase:
```
testM("zip"){
        val s1 = ZStream.fromChunk(Chunk[Int](1,2,3,4,5))
        val s2 = ZStream.fromChunks(Chunk[String]("a"), Chunk[String]("b"), Chunk[String]("c"))
        assertM(s1.zip(s2).runCollect)(equalTo(List((1, "a"), (2, "b"), (3, "c"))))
      }
```
>  List((1,a), (2,b)) did not satisfy equalTo(List((1,a), (2,b), (3,c)))

Implementation doesn't handle properly the case when 2 streams terminate at different moments.

### PR DESCRIPTION
**Pull request by simpadjo**
Closes #3513

A bit messy, improvements are welcome.
There is a chance that it will be deuglified it as a part of #3495 (In case I find out how to unify `ZStream#zip` and `Ztransducer#zip`)

### CODE REVIEW

**Comment by iravid** [comment]
Thanks @simpadjo. The code looks good overall. I don't have the cycles to do a deeper review here so happy to merge this as is and maybe follow up later if I have comments.

Can you fix the Dotty compilation?

**Comment by simpadjo** [comment]
@iravid thank you for the review. Fixed.
Btw, now JS tests run for 30+ minutes. Is it normal?

**Comment by iravid** [comment]
Yes, they've slowed down considerably. I'm not sure why that is but haven't had a chance to delve deeper aside from disabling some slow tests on Scala.js.

**Comment by iravid** [comment]
@simpadjo Thanks for fixing, great catch once again!

**Comment by adamgfraser** [comment]
I think the key driver is we are running the streams tests on Scala.js now. Previously all the stream tests were running only on the JVM. So we've significantly increased the workload (especially with streams using a lot of property based tests) on a platform that way always slower to begin with. We definitely need to do something about this. I think reducing the number of times property based tests are evaluated would be a good start and I can work on that.

**Comment by iravid** [comment]
Oh, that's right. I hadn't realized that. Good point about the number of iterations for the property checks!

**Pull request merged**
