### PR TITLE
ZIO 2.0: Delete Deprecated Operators

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@adamgfraser Can you disable MIMA on this branch?

**Comment by adamgfraser** [comment]
@jdegoes I disabled it in the branch protection rules but I think we need update the CI to not run it at all for PRs submitted against this branch or the failure will still be reported.

@mijicd or @softinio Would you be able to help with that?

**Comment by iravid** [comment]
A better approach would be to keep the branch protection rules enabled, but set `failOnProblem` to false in the call to `mimaSettings` in `build.sbt`.

**Comment by adamgfraser** [comment]
@iravid Good idea. I will make this change now.

**Pull request merged**
