### PR TITLE
Tidy the homepage sponsors section

### PR DESCRIPTION
**Pull request by wongelz**
Also fixed the discord logo; reword "Get Started" link.

tidy-homepage

### CODE REVIEW

**Comment by jdegoes** [comment]
@wongelz Thank you! 🙏 🙏 🙏

**Comment by ghostdogpr** [comment]
@wongelz Nice! I noticed you contributed to improve the website a few times. I was wondering if you could give me a hand to add a "Subscribe" button on the homepage to sign up for the newsletter. I have something that works but my CSS/JSX skills are subpar so it doesn't look so good.

**Comment by wongelz** [comment]
@ghostdogpr Sure, can you share what you have? I'll see what I can do.

**Comment by ghostdogpr** [comment]
@wongelz thanks! I'm sending this on discord if that's okay.

**Pull request merged**
