### PR TITLE
Remove specialized annotations

### LINKED ISSUE #1526: Remove specialization from Chunk in favor of distinct subtypes of Chunk.Arr
Today, `Chunk` is specialized on `A`. There are several reasons to reconsider this:
1. It is probably sufficient to specialize just the `Arr` constructor, as only arrays benefit from specialization. 
2. The future of specialization is unclear in Dotty. I only found this presentation from Dmitry Petrashko: https://d-d.me/talks/flatmap2016, but nothing concrete in the Dotty site. Maybe @smarter can shed some light on this?

### PR DESCRIPTION
**Pull request by regiskuckaertz**
@iravid is there anything else required for this to be done?

Closes #1526

### CODE REVIEW

**Comment by adamgfraser** [comment]
Nice! After this would be great to see what the other Dotty compatibility issues are, if any.

**Comment by regiskuckaertz** [comment]
Sadly, that doesn't look so good:
```scala
object ChunkBox {
  val array: Array[Int] = Array(1, 2, 3, 4)
  val chunk: Chunk[Int] = Chunk.fromArray(array)
  val arrayOut: Array[Int] = chunk.toArray
}
```
```java
public final class zio.ChunkBox {
  public static int[] arrayOut();
  public static zio.Chunk<java.lang.Object> chunk();
  public static int[] array();
}
```

**Comment by jdegoes** [comment]
@regiskuckaertz What is that boxing example from? Dotty?

**Comment by regiskuckaertz** [comment]
@jdegoes 2.12, actually after I learnt how to use javap 😅 

```
      27: astore_3
      28: aload_3
      29: invokeinterface #40,  1           // InterfaceMethod zio/Chunk.toArray:()Ljava/lang/Object;
      34: checkcast     #42                 // class "[I"
      37: astore        4
      39: new           #12                 // class scala/collection/mutable/ArrayOps$ofInt
      42: dup
      43: getstatic     #47                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      46: aload         4
      48: invokevirtual #51                 // Method scala/Predef$.intArrayOps:([I)[I
```

**Comment by iravid** [comment]
@regiskuckaertz rebase please :-)

**Comment by regiskuckaertz** [comment]
Done

**Pull request merged**
