### PR TITLE
fix: raceFirst and finalizers

### PR DESCRIPTION
**Pull request by regiskuckaertz**
/attempt #9203

### CODE REVIEW

**Comment by kyri-petrou** [comment]
@regiskuckaertz before I do a detailed review of the code, can we add the test in the linked issue to check whether this works?

One other thing, the linked issue specifies that the issue exists with `ZIO.raceAll`, but it's also present with `ZIO.race` / `ZIO.raceFirst`. e.g., this hangs when it should complete successfully:

```scala
import zio._
import zio.test.TestAspect.timeout
import zio.test._

import java.util.concurrent.atomic.AtomicBoolean

object ZIORaceFirstBug extends ZIOSpecDefault {
  override def spec: Spec[Any, Any] =
    suite("ZIO.raceFirst")(
      test("should always call finalizers") {
        for {
          isRunning <- ZIO.succeed(new AtomicBoolean(true))

          backgroundBlockingStuff = ZIO.attemptBlocking(while (isRunning.get()) {})

          acquire = backgroundBlockingStuff.fork
          release = ZIO.succeed(isRunning.set(false))

          eff = ZIO.acquireRelease(acquire)(_ => release)

          _ <- ZIO.scoped(eff.raceFirst(ZIO.never))
         // _ <- ZIO.scoped(eff.race(ZIO.never)) // This one also hangs

        } yield assertCompletes
      } @@ timeout(10.seconds)
    )
}
```

I'll update the ticket to include this test case

**Comment by regiskuckaertz** [comment]
@kyri-petrou The `race` method on the value is a completely different beast. I suppose such a low-level implementation was written for performance and replacing it with `ZIO.raceAll(self :: that :: Nil)` will not do it 😅 I can give it a try.

**Comment by kyri-petrou** [comment]
Hey @regiskuckaertz, #9353 fixed the issue using a more broad-spectrum approach that also fixed the issue with `race`.
Are you happy with closing this PR or are there any changes / improvements in it that you think we'd still benefit from?

**Comment by regiskuckaertz** [comment]
Nope happy to close this if the bug is fixed

**Pull request closed without merging**
