### PR TITLE
Add ZStream#unNone

### PR DESCRIPTION
**Pull request by asakaev**
Usually using this technique, you have to write boilerplate code.
Inspired by @mpilquist implementation.

### CODE REVIEW

**Comment by asakaev** [comment]
I don't get the purpose of using extension methods if we have access to sources. What is the reason?

There is only one method implemented as an extension. What makes it distinct from the others? Maybe it should be implemented as a method of a class?

**Comment by iravid** [comment]
Thanks @asakaev! Keeping the methods on the class as you've done is preferable (better discoverability). Let's move `unTake` in as well.

**Comment by vasilmkd** [comment]
Moving `unTake` works as well! Thanks.

**Comment by iravid** [comment]
Nice work @asakaev! Thanks for reviewing  @vasilmkd!

**Comment by vasilmkd** [comment]
@iravid my pleasure. I'm willing to donate review cycles, as you call them, generously for the duration of the hackathon.

**Pull request merged**
