### PR TITLE
Revert Diffing Functionality

### PR DESCRIPTION
**Pull request by adamgfraser**
Given the issues discussed in #3023 I think we should revert the diffing functionality for now. I don't think we want anything in our code base that is not our original work unless we explicitly decide that we want to use and credit the work of others. We didn't decide to do that here and I don't think we should do that here. We can still cleanly revert the diffing PR at this point. The functionality is nice but is definitely not mission critical. This will allow us to take the time to implement this feature the right way.

### CODE REVIEW

**Comment by olafurpg** [comment]
INAL but my understanding is that you also need a NOTICE for the code here https://github.com/zio/zio/blob/master/stacktracer/jvm/src/main/scala/zio/internal/stacktracer/impl/AkkaLineNumbers.scala

I struggle to understand the rationale for reverting here. It’s totally normal to copy/extend code from other projects. You’re already attributing the original source via comments. I don’t see how adding a NOTICE changes the “originality” of the work.

**Comment by adamgfraser** [comment]
@olafurpg Hi! Thanks for your amazing work on Metals! I use it every day. 😃

I don't think there is anything wrong with using code from other projects and I definitely don't think there is anything wrong with including a notice if you do. My issue here is that we opened an issue for an original implementation of this functionality, my understanding per discussion [here](https://github.com/zio/zio/issues/2784#issuecomment-584627350) was that this was an original implementation, and it was a mistake on my part to merge this when that was not the case.

We are ultimately going to use a version of existing diffing algorithm and would like to offer diffing functionality that will bear similarities to other libraries. But at least my perspective is that we want to do that ourselves and offer our own take on it versus reusing code from other libraries in this space.

I will take a look at the Akka line numbers issue. That was added before I was involved with the project but will make sure that is credited appropriately.

**Comment by neko-kai** [comment]
@adamgfraser @olafurpg 
The [Apache 2 licence](https://raw.githubusercontent.com/akka/akka/master/LICENSE) says you need to *preserve* the NOTICE file if one exists, in SOME form - including in source comments.

```
(d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.
```

There is no NOTICE file in Akka. There is NOTICE in munit, but it can also be a part of the comment, not a file.

**Comment by jdegoes** [comment]
@olafurpg Good to see you here! And thanks again (and yet again!) for your ongoing work on Metals—which I think nearly 95% of the ZIO team is using.

To everyone:

Code reuse is a normal and wonderful part of open source development, and providing attribution that goes above and beyond the call of duty is hugely important to me personally (see our detailed attributions on tests, the design of STM, and many other things in ZIO).

That said, I think reusing code from other projects should be _deliberate_ rather than _accidental_, and in this case, it feels like it's just something that happened in the ordinary course of development, rather than something that was discussed and planned for.

So rather than just charging forward with 1.0 so near by, it could make sense to back this out temporarily, until we figure out what the best approach is—continue as per the original specification with a novel implementation of some diffing algorithm, or deliberately reuse and attribute great code from another project like MUnit.

Thanks to everyone for their input on this issue and their work toward making better OSS software for developers worldwide!

**Pull request merged**
