### PR TITLE
Fix #5244: don't expand package definitions in the assertTrue macro for scala 3

### LINKED ISSUE #5244: assertTrue for scala 3 doesn't support package qualified identifiers
An assertion like 

```scala
assertTrue(zio.duration.Duration.fromNanos(1000) == zio.duration.Duration.Zero)
```

is translated into invalid code that looks basically like this:

```scala
zio.test.Arrow.succeed[zio](zio)
    .>>>[zio.duration](zio.test.Arrow.fromFunction[zio, zio.duration](((from: zio) => from.duration)))
    .>>>[zio.duration.package.type](zio.test.Arrow.fromFunction[zio.duration, zio.duration.package.type]((from: zio.duration) => from))
    .>>>[zio.duration.Duration.type](zio.test.Arrow.fromFunction[zio.duration.package.type, zio.duration.Duration.type]((from: zio.duration.package.type) => from.Duration))
    .>>>[java.time.Duration](zio.test.Arrow.fromFunction[zio.duration.Duration.type, java.time.Duration]((from: zio.duration.Duration.type) => from.fromNanos(1000L)))
    .>>>[scala.Boolean](zio.test.Assertions.equalTo[java.time.Duration](zio.duration.Duration.Zero)(zio.test.OptionalImplicit.none[zio.test.Diff[java.time.Duration]]))
```

the scalajs version fails to compile with
`java.lang.AssertionError: assertion failed: Cannot use package as value: Select(This(Ident(<root>)),zio)`

while the jvm version fails at runtime with
`java.lang.NoClassDefFoundError: zio`

the test that contains the assertion is currently green on the jvm because it is annotated with `@@ failing`.

I will try to make a PR for this.

### PR DESCRIPTION
**Pull request by roald-di**
This is my humble attempt at fixing #5244

### CODE REVIEW

**Comment by adamgfraser** [comment]
Copying @kitlangton.

**Comment by kitlangton** [comment]
Oh, amazing! Thanks @roald-di. I'll give this a spin this afternoon :)

**Review by kitlangton — APPROVED** [review]
This looks great! Thanks for tackling this :)
Also, I'll try to make passing non-`@failing` variants of each test, such that an unrelated failure such as this is not inappropriately squelched.

**Comment by kitlangton** [comment]
All good to merge @adamgfraser

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
