### PR TITLE
Add validation functions to ZPool

### PR DESCRIPTION
**Pull request by davidlar**
I would really need something like this to make the pool more usable.
In my case I use it as a database pool and I want to avoid getting broken connections from the pool and instead let the pool validate them before returning them to me.
I know I can build this stuff outside the pool but it was quite hard to get it right, especially the pre validate check.
It's much easier to handle this inside the pool.

Not sure about the interface (the way the validate functions are provided) and maybe we could skip the postValidate function.

What do you think?

### CODE REVIEW

**Comment by adamgfraser** [comment]
This is pushing significant complexity onto users who aren't interested in this functionality. At the very least we should make this a separate constructor.

But it feels like maybe this is not addressing the root problem. It seems like if you want to you should just be able to check the item you got and then invalidate it and get a new one. Why was this not working for you?

Want to get to the right interface for this data structure that is minimal but also powerful enough to do what we need.

**Comment by davidlar** [comment]
It is a separate constructor but maybe it should be renamed...

My simple first try to wrap pool.get: ```
def openValid(pool: UpdatedZPool[Throwable, A], retriesLeft: Int): RIO[Scope, A] = {
  val getValid =
    for {
      item <- pool.get
      valid <- preValidate(item)
      _ <- (pool.invalidate(item) *> ZIO.fail(new Exception("Invalid item"))).unless(valid)
    } yield item

  getValid.retryN(retriesLeft)
}```

Lets say we will get invalid items for a while, then the problem here is that the scope doesn't close for each retry and the pool will get exhausted. 
Because of that I thought that we must split acquire and release to be able to release on each retry.

My working solution was this:```
def openValid(pool: UpdatedZPool[Throwable, A], retriesLeft: Int): RIO[Scope, A] =
      ZIO.uninterruptibleMask { restore =>
        for {
          scope <- Scope.make
          acquire <- restore(scope.extend(pool.get)).exit
          release = scope.close(Exit.succeed(()))
          acquireValid <- acquire match {
            case Exit.Success(item) =>
              for {
                valid <- preValidate(item)
                acquired <-
                  if (valid) ZIO.acquireRelease(ZIO.succeed(item))(_ => release)
                  else
                    pool.invalidate(item) *> release *> {
                      if (retriesLeft == 0) ZIO.fail(new Exception(s"Could not get a valid connection for $database"))
                      else openValid(pool, retriesLeft - 1)
                    }
              } yield acquired
            case Exit.Failure(cause) => release *> ZIO.failCause(cause)
          }
        } yield acquireValid
      }```

but it feels a bit complex and I'm not sure about if uninterruptibleMask is needed or not...
Do you know a better way to do this?

**Comment by adamgfraser** [comment]
I think we need something like `ZIO#withEarlyRelease` so you could get the resource, determine if it is invalid, and if so just release it and get again.

**Comment by davidlar** [comment]
I will try it out as soon as it's merged!
Thank you Adam!

**Comment by davidlar** [comment]
Now with `ZIO#withEarlyRelease` I can do like this (as soon as https://github.com/zio/zio/pull/6844 is merged)!

```
def openValid(pool: UpdatedZPool[Throwable, A], retriesLeft: Int): RIO[Scope, A] = {
  val getValid: ZIO[Scope, Throwable, A] =
    for {
      releaseAndItem <- pool.get.withEarlyRelease
      (release, item) = releaseAndItem
      valid <- preValidate(item)
      _ <- (pool.invalidate(item) *> release *> ZIO.fail(new Exception("Invalid item"))).unless(valid)
    } yield item

  getValid.retryN(retriesLeft)
}
```

I will close this! Thank you!

**Pull request closed without merging**
