### PR TITLE
Implement ZStream#repeatWith

### PR DESCRIPTION
**Pull request by paulpdaniels**
Relates to #4886

### CODE REVIEW

**Review by iravid — DISMISSED** [review]
Yes! So much simpler than the previous version 💪

**Comment by iravid** [comment]
Just needs conflicts resolved and this is good to go.

**Comment by paulpdaniels** [comment]
Merge conflicts resolved

**Comment by iravid** [comment]
Sorry @paulpdaniels can you just run `set prepare` here so we can merge?

**Review by iravid — APPROVED** [review]

**Pull request merged**
