### PR TITLE
Add benchmark for race

### PR DESCRIPTION
**Pull request by Fristi**
Complementary benchmark for #3926

### CODE REVIEW

**Comment by jdegoes** [comment]
In order for this benchmark to be meaningful, it would need to perform racing repeatedly inside the same effect. Otherwise it would just measure unsafePerformSync overhead. In addition, ZIO race semantics are "first winner", not "first to finish", which means the other ones need modification to match ZIO semantics.

**Comment by adamgfraser** [comment]
I'm also not sure this is the underlying cause of the issue. It seems the problem in #3926 is a performance regression between the latest two ZIO release candidates. ZIO's race may or may not be faster than the race implementation in other effect systems but I think we would need to compare the performance of race between this version and the last version to get some indication of whether it could be the cause of the performance issue. Maybe the best next step here is a minimal reproducible example showing the performance degradation between the two versions. Then as we're experimenting with different changes we can evaluate whether they move the need on that.

**Comment by Fristi** [comment]
> In order for this benchmark to be meaningful, it would need to perform racing repeatedly inside the same effect. Otherwise it would just measure unsafePerformSync overhead. In addition, ZIO race semantics are "first winner", not "first to finish", which means the other ones need modification to match ZIO semantics.

Thanks for the feedback! Just reaching out to help :) I can try to have shot to implementing this benchmark correctly later this week, but if anyone else is up for to pin point the problem go ahead!

**Comment by Fristi** [comment]
I tested most RC versions with JMH with this test code to see any differences:
```
def zio(): Unit = {
    @tailrec
    def sumTo(t: Task[BigInt], n: Int): Task[BigInt] =
      if (n <= 1) t
      else sumTo(t.map(_ + n), n - 1)

    def racing =
      sumTo(IO.effectTotal(0), depth).disconnect raceEither sumTo(IO.effectTotal(0), depth).disconnect

    runtime.unsafeRun(racing.repeat(Schedule.recurs(1000)))
  }
```

As John mentioned, to make the test meaningful repeating the racing behavior should give a better idea of the performance of `raceEither`.

All versions performed equally except RC17 which had twice the performance (~ 80,000 ops/s versus ~ 35,000 ops/s)

Anyway I guess my assumption there is a performance issue with `raceEither` was wrong.

**Comment by jdegoes** [comment]
Will close for now although improvements to benchmarks are _always_ appreciated! 

Thanks @Fristi for your work on this!

**Pull request closed without merging**
