### PR TITLE
Port ZSink.last, ZSink.head

### PR DESCRIPTION
**Pull request by simpadjo**
@iravid ping

### CODE REVIEW

**Comment by simpadjo** [comment]
@iravid build succeeded (for some definition of success)

**Comment by iravid** [comment]
@simpadjo Could you move the tests back to `shared`?

**Comment by simpadjo** [comment]
> @simpadjo Could you move the tests back to `shared`?

In this case JS build hangs forever. Given that other tests for this branch are in JVM directory I decided that this is a known issue.

**Comment by simpadjo** [comment]
@iravid moved tests back to "shared" worked this time. Probably I was just not patient enough

**Pull request merged**
