### PR TITLE
Full path reporting for test traces

### PR DESCRIPTION
**Pull request by hmemcpy**
ZIO's `Trace` currently reports only the filename of the failing test (e.g. `MySpec.scala:34`), stripping the full path (for security reasons), and the filename itself is insufficient for assertions/tooling to be able to navigate to the exact location of the failure.

This PR restores the `SourceLocation` implicit which captures the full path of the executing test.

image

### CODE REVIEW

**Review by adamgfraser — DISMISSED** [review]
Good to go when CI is passing and conflicts are resolved!

**Review by adamgfraser — CHANGES_REQUESTED** [review]
Looks like just a Scala 3 issue to resolve!

**Comment by hmemcpy** [comment]
Of course there is 😅

**Review by adamgfraser — APPROVED** [review]

**Comment by hmemcpy** [comment]
Fixed.
Methods in ZIO that require `Trace` will keep both the `trace` and the `sourceLocation` implicits, otherwise just the new SourceLocation will be used for test-specific methods.

**Review by adamgfraser — APPROVED** [review]

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
