### PR TITLE
Rename TestUtils.scala.scala to TestUtils.scala

### PR DESCRIPTION
**Pull request by ioleo**
Fixed filename typo and moved to `zio/test`.

### CODE REVIEW

**Comment by adamgfraser** [comment]
Good catch. While you're at it, would you mind moving the fill from the `test/mock` folder to the `test` folder?

**Comment by ioleo** [comment]
@adamgfraser done, ready for review

**Comment by adamgfraser** [comment]
@ioleo Thanks! Looks good to me!

**Comment by ghostdogpr** [comment]
Thanks for the fix!

**Pull request merged**
