### PR TITLE
Buffer signal bug

### PR DESCRIPTION
**Pull request by vasilmkd**

### CODE REVIEW

**Comment by vasilmkd** [comment]
I have managed to isolate this to the code in the test case, where a success (3) follows a failure (2). If the stream short circuits after the first failure, the code runs successfully. So this might be an issue with `flatMap`? @iravid

**Comment by vasilmkd** [comment]
Here's the output: in this case, the code stops at `p <- Promise.make[Nothing, Unit]`. Again I stress this, this _always_ happens when we have a stream with a success following a failure pull.

```
going
pulled: Fail(Traced(Fail(Ouch),ZTrace(Id(1579597725724,167),List(SourceLocation(ZStream.scala,zio.stream.ZStream$Structure$Concat,process,2735), Sour
ceLocation(ZIO.scala,zio.ZIO,flatten,515), SourceLocation(StreamEffect.scala,zio.stream.StreamEffect$$anonfun$$lessinit$greater$1,apply,29), SourceLo
cation(ZIO.scala,zio.ZIO,flatten,515), SourceLocation(Ref.scala,zio.Ref$,get$extension,41), SourceLocation(ZStream.scala,zio.stream.ZStream$Structure
$Concat,process,2732), SourceLocation(Ref.scala,zio.Ref$,get$extension,41), SourceLocation(ZStream.scala,zio.stream.ZStream,bufferSignal,801), Source
Location(ZStream.scala,zio.stream.ZStream,bufferSignal,801), SourceLocation(ZManaged.scala,zio.ZManaged,fork,428), SourceLocation(FiberContext.scala,
zio.internal.FiberContext$InterruptExit$,apply,157), SourceLocation(FiberContext.scala,zio.internal.FiberContext$InterruptExit$,apply,150), SourceLoc
ation(ZIO.scala,zio.ZIO$TapFn,apply,3220), SourceLocation(Ref.scala,zio.Ref$,set$extension,104), SourceLocation(ZManaged.scala,zio.ZManaged,fork,428)
),List(SourceLocation(Take.scala,zio.stream.Take$,fromPull,66), SourceLocation(ZStream.scala,zio.stream.ZStream,bufferSignal,802), SourceLocation(ZSt
ream.scala,zio.stream.ZStream,bufferSignal,808)),Some(ZTrace(Id(1579597725461,15),List(SourceLocation(ZManaged.scala,zio.ZManaged,fork,423), SourceLo
cation(Ref.scala,zio.Ref$,make,169), SourceLocation(ZManaged.scala,zio.ZManaged,flatMap,310), SourceLocation(FiberContext.scala,zio.internal.FiberCon
text$InterruptExit$,apply,150), SourceLocation(ZStream.scala,zio.stream.ZStream,bufferSignal,763), SourceLocation(Ref.scala,zio.Ref$,make,169), SourceLocation(ZManaged.scala,zio.ZManaged,flatMap,309), SourceLocation(Ref.scala,zio.Ref$,update$extension,123), SourceLocation(ZManaged.scala,zio.ZManaged,flatMap,309), SourceLocation(ZManaged.scala,zio.ZManaged,map,454)),List(SourceLocation(ZManaged.scala,zio.ZManaged,fork,430), SourceLocation(ZManaged.scala,zio.ZManaged,map,454), SourceLocation(ZManaged.scala,zio.ZManaged,map,454), SourceLocation(ZManaged.scala,zio.ZManaged,flatMap,311), SourceLocation(ZStream.scala,zio.stream.ZStream$,managed,3267), SourceLocation(ZStream.scala,zio.stream.ZStream$,managed,3267), SourceLocation(ZStream.scala,zio.stream.ZStream,flatMap,1300), SourceLocation(ZStream.scala,zio.stream.ZStream,flatMap,1317), SourceLocation(ZStream.scala,zio.stream.ZStream,flatMap,1308), SourceLocation(ZIO.scala,zio.ZIO$,zio$ZIO$$_succeedRight,3204)),Some(ZTrace(Id(1579597725441,3),List(SourceLocation(ZIO.scala,zio.ZIO,zipWith,1638), SourceLocation(ZIO.scala,zio.ZIO,zipWith,1638), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2339), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2338), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2242)),List(SourceLocation(ZIO.scala,zio.ZIO,zipWith,1638), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2342), SourceLocation(ZIO.scala,zio.ZIO,run,1299), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2335), SourceLocation(ZIO.scala,zio.ZIO,refailWithTrace,1156), SourceLocation(Spec.scala,zio.test.Spec,foldM,153), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2340), SourceLocation(ZIO.scala,zio.ZIO,forever,572)),Some(ZTrace(Id(1579597725059,0),List(SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2339), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2338), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2243), SourceLocation(ZIO.scala,zio.ZIO$,foreach,2242), SourceLocation(ZIO.scala,zio.ZIO,zipWith,1638), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2337), SourceLocation(Promise.scala,zio.Promise$,makeAs,243), SourceLocation(Promise.scala,zio.Promise$,make,236), SourceLocation(ZIO.scala,zio.ZIO$,fiberId,2194)),List(SourceLocation(ZIO.scala,zio.ZIO,zipWith,1638), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2342), SourceLocation(ZIO.scala,zio.ZIO,run,1299), SourceLocation(ZIO.scala,zio.ZIO$,foreachParN,2335), SourceLocation(ZIO.scala,zio.ZIO,refailWithTrace,1156), SourceLocation(Spec.scala,zio.test.Spec,foldM,153), SourceLocation(ZIO.scala,zio.ZIO,summarized,1390), SourceLocation(TestRunner.scala,zio.test.TestRunner,run,45), SourceLocation(BaseTestTask.scala,zio.test.sbt.BaseTestTask,run,39), SourceLocation(ZIO.scala,zio.ZIO,run,1299)),None)))))))))
before latch
after latch
queue shutdown: false
waiting for zio.Promise@706fa499
status of latch done: true
done waiting
offer done
unblocked zio.Promise@181349bc
going
pulled: Value(1)
in offer value
is this line printed?
```

**Comment by vasilmkd** [comment]
Adding another message, for example: `_     <- UIO.effectTotal(println(s"offered new latch $p"))` now stops executing on the line `_ <- UIO.effectTotal(println("is this line printed?"))`. How can this be happening, I'm so confused.

**Comment by jdegoes** [comment]
I suggest trying to minimize and doing a fiber dump! 

I can try to take a look at this but it's not gonna be till after 1.0...

**Comment by vasilmkd** [comment]
@jdegoes Sorry for the question, how can I do a fiber dump inside sbt?

**Comment by adamgfraser** [comment]
@vasilmkd Add a call to Fiber.dump to your code.

**Comment by vasilmkd** [comment]
I did, nothing happens, it blocks on the line. Something is seriously wrong here.

**Comment by adamgfraser** [comment]
I can try to take a look later today.

**Comment by adamgfraser** [comment]
Can we close this?

**Comment by vasilmkd** [comment]
Can it stay open for a while longer? I'm working on it still. Thanks. I haven't completely solved it yet.

**Comment by adamgfraser** [comment]
Sure, sorry, I thought that you had resolved it with your other PR. Do you need anything on this or just you working through it yourself right now?

**Comment by vasilmkd** [comment]
I might actually need help from you later. I encountered a suite that when executed with testOnly works properly but when executed with other suites hangs. But I will need to take another look. I'm not near a computer at the moment.

**Comment by vasilmkd** [comment]
@adamgfraser As I said.
Running `streamsTestsJVM/testOnly zio.stream.StreamBufferSpec` works fine and all the tests pass.
Running `streamsTestsJVM/test` hangs on the same suite. What gives.

**Comment by adamgfraser** [comment]
@vasilmkd Will take a look.

**Comment by adamgfraser** [comment]
@vasilmkd I tried running this locally and the test appears to be flaky when run with `testOnly`. Sometimes it passes and sometimes it hangs. So my hypothesis would be that there is a concurrency bug in either your implementation or your test. That exists regardless of how the test is run, but it may be that running the entire test suite creates higher concurrency conditions (because other suites are being run at the same time) that potentially make the bug more likely to occur.

**Comment by vasilmkd** [comment]
Resolved by #2704 and #2752.

**Pull request closed without merging**
