### PR TITLE
ZStream#toInputStream laziness

### PR DESCRIPTION
**Pull request by simpadjo**

### CODE REVIEW

**Comment by iravid** [comment]
So I think this means we can revert the previous change to `toInputStream`?

**Comment by simpadjo** [comment]
No, that one is still needed. This one just suspends the first chunk, the previous one catches errors

**Comment by iravid** [comment]
If I'm not mistaken, the change there only catches errors thrown by pulling the first chunk, no?

**Comment by simpadjo** [comment]
No, it catches all errors (turns them into `E` instead of dying). `"Preserves errors in the middle"` testcase verifies this.

**Comment by iravid** [comment]
@simpadjo Your tests are passing even when that change is reverted. The reason is that the `Task` is done running by the time you're inside `use`, so it does not affect the actual runtime of the InputStream.

**Comment by simpadjo** [comment]
:thinking: not sure I totally get it so far. Do you mean that coverage is weak (and it's still possible to `die`)  or that the first patch is indeed redundant?

**Comment by iravid** [comment]
No, the coverage is fine. It's just that now that `ZInputStream` is constructed lazily (due to the `Iterator.empty ++` tweak), `ZInputStream.fromPull` will not throw when given a failed stream.

I can expand more later if needed.

**Comment by simpadjo** [comment]
No worries, just revert the redundant commit.

**Comment by simpadjo** [comment]
@iravid reverted the previous fix as you suggested

**Pull request merged**
