### PR TITLE
Scalafmt 3.6.0

### PR DESCRIPTION
**Pull request by sideeffffect**
Please merge as _Merge_ merge (not as Squash merge).

### CODE REVIEW

**Comment by adamgfraser** [comment]
Why does this need to be a merge commit and why do we need this at all? Seems like a lot of unnecessary changes, especially for a branch that we are not actively developing against at this point.

**Comment by sideeffffect** [comment]
> Why does this need to be a merge commit

because of the `.git-blame-ignore-revs` trick

> why do we need this at all

I would like to make a few changes to the build configuration (for Scala Native) in series/1.x. This will make it easier to merge the series/1.x (along with those changes) up to the series/2.x branch. Having both branches on the same scalafmt prevents potentially different formatting and we certainly want series/2.x to be on up-to-date Scalafmt.

**Comment by adamgfraser** [comment]
If we're going to update the version we should update the settings so that it does not cause significant formatting changes. Don't think there is any particular urgency around updating this. Also would encourage you to do new development targeting Scala Native on the `series/2.x` branch.

**Comment by sideeffffect** [comment]
You're right, probably not worth the hassle... at least at this point.

**Pull request closed without merging**
