### PR TITLE
Release zio for scala 2.13

### LINKED ISSUE #1007: Build for 2.13.0
Scala 2.13.0 was [released](https://github.com/scala/scala/releases/tag/v2.13.0), so it would be great to have ZIO build for it.

### PR DESCRIPTION
**Pull request by mijicd**
Closes #1007.

### CODE REVIEW

**Comment by kaishh** [comment]
YES

**Comment by henricook** [comment]
Pleeeeeeeeeeeeeease

**Comment by jdegoes** [comment]
There's a few 2.13 failures, around collections in STM, looks like. Super excited to get this through though, let me know if I can help!

**Comment by mijicd** [comment]
Yeah, conversions and Queue's API incompatibilty are kinda painful. I
wanted to try one more thing, but I will reach out to you ASAP to push it
through.

**Comment by kaishh** [comment]
@mijicd 
Do you have the cycles currently to finalize the PR? I've checked how much is left and it seems with a few fixes it's ready to ship.
I've opened a PR to your fork: https://github.com/mijicd/zio/pull/1 (I've decided to `@silence` collection-related warnings instead of using scala-collection-compat, since deprecated methods won't be removed during the 2.13 cycle anyway.)

**Comment by mijicd** [comment]
@kaishh I've planned to wrap it up today, as I've finally found some spare time. Thanks for helping, merged your PR. Regarding `scala-collection-compat`, it would collide with no dependency policy, and it doesn't really solve all the issues, so this might be an acceptable approach.

**Comment by mijicd** [comment]
This one's ready to be reviewed. After a discussion with @kaishh, we agreed to move out the custom Queue implementation and tackle it separately.

**Comment by jdegoes** [comment]
@kaishh Great idea!

@mijicd Thanks for your work on this!

giphy

**Pull request merged**
