### PR TITLE
fix: ZIO Config Guide Invalid link 

### LINKED ISSUE #8926: ZIO Config Guide Invalid link
[ZIO -Config guide]( https://zio.dev/zio-config/) points incorrectly to itself instead of Dive into [Dive into ZIO config](https://zio.dev/zio-config/dive-into-zio-config) . 

i tried editing the page but link points to a not found

### PR DESCRIPTION
**Pull request by varshith257**
Closes #8926 

Changes:

Existing:
```
href="/zio-config/"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Getting Started</div></a></nav></div></div><div
```

Updated:
```
href="/zio-config/dive-into-zio-config"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Dive Into ZIO Config</div></a>
```

### CODE REVIEW

**Comment by jdegoes** [comment]
It is not correct to update generated HTML. What must be updated is the content, from which the HTML is generated.

**Comment by varshith257** [comment]
@jdegoes  Docusaurus automatically generates previous (pagination_prev) and next (pagination_next) navigation buttons at the bottom of each documentation page based on the sidebar configuration. In ZIo-Config the sidebar.js configuration is almost correct except the misplaced index. md. It will be automatically  reference it and reference to next o following one

Reference zio-json sidebar.js configuration:

image

**Comment by varshith257** [comment]
@jdegoes Related PR in Zio-Config, PTAL:
https://github.com/zio/zio-config/pull/1434

I can't claim the bounty linking /claim. I think we need to close this so that algora link claim there

**Comment by varshith257** [comment]
@jdegoes PTAL of  https://github.com/zio/zio-config/pull/1434 of the same PR work

**Comment by varshith257** [comment]
@jdegoes Can you have a look at it here? The PR got merged in ZIO-Config but I am unable to claim it due to the issue and claim is here in ZIO and work has been done in the ZIO-Config.

The workaround I am thinking of is to update this branch and get merge a empty PR which has claim here :)

**Comment by jdegoes** [comment]
@varshith257 It seems you were able to claim the bounty, right?

**Comment by varshith257** [comment]
@jdegoes Yes. I have raised a query to algora and it has been solved :)

**Pull request closed without merging**
