### PR TITLE
add NonEmptyChunk.fold

### PR DESCRIPTION
**Pull request by simpadjo**
and minor improvements in type signatures

### CODE REVIEW

**Comment by iravid** [comment]
@adamgfraser can you chime in on the name?

**Comment by adamgfraser** [comment]
It seems strange. Normally `fold` would be a method on a data type and here it is not a method on a data type but the data type we are "folding" is `Chunk` instead of `NonEmptyChunk` and we are folding over the hypothetical empty and nonempty cases instead of the elements as we normally would for a collection.

Maybe make it a method on `Chunk` and call it `nonEmptyOrElse`?

**Comment by simpadjo** [comment]
Agree!

**Comment by simpadjo** [comment]
@adamgfraser @iravid done

**Pull request merged**
