### PR TITLE
Add test for mapZIOPar and mapZIOParUnordered for parallelism respected

### LINKED ISSUE #8753: mapZIOParUnordered does not respect parallelism
I am surprised of what this program using `mapZIOParUnordered` outputs

```scala
  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = for {
    _ <- ZIO.debug("start")
    _ <- ZStream
      .iterate[Int](0)(n => n +1)
      .mapZIOParUnordered(2){ _ =>
        ZIO.debug("tick").delay(1.second)
      }.runDrain.zipParLeft(ZIO.debug("----").delay(2.seconds).forever)

  } yield ()
```

the number of ticks printed between the ----- is: 2, 7, 11, 15, 19, 23 ....
while if instead of mapZIOParUnordered(2) i use mapZioPar(2) ticks printed is: 2, 6, 6, 6, 6. Here i would expect it to be 4, 4, 4, 4 but at least it does not keep increasing

### PR DESCRIPTION
**Pull request by narma**
Closes #8753
That test shows that parallelism respected in mapZIOPar and mapZIOParUnordered combinators

Also closes #8933

### CODE REVIEW

**Review by jdegoes — DISMISSED** [review]

**Comment by kyri-petrou** [comment]
@narma can you also have the tests execute with a number higher than the buffer size (16)? Perhaps with 32?

**Comment by narma** [comment]
@kyri-petrou done! Also have tested with `@@ nonFlaky` on (JS, JVM, Native) platforms, works well.

**Review by kyri-petrou — DISMISSED** [review]
@narma thanks for that. My big apologies, I got confused with a different issue that's why I asked to test for parallelism above the buffer size.

I've approved this PR, but if it's not too much to ask, would you be able to also test whether parallelism can _exceed_ the buffer size (in a separate PR). I think the reason https://github.com/zio/zio/issues/8753 doesn't happen anymore is because a recent PR changed that logic, but I'm worried it introduced the opposite regression (parallelism not being respected by not exceeding the buffer size, see my comment here https://github.com/zio/zio/issues/8935#issuecomment-2164227518).

**Comment by narma** [comment]
@kyri-petrou Sure! Just added test, Can you confirm that I've got your right?

**Comment by kyri-petrou** [comment]
@narma thanks! It seems there isn't a regression there afterall 😮‍💨

Do you mind if I push a commit to your PR with a small rewrite of the tests to use latches instead?

**Comment by kyri-petrou** [comment]
In case you want to do it yourself, this is what I had in mind (which is a more accurate / strict). You'll also need to add the `concurrent` module as a dependency to the `streamTests` module in `build.sbt`:

```scala
          test("parallelism is not exceeded") {
            val iterations = 1000
            checkAll(Gen.fromIterable(Chunk(4, 16, 32, 64))) { parallelism =>
              for {
                latch <- CountdownLatch.make(parallelism + 1)
                f <- ZStream
                       .range(0, iterations)
                       .mapZIOParUnordered(parallelism)(_ => latch.countDown *> latch.await)
                       .runDrain
                       .fork
                _     <- Live.live(latch.count.delay(100.micros)).repeatUntil(_ == 1)
                _     <- latch.countDown
                count <- latch.count
                _     <- f.join
              } yield assertTrue(count == 0)
            }
          } @@ TestAspect.jvmOnly @@ nonFlaky(20) @@ TestAspect.timeout(10.seconds),
          test("parallelism must be reached irrespective of buffer size") {
            val iterations = 1000
            checkAll(Gen.fromIterable(Chunk(4, 16, 32, 64))) { parallelism =>
              for {
                latch <- CountdownLatch.make(parallelism)
                _ <- ZStream
                       .range(0, iterations)
                       .mapZIOParUnordered(parallelism, bufferSize = 2)(_ => latch.countDown *> latch.await)
                       .runDrain
              } yield assertCompletes
            }
          } @@ TestAspect.jvmOnly @@ nonFlaky(20) @@ TestAspect.timeout(10.seconds)
        ),
```

**Comment by kyri-petrou** [comment]
@narma I spoke too soon. I just realised you're only testing `mapZIOParUnordered`. If you change the 2nd test I wrote there to use `mapZIOPar`, then it fails 😢

**Comment by narma** [comment]
@kyri-petrou Thanks for suggestions! I've decided to mark ignore test for mapZIOPar to address resolveing this issue in another PR, that seems right to you?

**Comment by narma** [comment]
@kyri-petrou Feel free to add commits here

**Comment by kyri-petrou** [comment]
@narma this is perfect, thank you very much!

**Review by kyri-petrou — APPROVED** [review]

**Pull request merged**
