### PR TITLE
How to configure a hot-reloading dev server

### PR DESCRIPTION
**Pull request by DaniRey**
Added a documentation on how to configure sbt-revolver, which adds file-watching and hot-reloading capabilities
Added the getting-started documentation to the howtos, as it is otherwise missed by the impatient (skipping the start page)

### CODE REVIEW

**Comment by adamgfraser** [comment]
Can we either build this out into a more general page about how to build web servers with ZIO or move move it to the community resources section?

Just hot reloading seems a little specific to be one of the how too and it is not directly related to ZIO though clearly this can be a helpful tool if you are developing a web application and you can develop web applications with ZIO.

**Comment by DaniRey** [comment]
We could totally do that, but which library should then be used?

While most common with web servers, I don't think it is limited to that use case, but applies to any kind of server/watchdog, i.e. messaging, file watching, monitoring.

**Comment by adamgfraser** [comment]
If you wanted to do a more general "how to build web servers with ZIO" I would probably use `zio-http`.

Not disagreeing at all about the value of the hot reloading functionality, it is just something that while definitely useful in some cases is not needed in many others and at least right now it is more about this library which is generally useful in some situations but doesn't tie it in to ZIO.

**Comment by DaniRey** [comment]
Makes sense.
Let's close this PR then. I'll try to write a "How to build web servers with ZIO".

What do you think about adding the "getting started" to the how-tos in the sidebar?

**Comment by adamgfraser** [comment]
Might make sense as a blog post that we could link to or a contribution to `zio-http`. I know they are doing a ton of stuff and could use more help adding stuff like this.

**Comment by DaniRey** [comment]
Now we are circling back to why I did this PR in the first place.

(Context: John once said, that the Scala ecosystem is lacking something like Spring and I agree. I believe he also said that ZIO should be become Scala's Spring. I believe ZIO is on a good track to become exactly this. A one stop shop, where you get all the tools needed to write any kind of business application in Scala.)

My perception is, that ZIO is on a good level with the quality and performance, but is lacking in documentation and ease of use. I feel part of the problem is, that a lot of information is only available in blog posts or talks. Both do not age well, because they are not maintained (version numbers are outdated, usage patterns changed, libraries were replaced...)

I feel ZIO needs to do the following to become better documented and easier to use:
1. Blog posts which are considered important for beginners should become maintained howtos
2. Documentation should focus more on "how people search information" and less on "how they would search it if they were already experts". In other words, more along the way other popular frameworks are structured and documented.
3. There should be a "How to build a business (web) application with ZIO". Which shows all the important concepts like: code structure, configuration, deployment, development setup
4. Ideally all documentation of the ZIO ecosystem will end-up in one shared home. Maybe this would slow down things too much at the moment, but at least all sub-projects should have their documentation structured and linked the same way.
5. There should be a shared BOM (bill of materials), which can be added to a project, having compatible versions of all involved ZIO projects. Basically a Springboot light.

I tried to make a first step towards 1, 2 and 3. 

Do you share some of these goals? Can we find a good way to do this? I'm currently trying out ZIO 2.0 with Scala 3, as it might become our future stack. I'm happy to write documentation while doing so.

**Comment by adamgfraser** [comment]
Yeah I think those are fantastic goals. I just think we need to have enough content to actually do that.

**Comment by adamgfraser** [comment]
Also that's why I think it could be useful to build out the documentation for `zio-http` first. That's the core library people are probably going to be using for this with various supporting libraries in the ZIO ecosystem so I think that is probably the first place people are going to be looking for information and also has a group of involved contributors who are focused on these issues. So could make sense to build out more content there first and then pull it into the ZIO homepage though also fine if you want to directly contribute here.

**Comment by DaniRey** [comment]
My goal would be to make a first time user successful. Therefore I would rather contribute to the ZIO homepage, as this is where they will start (not even knowing `zio-http` exists).

I will try to contribute in both places.

**Comment by adamgfraser** [comment]
Sounds great! Thanks again for working on this! ❤️

**Pull request closed without merging**
