### PR TITLE
Improved layout of sponsors footer

### LINKED ISSUE #1181: Poor layout of sponsors on zio.dev footer
Screen Shot 2019-07-14 at 9 45 22 AM

### PR DESCRIPTION
**Pull request by lwalejko**
Fixes #1181

### CODE REVIEW

**Comment by lwalejko** [comment]
image
@jdegoes is it better?

**Comment by jdegoes** [comment]
@lwalejko Would love to take a look! Can you include a screen shot?

**Comment by jdegoes** [comment]
Ah, I see it. 😄

**Comment by jdegoes** [comment]
@lwalejko Thanks for this contribution, and congratulations on your first ZIO pull request!

giphy

**Pull request merged**
