### PR TITLE
Added circleci step to compile dotty

### LINKED ISSUE #1048: Enable Circle CI Dotty compilation but not tests
Tests don't work for Dotty but we should still be compiling Dotty on every build.

/cc @NeQuissimus @softinio

### PR DESCRIPTION
**Pull request by softinio**
This resolves #1048

### CODE REVIEW

**Comment by softinio** [comment]
@NeQuissimus Linting definitely does a full compile right? 

Results: https://circleci.com/gh/zio/zio/2814

**Comment by jdegoes** [comment]
@softinio This doesn't _look_ like it's doing a full compile... it's just checking the source formatting of the files, isn't it?

**Comment by softinio** [comment]
@jdegoes Agreed thats what I thought but Tim hinted in issue that linting does hence asked him for clarification of what he meant. 

Just going to change it to an actual compile to be sure especially since we dont need to lint using dotty

**Comment by jdegoes** [comment]
@softinio Awesome (Tim may know more about this than me, I just looked at the log, and I know I've used `scalafmt` on non-compiling code before).

**Comment by NeQuissimus** [comment]
Oooohh, that's my bad. I was under the impression that our linting included scalafix! Scalafmt won't trigger a compile, you're right.

**Comment by softinio** [comment]
@jdegoes @NeQuissimus This is all ready for you gents to review .... a few notes:

- Did not include compiling of the interops for dotty in the build as they are imminently being removed from this repo
- some subprojects that have dotty versions of dependencies not available yet on maven we can't compile so have excluded from build but have opened an issue for it so we can handle when ever dotty versions of those depencies are available to us see https://github.com/zio/zio/issues/1077
- I did upgrade the version of dotty we are compiling against to `0.16.0-RC3`

Here is the result `success`:

https://circleci.com/gh/zio/zio/3202

Hope I didn't miss anything :-) 

Many thanks.

**Comment by jdegoes** [comment]
@softinio Awesome work. Thank you!

**Pull request merged**
