### PR TITLE
Change transducer encoding to force them to be infinite

### PR DESCRIPTION
**Pull request by iravid**

### CODE REVIEW

**Comment by mschuwalow** [comment]
Looks good!

Sadly I was out of the loop for a while. Is there anywhere where I can get up to speed on the current design direction of ZStream?

**Comment by iravid** [comment]
@mschuwalow Hey! I will do a summary soon of the current design. You can also look at the ZTransducer/ZSink classes; they have some notes on them. ZStream is mostly unchanged except it now operates on chunks by default.

**Comment by regiskuckaertz** [comment]
@mschuwalow Great to have you back! The tickets are also a great source of history: https://github.com/zio/zio/issues/2551, https://github.com/zio/zio/issues/2720, https://github.com/zio/zio/issues/2719

**Comment by mschuwalow** [comment]
Thanks, I'll take a look!

**Pull request merged**
