### PR TITLE
Include the JVM stack up to Runtime.unsafeRun* in the fiber trace

### PR DESCRIPTION
**Pull request by dkarlinsky**
Issue #5785

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
So I think we want to get this out of the runtime configuration.

If we implement:

```scala
object ZIO {
  /** Captures the current thread's stack trace as a `ZTrace`. */
  val stackTrace: UIO[ZTrace] =
    ???
}
```

Then we can add the stack trace to an existing `Cause` used `Cause.traced`. This will allow us to implement `unsafeRunWithStackTrace` as:

```scala
trait Runtime[+R] {
  def unsafeRunWithStackTrace[E, A](zio: => ZIO[R, E, A]): A =
    unsafeRun(ZIO.stackTrace.flatMap(trace => zio.mapErrorCause(_.traced(trace))))
}
```

**Comment by dkarlinsky** [comment]
@adamgfraser I think this is basically what @jdegoes [suggested](https://github.com/zio/zio/issues/5785#issuecomment-951435614) on the issue. 
I responded to his comment [here](https://github.com/zio/zio/issues/5785#issuecomment-951618071), but 
the main issue I see is that, if we want to log exceptions inside our effect (which in code I work on we do alot), the captured stacktrace won't be in the `Cause`.
This as opposed to passing the `ZTace` of the current stack to `new FiberContext` as the parent trace. 

I  could have  the separate `unsafeRun*WithStackTrace` methods capture the stack and propagate it to the private `unsafeRunWith` that creates the initial `FiberContext`. 
But I count seven public `unsafeRun*` methods. Do we want to add seven `*withStackTrace` variants?

**Comment by dkarlinsky** [comment]
I now see that `parentTrace` is gone from the `FiberContext` constructor...
Maybe we could add `runtimeStackTrace: Chunk[ZTraceElement]` parameter, which would be appended to the trace generated in `unsafeCaptureTrace`?

**Comment by jdegoes** [comment]
@dkarlinsky Can you open up a ticket where we can discuss how to do this in ZIO 2.0, in a way that doesn't degrade performance for those who aren't interested in the feature? Thank you!

**Comment by dkarlinsky** [comment]
@jdegoes we have https://github.com/zio/zio/issues/5785 
Or do you prefer a fresh issue, specific to ZIO 2.0?

**Pull request closed without merging**
