### PR TITLE
Remove Observer If Awaiting Fiber Is Interrupted

### LINKED ISSUE #7066: Promise + repeatZIOChunkOption memory leak
We were investigating the memory leak(https://github.com/zio/zio-kafka/issues/485) in `zio-kafka` after upgrade to ZIO 2.0 and apparently Fibers/Promises are causing OOM again(we had the similar issue about 2 years ago with ZIO 1.0, ref https://github.com/zio/zio/issues/4457)
Simplified example from `zio-kafka`:
```
  case class Record(x: Int)

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = {
    def stream(queue: Queue[Promise[Option[Throwable], Chunk[Record]]]) =
      {
        for {
          p <-  Promise.make[Throwable, Unit]
          s  = ZStream.repeatZIOChunkOption(for {
            request <- Promise.make[Option[Throwable], Chunk[Record]]
            _       <- queue.offer(request).unit
            result  <- request.await
          } yield result).interruptWhen(p)
        } yield  (p, s)
      }

    for {
      queue <- Queue.unbounded[Promise[Option[Throwable], Chunk[Record]]]
      // fulFill promise
      _ <- ZStream
        .fromQueue(queue)
        .mapZIO(_.succeed(Chunk.fromIterable(0.to(100).map(Record))))
        .runDrain
        .fork
      tup <- stream(queue)
      // dummy consumer
      _ <-
        tup._2.tap{ _ =>
          val (p, s) = tup //just for the debug purpose
          ZIO.unit
        }.runDrain
    } yield ()
  }
```
After couple seconds the number of observers will be up to 100k and continue to grow, not allowing gc to cleanup linked resources:
image

image

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #7066.

### CODE REVIEW

**Comment by narma** [comment]
Looks like we have another / one more place with leaking, just tested this fix with original repro given at https://github.com/zio/zio-kafka/issues/485 and with first repro at #7066 - still reproducible.

**Comment by adamgfraser** [comment]
@narma Try now.

**Comment by narma** [comment]
@adamgfraser works like a charm

**Comment by adamgfraser** [comment]
@narma Awesome!

**Comment by narma** [comment]
Thank you, Adam! Can't wait upcoming minor release :)

**Comment by adwells-ds** [comment]
Thanks for the fix, test cases have been running for couple hours and no leaks/issues so far 👍

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Woudl be great to figure out a way to add a test for this, if we can!

**Pull request merged**
