### PR TITLE
Update to Scala 3.0.0-M1

### PR DESCRIPTION
**Pull request by lvitaly**
Relates to #4397

### CODE REVIEW

**Comment by ghostdogpr** [comment]
I just merged https://github.com/zio/zio/pull/4425 which had the same thing except you also updated the sbt plugins. Can you rebase so that we merge that too?

**Comment by lvitaly** [comment]
@ghostdogpr Yep. I will do it soon. Sorry. I missed that PR.

**Comment by lvitaly** [comment]
@ghostdogpr Done. Checks passed.

**Comment by lvitaly** [comment]
@ghostdogpr basically, I don't see any valuable changes anymore, and I'm going to close this PR.

**Pull request closed without merging**
