### PR TITLE
[Do Not Merge] ZConduit

### PR DESCRIPTION
**Pull request by iravid**

### CODE REVIEW

**Comment by vasilmkd** [comment]
Do we need a `sealed` class hierarchy?

**Comment by iravid** [comment]
I don’t think it’s strictly necessary, no

**Comment by iravid** [comment]
@regiskuckaertz I added `Signal` and `SignalFunction` to this branch using your fold encoding. It's pretty nice!

**Comment by jdegoes** [comment]
@iravid Can you close and re-open as Draft pull request? Draft pull requests can't be merged until they're switched to ready.

**Comment by iravid** [comment]
Yes.

**Pull request closed without merging**
