### PR TITLE
Compile tests on Scala Native

### PR DESCRIPTION
**Pull request by sideeffffect**
blocked on
https://github.com/zio/zio/pull/6284
https://github.com/scala-native/scala-native/pull/2548

### CODE REVIEW

**Comment by sideeffffect** [comment]
@lolgab Any idea why it's complaining about
```
[error] missing symbols:
[error] * M19java.util.TimeZone$D10getDefaultL18java.util.TimeZoneEO
[error]   - from M17java.time.ZoneId$D13systemDefaultL16java.time.ZoneIdEO
[error]   - from M16java.time.Clock$D17systemDefaultZoneL15java.time.ClockEO
[error]   - from M24java.time.LocalDateTime$D3nowL23java.time.LocalDateTimeEO
[error]   - from M23java.time.LocalDateTimeD3nowL23java.time.LocalDateTimeEo
[error]   - from M39zio.clock.package$Clock$Service$$anon$1D24$anonfun$localDateTime$2L23java.time.LocalDateTimeEPT39zio.clock.package$Clock$Service$$anon$1
[error]   - from M49zio.clock.package$Clock$Service$$anon$1$$Lambda$5D5applyL16java.lang.ObjectEO
[error]   - from M39zio.clock.package$Clock$Service$$anon$1D13localDateTimeL7zio.ZIOEO
[error]   - from M32zio.clock.package$Clock$Service$RE
[error]   - from M24zio.clock.package$Clock$RE
[error]   - from M20zio.test.TestRunner$D15apply$default$4L10zio.ZLayerEO
[error]   - from M17zio.test.package$RE
[error]   - from M28zio.test.DefaultRunnableSpecD5suiteL16java.lang.StringL30scala.collection.immutable.SeqL13zio.test.SpecEO
[error]   - from M19zio.ImportlessSpec$RE
[error]   - from M47zio.ImportlessSpec$$SN$ReflectivelyInstantiate$D5applyL16java.lang.ObjectEO
[error]   - from M19zio.ImportlessSpec$IE
```
When I can see that it should be available: https://github.com/cquiroz/scala-java-time/blob/v2.4.0-M1/core/native/src/main/scala/java/util/TimeZone.scala#L16

**Comment by lolgab** [comment]
@sideeffffect The problem is that Scala Native has stubs for this class and it gets picked instead of the one coming from scala-java-time.
The solution is update Scala Native to remove all the classes that are now implemented by scala-java-time.

**Comment by lolgab** [comment]
@sideeffffect What do you think of first updating only Scala Native with Scala 3 support and enabling the tests in a separate PR after the problem with `TimeZone` is fixed upstream?

**Comment by sideeffffect** [comment]
@lolgab Good idea :+1: Btw for that we are blocked on https://github.com/scala-native/scala-native-loop/pull/39

**Comment by lolgab** [comment]
@sideeffffect scala-native-loop 0.2.1 was published for Scala 3

**Comment by sideeffffect** [comment]
We're getting many `Cannot block for result to be set in Scala Native` errors from `OneShot`. Any idea what to do about it @lolgab ?

**Comment by lolgab** [comment]
@sideeffffect What I do in scala-native-loop is to run the event-loop after each test. https://github.com/scala-native/scala-native-loop/blob/master/core/src/test/scala/scala/scalanative/loop/LoopTestSuite.scala#L7

**Comment by sideeffffect** [comment]
Any idea what could this mean @lolgab ?
```ini
[error] Found 1 missing definitions while linking
[error] Not found Top(scala.Nothing)
[error] 	at /home/runner/work/zio/zio/test-tests/shared/src/test/scala/zio/test/mock/PolyMockSpec.scala:15
```

**Comment by sideeffffect** [comment]
Please merge after build finishes green :pray: @adamgfraser @mijicd

**Comment by sideeffffect** [comment]
:tada:

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
