### PR TITLE
Add real-world BOM utf tests & add ZTransducer#utfDecode to smartly use BOM decoders

### PR DESCRIPTION
**Pull request by er1c**
Based upon https://github.com/zio/zio/pull/3981 - will rebase once it is merged.

- Add ZTransducer.utfDecode to auto-detect byte order marks
- Add ZTransducer.utf32Decode
- Add ZTransducer.utf32BEDecode
- Add ZTransducer.utf32LEDecode
- Add real-world BOM and utf tests for the ZTransducer UTF decoders

### CODE REVIEW

**Comment by er1c** [comment]
@mschuwalow mind taking a look at this?

**Comment by iravid** [comment]
Love the additional coverage and the `utfDecode` transducer. Can you rebase the branch?

**Comment by er1c** [comment]
@iravid already done :) waiting on CI

**Comment by er1c** [comment]
@iravid status is green.  I guess the biggest question here is the behavior for when the UTF_32 BOMs aren't supported by Charset

**Pull request merged**
