### PR TITLE
Added 'Promise' methods 'map', 'flatMap', 'zip', 'zipWith' (#4207))

### PR DESCRIPTION
**Pull request by arnoldlacko**
Based on the discussion in #4207 I've implemented a few combinators for `Promise` (`map`, `flatMap`, `zip`, `zipWith`).
A concern I have with this is that the type signatures are quite unconventional (due to the usage of `UIO`), which is why I'm wondering if renaming `map` and `flatMap` to something else might be a good idea. I'm thinking perhaps `flatMap` could be something like `andThen`, while for `map` I can't think of a good alternative. Let me know please about your thoughts, I'm happy to adjust (or remove if needed).
@iravid

### CODE REVIEW

**Comment by arnoldlacko** [comment]
Closing temporarily to do some further checks (I suspect using `ZIO.to` this way might not be correct here)

**Comment by arnoldlacko** [comment]
> Closing temporarily to do some further checks (I suspect using `ZIO.to` this way might not be correct here)

Resolved my concern, it seems fine. Reopening PR. :)

**Comment by jdegoes** [comment]
There are some drawbacks to these operations:

1. The `map` / `flatMap` / etc. methods have well-defined meanings and laws around them, which can't be satisfied by these (identically-named) operators.
2. Reasoning about these operators is somewhat difficult. For example, take `map`. Ordinarily, `map` will return a new value, in a way that is completely disconnected from the prior value. But in this case, `Promise#map` returns a new promise, but if someone completes the old promise, it will complete the new promise too (so there are 2 separate ways to complete the promise).

Do you have use cases we could look at, which could help us determine if these operators would be useful in a very broad context? If they are targeted toward niche use cases, it may be more useful to have them in a third-party library, rather than adding them to Promise directly.

**Comment by arnoldlacko** [comment]
@jdegoes thanks for the feedback. I don't actually have use cases where these operators would be strictly necessary. I've implemented them mostly as an exercise based on the discussion in #4207 and I was curious to see if it would be useful to have them added to `Promise`. I see your point about these operators having well defined meanings, which is why I was wondering if the proposed ones would make sense under different names (struggling to come up with appropriate ones though), but I am happy to close this PR in case it seems better not to have these on `Promise` at all.

**Comment by arnoldlacko** [comment]
Closing this one for now due to the concerns discussed above.

**Comment by arnoldlacko** [comment]
Thanks for the feedback @jdegoes . It was a nice exercise anyway, so no effort is wasted. :)

**Pull request closed without merging**
