### PR TITLE
Update to Scala 2.13.5 and 3.0.0-RC1

### PR DESCRIPTION
**Pull request by sideeffffect**
fixes https://github.com/zio/zio/issues/4732
/cc @adamgfraser @neko-kai

### CODE REVIEW

**Review by adamgfraser — DISMISSED** [review]

**Comment by neko-kai** [comment]
👍

**Review by neko-kai — DISMISSED** [review]

**Comment by sideeffffect** [comment]
```scala
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:61:63 
[error] 61 |        And(self.mock.compose ++ that.mock.compose)(xs1 ++ xs2).asInstanceOf[Expectation[R with R0]]
[error]    |                                                               ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:61
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:63:63 
[error] 63 |        And(self.mock.compose ++ that.mock.compose)(xs :+ that).asInstanceOf[Expectation[R with R0]]
[error]    |                                                               ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:63
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:65:63 
[error] 65 |        And(self.mock.compose ++ that.mock.compose)(self :: xs).asInstanceOf[Expectation[R with R0]]
[error]    |                                                               ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:65
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:66:80 
[error] 66 |      case _ => And(self.mock.compose ++ that.mock.compose)(self :: that :: Nil).asInstanceOf[Expectation[R with R0]]
[error]    |                                                                                ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:66
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:79:65 
[error] 79 |        Chain(self.mock.compose ++ that.mock.compose)(xs1 ++ xs2).asInstanceOf[Expectation[R with R0]]
[error]    |                                                                 ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:79
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:81:65 
[error] 81 |        Chain(self.mock.compose ++ that.mock.compose)(xs :+ that).asInstanceOf[Expectation[R with R0]]
[error]    |                                                                 ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:81
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:83:65 
[error] 83 |        Chain(self.mock.compose ++ that.mock.compose)(self :: xs).asInstanceOf[Expectation[R with R0]]
[error]    |                                                                 ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:83
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:84:82 
[error] 84 |      case _ => Chain(self.mock.compose ++ that.mock.compose)(self :: that :: Nil).asInstanceOf[Expectation[R with R0]]
[error]    |                                                                                  ^
[error]    |                     Exception occurred while executing macro expansion.
[error]    |                     java.lang.StackOverflowError
[error]    |
[error]    | This location contains code that was inlined from Expectation.scala:84
[error]    | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:117:62 
[error] 117 |        Or(self.mock.compose ++ that.mock.compose)(xs1 ++ xs2).asInstanceOf[Expectation[R with R0]]
[error]     |                                                              ^
[error]     |                   Exception occurred while executing macro expansion.
[error]     |                   java.lang.StackOverflowError
[error]     |
[error]     | This location contains code that was inlined from Expectation.scala:117
[error]     | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:119:62 
[error] 119 |        Or(self.mock.compose ++ that.mock.compose)(xs :+ that).asInstanceOf[Expectation[R with R0]]
[error]     |                                                              ^
[error]     |                   Exception occurred while executing macro expansion.
[error]     |                   java.lang.StackOverflowError
[error]     |
[error]     | This location contains code that was inlined from Expectation.scala:119
[error]     | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:121:62 
[error] 121 |        Or(self.mock.compose ++ that.mock.compose)(self :: xs).asInstanceOf[Expectation[R with R0]]
[error]     |                                                              ^
[error]     |                   Exception occurred while executing macro expansion.
[error]     |                   java.lang.StackOverflowError
[error]     |
[error]     | This location contains code that was inlined from Expectation.scala:121
[error]     | This location contains code that was inlined from Tags.scala:131
[error] -- Error: /home/circleci/project/test/shared/src/main/scala/zio/test/mock/Expectation.scala:122:79 
[error] 122 |      case _ => Or(self.mock.compose ++ that.mock.compose)(self :: that :: Nil).asInstanceOf[Expectation[R with R0]]
[error]     |                                                                               ^
[error]     |                   Exception occurred while executing macro expansion.
[error]     |                   java.lang.StackOverflowError
[error]     |
[error]     | This location contains code that was inlined from Expectation.scala:122
[error]     | This location contains code that was inlined from Tags.scala:131
```

**Comment by neko-kai** [comment]
@sideeffffect Argh, I fixed another instance of this error last time, but apparently not this one. on it rn

**Comment by neko-kai** [comment]
@sideeffffect Could you try with 1.0.0-M16?

**Comment by neko-kai** [comment]
Passed on 2nd try, but 1st failure doesn't seem related (ZStream test) 🎉

**Review by neko-kai — APPROVED** [review]

**Comment by sideeffffect** [comment]
@adamgfraser I think we can merge this now :tada:

**Pull request merged**
