### PR TITLE
Ensure green CI with re-actors/alls-green

### PR DESCRIPTION
**Pull request by sideeffffect**
Otherwise a failed step will still allow merging a PR.

### CODE REVIEW

**Comment by kyri-petrou** [comment]
I'm not sure we need this. The `ci` step won't be run when a job fails, and we have status checks in place to require it for merging (see screenshots).

I think the main thing is that admins can bypass the required status checks, but that would still be the case even with this change no?

image
image
image

**Comment by sideeffffect** [comment]
You'd think, but that's not how it works, sadly.

Example here https://github.com/zio/zio-prelude/pull/1353

**Comment by sideeffffect** [comment]
https://github.com/re-actors/alls-green

**Comment by kyri-petrou** [comment]
@sideeffffect Ahhh I see, in `zio-prelude` the `ci` job is not a required check in the repo's config. But I agree it's better for `ci` explicitly fail instead of being skipped in cases that another step failed

**Comment by kyri-petrou** [comment]
Having said that, I think the config in zio-prelude should be changed. Unfortunately I'm not an admin in that repo so I can't change it :(

**Comment by sideeffffect** [comment]
> in zio-prelude the ci job is not a required check

I see it as required:
image

**Comment by kyri-petrou** [comment]
@sideeffffect isn't this screenshot from zio? I meant `zio-prelude` (should probably have commented on that PR though 😓)

**Comment by kyri-petrou** [comment]
Nevermind me, I just checked there and it's also Required (coffee hasn't kicked in yet by the looks of it)

**Review by kyri-petrou — APPROVED** [review]

**Comment by sideeffffect** [comment]
@ghostdogpr :pray:

**Pull request merged**
