### PR TITLE
[WIP] Op logging via superpowers for supervisors

### PR DESCRIPTION
**Pull request by bertlebee**
Here's an attempt at fixing #7263 by adding support for supervisors to modify effects ala `drainQueueWhileRunning`

It's super unsafe but the possibilities with this power are pretty amazing (think a useful debugger...)

I think I also need to modify "OnFailure" and "OnSuccessAndFailure" - anything else?

@jdegoes probably one for you to look at if you have time since I'm messing with your baby here!

Downside to this approach is it's still not using the runtime flag for op logging (just op supervision). I don't think we can remove it without breaking bincompat.

### CODE REVIEW

**Review by adamgfraser — COMMENTED** [review]
I think the semantics of `OpLog`  are that we will actually log each operation to the current loggers using some format that we think is appropriate. This gives meaning to this `RuntimeFlag`.

This can be implemented independent of the changes to `Supervisor` by just checking the flag and if it is enabled logging the operation, though of course the `Supervisor` changes could be independently valuable.

**Review by adamgfraser — COMMENTED** [review]
Implementing operations logging in terms of a supervisor also assumes that all operations of the runtime are execution of effects, which is not necessarily true. Implementing operation logging independently would give us the maximum flexibility to evolve the way we log operations in the future.

**Comment by bertlebee** [comment]
> Implementing operations logging in terms of a supervisor also assumes that all operations of the runtime are execution of effects, which is not necessarily true. Implementing operation logging independently would give us the maximum flexibility to evolve the way we log operations in the future.

Any operations that are inserted by the runtime are inserted into the stack with an empty trace so we can tell them apart. These are actually really useful operations to be able to see - if I'm logging individual operations, it might be nice to see exactly when interruption/interuptability operations execute - that's actually why I moved the hook to after the call to runDrainWhileRunning

Using a supervisor like this allows for maximum flexibility IMO - I'm using Console.printLine as a starting point, but the intent would be to make it use logTrace instead so the output can be stored somewhere.

There is 0 performance overhead using this approach when it's turned off. There's a massive overhead when turned on but I think that's expected, and I'd anticipate if someone was using this, they might also be using the debugger that could also be developed based on this.

Further enhancements could include a similar approach to zio1.x to trace lambdas to see details from internal operations as well (this would be useful to find out if operations were modified by a supervisor as well!) Eventually this could be combined with a zio aware java debugger implementation which could step through code within a lambda for a given Fiber.

More immediately I think this could be wrapped up in an opLogged aspect to very easily get detailed info on targeted areas of the application when there's a bug.

**Comment by bertlebee** [comment]
> I think the semantics of `OpLog` are that we will actually log each operation to the current loggers using some format that we think is appropriate. This gives meaning to this `RuntimeFlag`.
> 
> This can be implemented independent of the changes to `Supervisor` by just checking the flag and if it is enabled logging the operation, though of course the `Supervisor` changes could be independently valuable.

I actually missed this comment before writing my response (yay for phones) - per above, the plan would be to use logTrace/existing loggers - I'm only using Console atm because I know it's printing - initially I was getting no output from my test so I just moved it to a regular program to get things working without worrying about the test supervisor etc.
Having another flag means another check - not a massive cost, but I think it's safe to say that if people are logging individual operations, they're not so worried about performance, so the overhead of turning on effect supervision for this feature is ok.
Having an extra check for event supervision is fine, but it will be an additional cost, and the way that we'd use existing loggers to logTrace would be by inserting effects into the stack... Which is exactly what this approach is doing.

**Comment by bertlebee** [comment]
(current output)

```[info] running (fork) zio.Test 
[info] zio.Test.effect(Test.scala:7)                     : zio.internal.DefaultExecutors$$anon$1@3f10e45a
[info] zio.Test.effect(Test.scala:7)                     : ()
[info] zio.Test.effect(Test.scala:7)                     : ()
[info] zio.Test.effect(Test.scala:7)                     : Interruptible(zio.Test.effect(Test.scala:7),Stateful(zio.Test.effect(Test.scala:7),zio.ZIOCompanionVersionSpecific$$Lambda$329/0x0000000800db7040@6eebf336))
[info] Please enter your name: 
[info] zio.Test.effect(Test.scala:7)                     : Success(())
[info] zio.Test.effect(Test.scala:7)                     : Stateful(zio.Test.effect(Test.scala:7),zio.FiberRef$unsafe$$anon$2$$Lambda$397/0x0000000800de05b0@30578dca)
[info] zio.Test.effect(Test.scala:7)                     : Success(())
[info] zio.Test.effect(Test.scala:7)                     : ()
[info] zio.Test.effect(Test.scala:8)                     : zio.internal.DefaultExecutors$$anon$1@3f10e45a
[info] zio.Test.effect(Test.scala:8)                     : ()
[info] zio.Test.effect(Test.scala:8)                     : ()
[info] zio.Test.effect(Test.scala:8)                     : Interruptible(zio.Test.effect(Test.scala:8),Stateful(zio.Test.effect(Test.scala:8),zio.ZIOCompanionVersionSpecific$$Lambda$329/0x0000000800db7040@352fda86))
[info] stupid forking error!
[info] zio.Test.effect(Test.scala:8)                     : Success(())
[info] zio.Test.effect(Test.scala:8)                     : Stateful(zio.Test.effect(Test.scala:8),zio.FiberRef$unsafe$$anon$2$$Lambda$397/0x0000000800de05b0@11a0ceef)
[info] zio.Test.effect(Test.scala:8)                     : Success(())
[info] zio.Test.effect(Test.scala:8)                     : ()
[info] zio.Test.effect(Test.scala:9)                     : zio.internal.DefaultExecutors$$anon$1@3f10e45a
[info] zio.Test.effect(Test.scala:9)                     : ()
[info] zio.Test.effect(Test.scala:9)                     : ()
[info] zio.Test.effect(Test.scala:9)                     : Interruptible(zio.Test.effect(Test.scala:9),Stateful(zio.Test.effect(Test.scala:9),zio.ZIOCompanionVersionSpecific$$Lambda$329/0x0000000800db7040@2063edae))
[info] Hello, ()!
[info] zio.Test.effect(Test.scala:9)                     : Success(())
[info] zio.Test.effect(Test.scala:9)                     : Stateful(zio.Test.effect(Test.scala:9),zio.FiberRef$unsafe$$anon$2$$Lambda$397/0x0000000800de05b0@2cd60db5)
[info] zio.Test.effect(Test.scala:9)                     : Success(())
[info] zio.Test.effect(Test.scala:9)                     : ()```

**Comment by adamgfraser** [comment]
It actually isn't true that any operations are performed as execution of effects. For example when a fiber processes an interrupt signal while suspended it sends interrupt messages to all its child fibers. Similarly when a fiber processes a stateful message while suspended it potentially makes arbitrary changes to fiber state.

Of course there is subjectivity in how we define what are "operations" of the runtime that we want to log but I could easily argue that these are operations we want to log or at least have the ability to log since they clearly have semantic effect.

Having a more powerful supervisor interface seems potentially useful but also distinct from logging the operations of the runtime.

**Comment by bertlebee** [comment]
@adamgfraser that's a good point about the interruption signals and yes I would like to be able to see those logged. It's not clear to me how we would log interruption when a fiber is asleep using the logging mechanism since the fiber needs to be executing to interpret the effects that log messages. I guess it would be possible to effectively wake the fiber to log/interrupt.

I think we need to have a discussion about what should be logged (or be able to be logged/how much configuration we need to support).

Happy to split supervisor changes if you prefer, but this is where I ended up after trying a couple of different approaches, which all pushed me back to inspecting/modifying operations

**Comment by adamgfraser** [comment]
@robmwalsh In `evaluateMessageWhileSuspended` we check whether `RuntimeFlag.OpLog` is enabled and if so call `log`. 😃

Agree we need to figure out what operations we want to log though I think the implementation should give us the flexibility to log or not log whatever we want. This is why I like just logging at appropriate places because we can always change that in the future if we want to.

**Pull request closed without merging**
