### PR TITLE
Use IntelliJ's default order for Organize Imports

### PR DESCRIPTION
**Pull request by sideeffffect**
Many of our contributors use IntelliJ and it's then causing friction, when they bum up against unhappy linter step in CI (even though they believe they've made everything orderly).

### CODE REVIEW

**Comment by sideeffffect** [comment]
@adamgfraser this is ready to be merged

**Comment by adamgfraser** [comment]
@sideeffffect Is there a risk that these non-sensical imports are going to be created again when contributors organize imports?

**Comment by sideeffffect** [comment]
@adamgfraser these non-sensical imports are very unlikely to happen, they occurred only when Scalafix was making changes to a huge number of files (like in this PR), they shouldn't happen to contributors making usual changes.
More at https://github.com/liancheng/scalafix-organize-imports/issues/137

**Comment by sideeffffect** [comment]
@adamgfraser just one spurious failure that needs restarting and then we're good to go :smiley:

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
