### PR TITLE
Feature/adding indexed seq benchmarks

### PR DESCRIPTION
**Pull request by Ethan-Edmond**
I added a benchmark for most of the IndexedSeq methods in a new file called ChunkIndexedSeqComparison.scala. Some of the benchmarks were already made, some only seemed to apply to partial functions. It took me an embarassingly long time to write this.

ref #3353

### CODE REVIEW

**Comment by adamgfraser** [comment]
@Ethan-Edmond Is there a reason you closed this? This seems like exactly the kind of benchmarks we want.

**Comment by Ethan-Edmond** [comment]
Sorry, I was trying to clean up the commit history and I kinda made a mess with git. Ill put it back up in a minute, I'm just going through the commands that the CI runs.

**Comment by Ethan-Edmond** [comment]
@adamgfraser Here's the new one. [https://github.com/zio/zio/pull/5971](https://github.com/zio/zio/pull/5971)

**Comment by adamgfraser** [comment]
@Ethan-Edmond Ah. You had me worried! 😅

**Pull request closed without merging**
