### PR TITLE
Fix memory leak in mapOutZIOPar

### PR DESCRIPTION
**Pull request by svroonland**
This fixes a memory leak in ZIO 2.0.4. I believe the double `forkScoped` is not composed correctly, leading to a leak. The fix is maybe not the best way to express this (feel free to change of course!), but its essence should be clear enough. 

Code to reproduce the leak:

```scala
import zio._
import zio.stream.ZStream
import zio.test._

object PromiseMemLeakSpec extends ZIOSpecDefault {
  case class LeakyObject(v: Chunk[String])

  override def spec = suite("Promise")(test("mem leak") {
    for {
      requestQueue <- Queue.bounded[Promise[Option[Throwable], LeakyObject]](1024)
      stream = ZStream.repeatZIO {
        for {
          request <- Promise.make[Option[Throwable], LeakyObject]
          _       <- requestQueue.offer(request).unit
          result  <- request.await
        } yield result
      }

      _ <- ZStream
        .fromQueue(requestQueue) // no change when adding maxChunkSize parameter
        .chunks
        // Changing to mapZIOParUnordered or mapZIO removes the OOM
        .mapZIOPar(1024)(chunk => chunk.mapZIO(promise => promise.succeed(LeakyObject(Chunk.fill(10000)("val1")))))
        .runDrain
        .forkScoped
//      _ <- stream.runDrain
      _ <- stream.zipWithIndex.tap { case (_, i) => ZIO.when(i % 10 == 0)(ZIO.logInfo(s"${i}")) }.runDrain
    } yield assertCompletes
  }) @@ TestAspect.withLiveClock

}
```

Run with eg `sbt -J-Xmx512M -J-Xms512M` and observe an OOM within a minute.

### CODE REVIEW

**Comment by svroonland** [comment]
Interestingly enough, as already discussed with Adam, the issue does not occur anymore when using the latest snapshot version of zio with the #7557 fix.

**Comment by jdegoes** [comment]
`forkScoped` creates a hard reference to the child fiber, meaning it won't be GC'd until the scope is closed.

**Comment by adamgfraser** [comment]
@jdegoes But the fiber should remove itself from the scope as soon as it completes execution.

@svroonland I tried your example and was not able to reproduce on `series/2.x`, even with the `Promise` optimization disabled. I think the issue may actually be that the root fibers were not being garbage collected which was resolved in #7553. Can you disable root fibers and see if that resolves your issue?

**Comment by adamgfraser** [comment]
@svroonland Going to close as I believe the issue has been addressed by other changes but please feel free to reach out if you are still having issues.

**Comment by svroonland** [comment]
Just for reference, this one is quite similar to https://github.com/zio/zio/issues/7066

**Pull request closed without merging**
