### PR TITLE
Handle more runtime failures

### PR DESCRIPTION
**Pull request by swoogles**
Wrote the reproducing tests first, and they blew up like this:
Screen Shot 2022-04-09 at 11 31 31 AM

With the same error message that @vigoo was getting.

After the changes, the failures are reported and we our assertions on their contents pass:
Screen Shot 2022-04-09 at 12 02 20 PM

### CODE REVIEW

**Comment by vigoo** [comment]
Are we going to see the exception's stack trace in real world use cases?

**Comment by adamgfraser** [comment]
Can you show what it looks like if there is a failure?

**Comment by swoogles** [comment]
> Are we going to see the exception's stack trace in real world use cases?

Yep, In these tests I'm doing assertions against the stacktrace results, but in the real world, we'll just be printing those out for the user.

**Comment by swoogles** [comment]
Closing this for now so I can continue iterating/pushing without hammering the the Actions

**Pull request closed without merging**
