### PR TITLE
[Docs] Add Scala 3 + Zio /w VS Code Github Template

### PR DESCRIPTION
**Pull request by electronjoe**
As a complete newcomer to Scala (and ZIO), I wanted to explore ZIO while
learning  on Scala 3.  Getting my environment set up for this was some
work, so I have put together a Github Template that, with VS Code's
Remote-Container extension - will automatically build the developer
environment with no dependencies other than Docker and VS Code.

Signed-off-by: Scott Moeller <electronjoe@gmail.com>

### CODE REVIEW

**Comment by electronjoe** [comment]
@khajavi Do you think that templates might belong closer to the `Learning` material? I anticipate most people will begin learning by spinning up an environment.

**Comment by khajavi** [comment]
A one-click ZIO development environment for new users coming from Java or other languages would be a great starting point.
Yes, I agree. It would be better to move templates into the learning section.

**Comment by adamgfraser** [comment]
We also have an existing Gitpod Docker file.

**Comment by electronjoe** [comment]
I'll go play with the Gitpod docker file @adamgfraser. Thanks for pointing that out!

**Pull request closed without merging**
