### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by DoNotWorr**
Release notes for SBT:
https://eed3si9n.com/sbt-1.8.0

### CODE REVIEW

**Comment by DoNotWorr** [comment]
As a sidenote, the zio project itself still adds the test framework manually too.

**Comment by DoNotWorr** [comment]
Fixed formatting mistake

**Review by adamgfraser — DISMISSED** [review]

**Comment by adamgfraser** [comment]
@DoNotWorr Can you fix the compilation error in the documentation?

**Comment by DoNotWorr** [comment]
Sorry for the delay, I realized it was easier to set up the project locally first than to wait for the CI workflow

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
