### PR TITLE
Scala 3.0.0

### PR DESCRIPTION
**Pull request by lemastero**
Scala 3.0.0 is out.
(Not sure if Scalasteward watch this.)

### CODE REVIEW

**Comment by lemastero** [comment]
Scala 3 release is in progress: https://github.com/lampepfl/dotty/issues/12441. That is why build failed.

**Comment by ivanopagano** [comment]
> Scala 3 release is in progress: [lampepfl/dotty#12441](https://github.com/lampepfl/dotty/issues/12441). That is why build failed.

The scala3 build failed again it seems?

**Comment by neko-kai** [comment]
@lemastero Would need to wait for scalatest and then izumi-reflect to publish first as well even after scala 3 hits maven.

**Comment by neko-kai** [comment]
@lemastero izumi-reflect 1.1.2 now available for 3.0.0 https://github.com/zio/izumi-reflect/releases/tag/v1.1.2

**Comment by adamgfraser** [comment]
@neko-kai Thank you! 🙏

**Comment by ghostdogpr** [comment]
I upgraded izumi, I believe this is good to go and zio could be released for Scala 3.

**Comment by ghostdogpr** [comment]
Subsumed by #5101 that brings Scala.js to Scala 3.

**Pull request closed without merging**
