### PR TITLE
Implement ZSink#managed

### PR DESCRIPTION
**Pull request by jupposessho**
Naive implementation which is failing on the "sad path", I need some hint here.

### CODE REVIEW

**Comment by adamgfraser** [comment]
@jupposessho What failure are you getting?

**Comment by jupposessho** [comment]
@adamgfraser I got 
```
`r` = Right(ok) did not satisfy equalTo(Left(fail))
```

**Comment by adamgfraser** [comment]
I think your implementation is correct but reflects a difference in the semantics between the semantics of the previous implementation and this one. In this implementation since the sink is just a channel, the upstream is only evaluated when the downstream issues a read instruction. In this case `ZSInk.succeed` immediately succeeds without issuing a read instruction so the upstream is never evaluated, hence returning `Right(ok)`.

**Comment by adamgfraser** [comment]
For example consider the following test:

```scala
testM("ZSink failure handling") {
  assertM(ZStream.fail("fail").run(ZSink.succeed("ok")))(
    equalTo("ok")
  )
}
```

With the new encoding this test will pass but with the old encoding it will fail.

So I think you just need to update the test and then this is good to go.

**Comment by jupposessho** [comment]
Thanks @adamgfraser for the explanation! Just fixed the test.

**Review by adamgfraser — APPROVED** [review]

**Comment by adamgfraser** [comment]
@iravid Is this test flaky? Doesn't seem related to this PR.

```
[info] - ZChannelSpec
[info]   - interpreter
[info]     - reads
[info]       - concurrent reads
[info]         - simple concurrent reads
[info]         - nested concurrent reads
```

**Comment by adamgfraser** [comment]
Observed this test being flaky on another PR as well.

**Comment by iravid** [comment]
@adamgfraser Yeah that's possible. I saw that before but thought the nonFlaky `n` was too high for CI, but might be a real bug.

**Comment by adamgfraser** [comment]
@iravid Ah, okay, maybe we just need to reduce the number of repetitions in `nonFlaky`.

**Pull request merged**
