### PR TITLE
Delete Function To Layer Syntax

### PR DESCRIPTION
**Pull request by adamgfraser**
The function to layer syntax allows very concisely constructing layers based on simple services. However, it has several disadvantages:

1. It requires implicits and adds a bunch of them to the ZIO name space.
2. The exact way you do it is somewhat inconsistent between different Scala versions and treatment of case classes with zero parameters.
3. The mechanics are a little weird particularly with having to use the `apply` method explicitly.
4. It does not scale to cases where the service requires some initialization and finalization unlike the for comprehension pattern.

I tend to think that on balance always constructing layers using a for comprehension provides a highly consistent way of constructing layers that scales from simple cases to arbitrary complex ones.

### CODE REVIEW

**Review by jdegoes — APPROVED** [review]

**Comment by aartigao** [comment]
I'm really sad this has been removed. I don't know if we are weirdos but our codebase is 95% straightforward layers (`XXX.toLayer` where `XXX` is a case class), and 5% layers that need specific builds like `Ref` and we use forcomps for them. With this changes we're forced to make our codebase more verbose, just for this 5%.

**Comment by fourth44** [comment]
Requiring an entire for comprehension as mandatory syntax for essentially a simple 'zio lambda' is quite extreme. Conjuring services with ZIO.service[] is logical. Conjuring plain values that are needed as case class arguments with ZIO.service[] is very confusing.

**Comment by adamgfraser** [comment]
Thanks for your feedback. There is definitely a balance here and we're working on other solutions for the simple case. While the syntax made the simple cases quite concise many people also reported finding it confusing and it created two different ways of constructing layers.

Note that I would generally only recommend having services depend on other services. If you have inputs to an implementation that aren't themselves services you can just create them in the for comprehension if they are produced by `ZIO` workflows or provide them directly if they are just values. This is actually one advantage of the for comprehension approach.

**Comment by kitlangton** [comment]
@aartigao @fourth44 A PR for a replacement is here: https://github.com/zio/zio/pull/6563

**Pull request merged**
