### PR TITLE
Transducer >>> Sink : squash empty chunks

### PR DESCRIPTION
**Pull request by simpadjo**

### CODE REVIEW

**Comment by simpadjo** [comment]
I stumbled upon this operator and in wanted to just remove code duplication. In complex pipelines with fat transducers empty chunks might dominate the traffic. There is no reason emitting them.
Although I would be happy to drop this PR in favor of https://github.com/zio/zio/issues/3672 .

**Comment by iravid** [comment]
Ok, I don't mind merging given a test.

**Comment by simpadjo** [comment]
Hm, now stream tests are randomly failing. Let's postpone it unless we have a stable release.

**Comment by iravid** [comment]
The `groupedWithin` test is known to be flaky though. Not sure it's related.

**Comment by jdegoes** [comment]
@iravid Please re-open if necessary, will close for now!

**Pull request closed without merging**
