### PR TITLE
Add ZStream#batch/batchWeighted

### PR DESCRIPTION
**Pull request by tuleism**
Ref #1025

### CODE REVIEW

**Comment by jdegoes** [comment]
@tuleism Looks useful!

@iravid Would the sink version be `transduce`, or did you have something else in mind??

**Comment by iravid** [comment]
Hey @tuleism, nice work! This is useful! I think it would be even nicer to have the sink you've created available as `ZSink.foldWeighted` for additional reuse.

I had a different idea in mind however for this combinator: it should allow a faster upstream to progress independently of a slower downstream, aggregating elements up to a maximum cost for as long as the downstream is busy.

This combinator should essentially split the stream into two fibers, one pulling elements from upstream and aggregating them, and one pulling the aggregated elements.

**Comment by tuleism** [comment]
Thanks! I will modify the PR.

**Comment by regiskuckaertz** [comment]
My kingdom for a port of [`groupedWeightedWithin`](https://doc.akka.io/docs/akka/current/stream/operators/Source-or-Flow/groupedWeightedWithin.html) too.

@iravid 

> it should allow a faster upstream to progress independently of a slower downstream

isn't this a property you'd want for many combinators (as `buffer` already) and thus could be moved into a generic `transduce`?

**Comment by iravid** [comment]
No doubt there's a more generic combinator hiding here, I just don't know what it is :-) `groupedWeightedWithin` and `batchWeighted` differ only by what triggers aggregation; in the former, it's the schedule that triggers it, and in the latter, it's the backpressure from the buffer.

It'd be nice to abstract over this difference, but I'm not sure how to represent the backpressure from the buffer

**Comment by iravid** [comment]
Also I'm not sure if it's right for `transduce` to automatically introduce a buffer. My intuition is that introducing a buffer should be fairly explicit on the user's side as it can drastically affect memory usage (particularly when working with streams of chunks).

**Comment by regiskuckaertz** [comment]
Yes it looks like the all could rely on a schedules with the help of a few additional constructors. Agreed for `transduce`.

**Comment by iravid** [comment]
Hey @tuleism, let us know if you require any help with pushing this forward.

**Comment by tuleism** [comment]
@iravid sure. Sorry, I'm a bit busy right now. I will find some time to continue this week.

**Comment by jdegoes** [comment]
@tuleism Just for hygiene, I will close this for now, but we're very much looking forward to seeing this PR completed!

**Pull request closed without merging**
