### PR TITLE
update test documentation (test aspects)

### PR DESCRIPTION
**Pull request by unclebob418**
added a section for Test Aspects

pretty light on with the text but I think the code/comments does all the talking required

I couldn't successfully run `docs/docusaurusCreateSite` per the contributing guide. Looks like Yarn doesn't play nice with git bash/windows :(

Guessing circleCI will tell me if there's an issue

### CODE REVIEW

**Comment by unclebob418** [comment]
@adamgfraser can you please review?

**Comment by unclebob418** [comment]
Thanks, and hooray! my first approved change :)

What now? Does approved mean merged? Should I close this PR now or do I need to do something else?

**Comment by adamgfraser** [comment]
I was just going to give it a little while in case anyone else had comments and then merge it. Once it is merged the PR status will automatically be updated and there will be an option for you to delete your local branch. But don't do that yet.

**Comment by adamgfraser** [comment]
@unclebob418 Congratulations on your first contribution! Looking forward to getting the next one merged soon!

**Pull request merged**
