### PR TITLE
Make Schedule.resetWhen/resetAfter behave like their versions in ZIO 2.0

### LINKED ISSUE #6452: Schedule.resetWhen/resetAfter have different behaviour in ZIO 1.0 and ZIO 2.0
The ZIO 1.0 version resets a schedule only once.

https://gist.github.com/sturmin/da042fbb781e40dcf61d3bc76da23c4c
```
//> using scala "2.13"
//> using lib "dev.zio::zio:1.0.13"

import zio._

object App extends zio.App {

    def process(ref: Ref[Int])(predicate: Int => Boolean) = {
        ref.getAndUpdate(_ + 1).flatMap { i =>
            if (predicate(i)) ZIO.succeed(i)
            else ZIO.fail("boom!!!")
        }
    }

    def run(args: List[String]): URIO[ZEnv, ExitCode] = {
        (for  {
            ref <- Ref.make(0)
            v <- process(ref)(_ == 7).retry(Schedule.recurs(3).resetWhen(_ == 3)
            .tapOutput(o => console.putStrLn(s"output $o").orDie))
            _ <- console.putStrLn(v.toString())
        } yield ()).exitCode
    }
}
```

```
scala-cli run https://gist.github.com/sturmin/da042fbb781e40dcf61d3bc76da23c4c                                                                                                  
output 0
output 1
output 2
output 0
output 1
output 2
output 3
Fiber failed.
A checked error was not handled.
boom!!!
Fiber:Id(1647694710707,1) was supposed to continue to:
```

And the ZIO 2.0 version for comparison:
```
//> using scala "2.13"
//> using lib "dev.zio::zio:2.0.0-RC3"
import zio._
import zio.Console._

object App extends zio.ZIOAppDefault {

    def process(ref: Ref[Int])(predicate: Int => Boolean) = {
        ref.getAndUpdate(_ + 1).flatMap { i =>
            if (predicate(i)) ZIO.succeed(i)
            else ZIO.fail("boom!!!")
        }
    }

    def run = {
        for  {
            ref <- Ref.make(0)
            v <- process(ref)(_ == 7).retry(Schedule.recurs(3).resetWhen(_ == 3)
            .tapOutput(o => printLine(s"output $o").orDie))
            _ <- printLine(v.toString())
        } yield ()
    }
}
```

```
scala-cli run https://gist.github.com/sturmin/d10a6de1c9ef78ccd13f177328126b01                                                                                                  
output 0
output 1
output 2
output 0
output 1
output 2
output 0
7
```
What behaviour is expected one?

### PR DESCRIPTION
**Pull request by sturmin**
Fixed #6452

### CODE REVIEW

**Comment by adamgfraser** [comment]
Can you format?

**Comment by sturmin** [comment]
Yes, I have formatted it.

**Review by adamgfraser — APPROVED** [review]

**Comment by sideeffffect** [comment]
Just a heads up, this won't make it to `series/2.x`, is that OK?
https://github.com/zio/zio/pull/7853

**Comment by adamgfraser** [comment]
@sideeffffect I am maintaining ZIO 2 completely separately from ZIO 1. I would encourage you to do new development exclusively on the ZIO 2 branch. I know you have preferred to do work on the ZIO 1 branch and pull it into the ZIO 2 branch which is fine but I am not expecting any other changes to be pulled into the ZIO 2 branch. So totally fine this is not included.

**Pull request merged**
