### PR TITLE
fix:  flaky test of `ZStream.tapSink`

### LINKED ISSUE #8792: ZStream.tapSink, either a flaky test or flaky implementation
I've encountered this failure on my local env (saw it once, wasn't able to reproduce):

```scala
 - ZStreamSpec / Combinators / tapSink / does not read ahead - 5 ms
        ✗ 1 was not equal to 6
        result == 6
        result = 1
        at /Users/efarago/dev/github/zio/streams-tests/shared/src/test/scala/zio/stream/ZStreamSpec.scala:3727 
```

I suspect the issue depends on `ZStream.tapSink` 's guarantees in face of downstream cancellation;
If it guarantees that all emitted values were processed by the sink as well this is a real bug,
on the other hand if this is not guaranteed then this test is flaky as it cannot expect all values to have been processed by the sink (it can be relaxed to actually asset what its name suggests).

looking at `ZStream.tapSink` 's implementation it seems to me that once downstream completes the `merge` will also be halted, this effectively means interrupting both sides of the merge (if still running) which is done by fiber interruption. since there's no guarantee which one is interrupted first the ensuring block in `tapSink` can't guarantee proper completion of the sink.

I was able to show this with an awkward test:
```scala
test("early termination with a slow sink") {
            for {
              ref    <- Ref.make(0)
              stream  = ZStream(1, 2, 3, 4, 5).rechunk(1).forever
              sink    = ZSink.foreach((n: Int) => ZIO.sleep(2.second) *> ref.update(_ + n))
              fib     <- stream.tapSink(sink).take(1).mapZIO(_ => ZIO.sleep(1.second)).runDrain.fork
              _       <- TestClock.adjust(1.second)
              _       <- fib.join
              result <- ref.get
              _       <- ZIO.fail(s"fiber shouldn't have completed! (result=$result)")
            } yield {
              assertTrue(result == 0)
            }
          }
```

the test is awkward since it's expected to halt (if tapSink's guarantee is strong enough), instead it explicitly fails when the stream execution completes.

### PR DESCRIPTION
**Pull request by varshith257**
/fixes https://github.com/zio/zio/issues/8792
/claim https://github.com/zio/zio/issues/8792

### CODE REVIEW

**Comment by varshith257** [comment]
@jdegoes It is a follow-up to https://github.com/zio/zio/pull/8946#issuecomment-2184969248

Please take a look 🙏

And another PR is opened a month back. Can you also have a look at it?

- https://github.com/zio/zio-quickstarts/pull/56

**Comment by kyri-petrou** [comment]
@varshith257 as [I mentioned before](https://github.com/zio/zio/pull/8946#issuecomment-2253400753), this doesn't solve the issue; it'll only make the flakiness appear more often. `nonFlaky` runs the test 100 times, but if you use `nonFlaky(10000)` it is almost guaranteed to fail.

I'm closing this PR, if you'd like to close the issue the PR needs to contain a fix to the implementation of `tapSink`

**Comment by varshith257** [comment]
@kyri-petrou I have worked with it for a long time. To reflect its current behaviour of it I updated the tests:

1. https://github.com/zio/zio/pull/8946#issuecomment-2176330478

2. https://github.com/zio/zio/pull/8946#discussion_r1649701152


And here are the logs of the current tapSink behavior 

https://github.com/zio/zio/pull/8946#issuecomment-2176315699


I don't think a better solution of observing its current behaviour rather than updating tests with its current behaviour.

Any solution you are thinking of or had any in mind?

**Comment by kyri-petrou** [comment]
@varshith257 if I knew the solution I would have opened a PR with it myself 🥲

**Comment by varshith257** [comment]
```
Promise awaited
Offered chunk: Chunk(1)
Processing item: 1
+ with burst - 73 ms
Queue shutdown
Promise awaited in merge
Interrupting fiber at: 2024-05-21T20:42:31.411023748Z
+ throttleShape - 130 ms
+ timeoutFail
+ fail - 13 ms
+ succeed - 5 ms
+ timeoutTo
+ succeed - 16 ms
toInputStream: zio.stream.internal.ZInputStream@1e57a128
+ should switch stream - 183 ms
+ should not apply timeout after switch - 209 ms
+ takeUntil - 170 ms
+ takeWhile short circuits - 1 ms
+ takeRight - 253 ms
+ tap
+ tap - 4 ms
+ laziness on chunks - 4 ms
+ takeUntilZIO - 300 ms
+ tapBoth
+ just tap an error - 40 ms
+ tap values and then error - 40 ms
+ just tap values - 41 ms
+ tap chunks lazily - 40 ms
+ tapError
+ tapError - 22 ms
+ takeWhileZIO
+ takeWhileZIO - laziness on chunks - 5 ms
+ takeWhileZIO - 226 ms
+ tapSink
+ sink that is done before stream - 37 ms
+ sink that is done after stream - 43 ms
+ sink that fails before stream - 40 ms
- does not read ahead
Exception in thread "zio-fiber-104649" java.lang.InterruptedException: Interrupted by thread "zio-fiber-104649"
at zio.stream.ZStreamSpec.spec(ZStreamSpec.scala:3725)
```

@kyri-petrou See here's the log of current behaviour of tapskink.

**Comment by varshith257** [comment]
This logs show multiple Promise succeeded and Promise awaited entries, indicating that the promise works correctly. The Offered chunk entries confirm that chunks are being offered to the queue as intended. I have also reviewed the implementation of `ZSink.foreach` and ensured that it processes items immediately upon receiving them.

Based on the debugging and the implementation review, the tapSink method appears to ensure that the sink processes all values before the stream completes and is working fine for what it was designed.

After further investigating the tapsink behaviour, its non-deterministic behaviour doesn't guarantee the sink to process all elements in of downstream cancellation. The test should not assume that all values have been processed by the sink, as this is not guaranteed.

**Pull request closed without merging**
