### PR TITLE
Implement ZIO#service

### PR DESCRIPTION
**Pull request by adamgfraser**
Following up on good suggestion from @ghostdogpr implements `getService` which is like `environment` but does the `get` for you. So if you wanted the `Clock.Service` you could do `ZIO.getService[Clock.Service]` and get a `ZIO[Clock, Nothing, Clock.Service]`. Still needs variants for other type aliases and other ZIO effect types assuming we like this.

### CODE REVIEW

**Comment by hmemcpy** [comment]
Not a huge fan of the get* prefix, but overall +1 :)

**Comment by adamgfraser** [comment]
@hmemcpy You would prefer just `service`?

**Comment by hmemcpy** [comment]
I think it would be more consistent, yes.

**Comment by adamgfraser** [comment]
I'm not opposed to it. I think the original line of thinking was starting with something like `accessService` and then shortening it to `getService`, but I can see the symmetry of `service` with `environment`.

**Pull request merged**
