### PR TITLE
Akka docs - remove duplicate line (Entity Sharding)

### PR DESCRIPTION
**Pull request by pjfanning**
Entity Sharding already appears in the table (line 19).

### CODE REVIEW

**Comment by pjfanning** [comment]
@khajavi thanks for doing the akka migration doc - I noticed this small issue - could you have a look?

**Review by khajavi — DISMISSED** [review]
Thank you! :pray:

**Comment by adamgfraser** [comment]
@pjfanning Can you resolve conflicts?

**Review by adamgfraser — APPROVED** [review]

**Comment by pjfanning** [comment]
@adamgfraser I resolved the conflict

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
