### PR TITLE
#5849 Create test suite for Cause.prettyPrint

### PR DESCRIPTION
**Pull request by baldram**
Here is an implementation of 3 test cases out of the ticket description. If there is any additional thing we could check, please let me know.

I check failures existence in the stack trace, including pretty markers.

---
Blocked by: https://github.com/zio/zio/pull/5931
A target branch to be switched then, and changes adjusted.

---
A new, "clean" MR created https://github.com/zio/zio/pull/5949.
Closing this one.

### CODE REVIEW

**Comment by jdegoes** [comment]
@baldram Can you base your work of `series/2.x`? The `master` branch is for ZIO 1.x, and it already has tests.

Thank you!

**Comment by baldram** [comment]
I will base my work of series/2.x. Actually I tried, and then I faced an issue when calling `cause.prettyPrint`:
```
Exception in thread "zio-fiber-0" java.lang.NumberFormatException: java.lang.NumberFormatException: For input string: "\data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala"
```
It seems like some bug has appeared. Once I find a solution, I will deliver a result of work adjusted for 2.x.

**Comment by baldram** [comment]
A ticket is blocked by a bug I found when executing `cause.prettyPrint`. 
The problem is with casting `.toInt` on some strings.

Here is a code causing an issue:
```scala
case regex(location, file, line, column) => Some((location, file, line.toInt, column.toInt))
``` 
It gives:
```
Exception in thread "zio-fiber-0" java.lang.NumberFormatException: java.lang.NumberFormatException: For input string: "81:26"
```
Tried to look for the root cause. Below, what is happening in the pattern matching mentioned above. 
In my case (Windows unfortunately 😏) I get the following:
```
location=[zio.StackTracesSpec.spec.failure], 
file=[C], 
line=[\data\git\zio-hackaton\zio\core-tests\shared\src\test\scala\zio\StackTracesSpec.scala], 
column=[81:26]
```
Now, the line, and column can't be casted in this way.
Not sure whether a bug https://github.com/zio/zio/issues/5914 is about the same problem, or we need a new one.

Another possibility is to fix it within this ticket. 
However I'm not sure whether we should extend the mentioned pattern matching in Tracer, or it's a problem with strings generated by macro?

**Comment by baldram** [comment]
Ok, here is a bug connected to the problem.
https://github.com/zio/zio/issues/5917

**Pull request closed without merging**
