### PR TITLE
Port absorb and absorbWith combinators to ZManaged

### PR DESCRIPTION
**Pull request by alexvanolst**
Part of #2077 

These were trivial to port over and seem to make sense to me.

### CODE REVIEW

**Comment by iravid** [comment]
Would be great if you could add a test for `absorbWith` as well.

**Comment by alexvanolst** [comment]
@iravid I've alphabetized the methods and added tests.

There were no existing tests for `absorbWith` on `ZIO` , so added those first. Had to also port `run` to ZManaged to be able to test on failures. 

Now we're in the same situation again where `run` has no tests on `ZIO` or `ZManaged` and I've not got much time left this weekend.

If the `run` on `ZManaged` seems reasonable to you can I suggest we open a ticket for all the missing tests on `ZIO` and `ZManaged`?

**Comment by iravid** [comment]
@alexvanolst I tried to fix the conflicts but messed up the formatting. Can you run an fmt here? Then we can merge this. Great work here!

**Comment by iravid** [comment]
Thank you @alexvanolst!

**Pull request merged**
