### PR TITLE
Implement Schedule#fromDurations

### LINKED ISSUE #3205: Missing API for `ZSchedule` which takes a list of durations
Sometime, we want to exexcute a given action after specific (user provided) intervals of time, and it would be handy to have a pair of API for that: one matching `fixed` semantic, and one matching `spaced` one. 

I imagine a combinator taking a list of durations for parameter, and building the corresponding schedule so that: 
```
// start action for each of the provided times: 
val s1 = ZSchedule.startAt(0 second :: 2 minutes :: 5 minutes :: Nil)

// start action at 0s, then 2min after end of first action, then 5 minutes after end of second action
val s2 = ZSchedule.startSpacedBy(0 second :: 2 minutes :: 5 minutes :: Nil)
```
(I will let you choose better names

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #3205.

### CODE REVIEW

**Comment by adamgfraser** [comment]
@mijicd I'm seeing some test failures here in `StreamBufferSpec - Stream.bufferUnbounded - buffer the Stream`. These don't appear to be related to this PR as it only adds new methods to the API of `Schedule` and doesn't use them anywhere. Could this be related to the recent optimizations to `ZQueue`?

**Comment by adamgfraser** [comment]
Looks like the same failures are on `master`.

**Comment by mijicd** [comment]
It might be the case, but I haven't realized these locally or in PR build. Let me see.

**Comment by mijicd** [comment]
Identified and fixed, running benchmarks to double-check. PR coming soon :).

**Comment by mijicd** [comment]
Should be fixed in #3222

**Comment by adamgfraser** [comment]
Copying @jeremyrsmith and @fanf.

**Pull request merged**
