### PR TITLE
Scala Native 0.4.0

### PR DESCRIPTION
**Pull request by sideeffffect**
closes https://github.com/zio/zio/pull/4567
closes https://github.com/zio/zio/pull/4562
closes https://github.com/zio/zio/pull/4604
closes https://github.com/zio/zio/pull/4548

Blocked on
https://github.com/zio/izumi-reflect/pull/121

### CODE REVIEW

**Comment by sideeffffect** [comment]
@adamgfraser and now this :fireworks: 
I'll widen Scala Native to 2.12 and 2.13, but I will do that in the next PR, this is good as it is.

**Review by adamgfraser — APPROVED** [review]
Nice!

**Comment by sideeffffect** [comment]
Btw the branch isn't automatically deleted. I thought we changed that to auto-remove. Or has something changed? :thinking:

**Comment by adamgfraser** [comment]
@sideeffffect `Automatically delete head branches` is checked. I don't know.

**Pull request merged**
