### PR TITLE
[WIP] Cats interop JS support

### PR DESCRIPTION
**Pull request by joroKr21**
Fixed the cats laws:
  * Using safe `Eq` by `cats.effect.IO`
  * Using a deterministic runtime from `TestContext`
  * Using more generators from `GenIO`

Broken laws:
 - [x] `Alternative` right absorption: `ff ap F.empty != F.empty` because if `ff` is an error, it will not be absorbed. (also, seems like `SemigroupK` and `Alternative` are not consistent)
- [ ] `ConcurrentEffect` bracket release is called on Completed or Error
- [x] `ConcurrentEffect` uncancelable prevents Cancelled case
- [x] `Effect` guarantee is derived from bracket: `bracket` throws away the `release` error while `ensuring` doesn't

### CODE REVIEW

**Comment by joroKr21** [comment]
@jdegoes some laws do not pass

**Comment by jdegoes** [comment]
@joroKr21 I would expect a few failures (primarily because Scala.js has no way to "block" and there may be some "forks" that are requiring this). We should disable those tests for now (just in Scala.js), write them up in tickets, and address them after this work.

**Comment by joroKr21** [comment]
The problem was in the runtime used for testing. I changed it to use `TestContext` which is deterministic.
And no blocking is needed to define equality.

But some laws are not passing neither on the JVM nor on JS.
The tests were passing before because the generator used was too naive (`genSuccess`)

**Comment by joroKr21** [comment]
I don't think there is a lawful alternative instance, we might have to just remove it and change semigroupK / monoidK to accumulate errors.

**Comment by joroKr21** [comment]
I don't know about the other laws.

**Comment by joroKr21** [comment]
@jdegoes Wdyt about this suggestion?
  * `Alternative` - remove this instance and replace it with `SemigroupK` and `MonoidK` which combine errors
  * `guarantee` - change `ZIO.bracket` to be consistent with `ZIO.ensuring` and preserve errors

But I would need help to figure out why the `ConcurrentEffect` laws are broken.

**Comment by jdegoes** [comment]
Sorry for the delay on this, it's been a LONG week!

@joroKr21 

> Alternative - remove this instance and replace it with SemigroupK and MonoidK which combine errors

I think we can make a valid `Alternative` for any `Monoid` error type `E`. If one is success, we always choose that; if both are failures, we choose the one with non-empty `E`.
guarantee - change ZIO.bracket to be consistent with ZIO.ensuring and preserve errors

I do think we can do lawful `SemigroupK` and `MonoidK`.

> guarantee - change ZIO.bracket to be consistent with ZIO.ensuring and preserve errors

Can you explain this problem in more depth?

> But I would need help to figure out why the ConcurrentEffect laws are broken.

I am happy to help with that, I spent a lot of work already to ensure compliance with the previous `Gen`. Also it occurs to me that we could split the PR into 2, and deal with broken laws (as a result of a richer `Gen`) in a separate PR.

Please let me know if you need any more help, and thank you for your work on this thus far!

**Comment by joroKr21** [comment]
> Sorry for the delay on this, it's been a LONG week!

No worries, we don't have a deadline :smile: 

> I think we can make a valid Alternative for any Monoid error type E. If one is success, we always choose that; if both are failures, we choose the one with non-empty E.

I don't think this will work. Observe carefully the right absorption law:
```scala
(ff ap F.empty) <-> F.empty
```
Whatever we choose for `F.empty` when `ff` is a failed `ZIO` it will never be absorbed.

> guarantee - change ZIO.bracket to be consistent with ZIO.ensuring and preserve errors

`ZIO.bracket` is defined as: 

```scala
  final def bracket[R >: LowerR, E <: UpperE, A, B](
    acquire: ZIO[R, E, A],
    release: A => ZIO[R, Nothing, _],
    use: A => ZIO[R, E, B]
  ): ZIO[R, E, B] =
    bracketExit(acquire, (a: A, _: Exit[E, B]) => release(a), use)
```

Note how the `Exit` is ignored (thrown away).

`ensuring` (which is used to implement `guarantee`) is defined like this:

```scala
 final def ensuring[R1 <: R](finalizer: ZIO[R1, Nothing, _]): ZIO[R1, E, A] =
    ZIO.uninterruptibleMask(
      restore =>
        restore(self)
          .foldCauseM(
            cause1 =>
              finalizer.foldCauseM[R1, E, Nothing](
                cause2 => ZIO.halt(cause1 ++ cause2),
                _ => ZIO.halt(cause1)
              ),
            value =>
              finalizer.foldCauseM[R1, E, A](
                cause1 => ZIO.halt(cause1),
                _ => ZIO.succeed(value)
              )
          )
)
```

cats-effect requires consistency here. Is there any harm in preserving the error in `bracket` as well? Since the philosophy in ZIO is not to lose any errors.

> Also it occurs to me that we could split the PR into 2, and deal with broken laws (as a result of a richer Gen) in a separate PR.

I would say let's decide on `Alternative` and `bracket` here and we can leave the `Concurrent` issues for later.

**Comment by jdegoes** [comment]
@joroKr21 

> I don't think this will work. Observe carefully the right absorption law:

In my opinion the right absorption law is a mistake and disallows all effect instances. But since Cats has it, we have to respect it.

> cats-effect requires consistency here. Is there any harm in preserving the error in bracket as well? Since the philosophy in ZIO is not to lose any errors.

No harm at all, in fact, it should be done. It was probably a consequence of me pulling so much more logic out of the runtime system after interruptible regions landed. We'll just have to compose it the right way with any other errors in the finalizer (preserving sequencing), and add a test or two.

This is great work, I appreciate your attention to detail and care. Let me know if you need anything else to get unstuck!

**Comment by joroKr21** [comment]
Sorry for the delay! Crazy few weeks at work :sweat_smile: 

> In my opinion the right absorption law is a mistake and disallows all effect instances. But since Cats has it, we have to respect it.

Maybe, if it's removed at some point an instance could be added but best not to risk breaking someone's code.

> No harm at all, in fact, it should be done. It was probably a consequence of me pulling so much more logic out of the runtime system after interruptible regions landed. We'll just have to compose it the right way with any other errors in the finalizer (preserving sequencing), and add a test or two.

Perfect!

Ok, I think tomorrow I could wrap up this PR :100:

**Comment by joroKr21** [comment]
Uh, rebasing this was very difficult (first, the entire namespace moved and then more interop was added in between). Now it seems that more laws are failing than before :disappointed:

**Comment by joroKr21** [comment]
Ah, nvm it's because a new `Cause` was added, needed to update the `Eq` instance.

**Comment by ghostdogpr** [comment]
Actually cats-interop is being moved to its own repo: https://github.com/zio/interop-cats 

The move isn’t finished yet but maybe you can already open the PR there?

**Comment by joroKr21** [comment]
Yes we could do that but then would need another PR before that to change `bracket`'s error handling.

**Comment by joroKr21** [comment]
I can't seem to make all tests pass. The signature of `ZIO.bracket` doesn't allow to halt with a combination of the `release` error and the `ExitCase` cause.

Also any tips on how to debug the concurrent test failures?

**Comment by joroKr21** [comment]
I took a closer look at the `bracket` vs `guarangee` failure. @jdegoes I think the problem is that `ensuring` will halt when the finalized halts, whereas `bracketExit` always returns the exit from `use`.
Here is the code for comparison:
```scala
 final def ensuring[R1 <: R](finalizer: ZIO[R1, Nothing, _]): ZIO[R1, E, A] =
    ZIO.uninterruptibleMask(
      restore =>
        restore(self)
          .foldCauseM(
            cause1 =>
              finalizer.foldCauseM[R1, E, Nothing](
                cause2 => ZIO.halt(cause1 ++ cause2),
                _ => ZIO.halt(cause1)
              ),
            value =>
              finalizer.foldCauseM[R1, E, A](
                cause1 => ZIO.halt(cause1),
                _ => ZIO.succeed(value)
              )
          )
    )
```
```scala
  final def bracketExit[R >: LowerR, E <: UpperE, A, B](
    acquire: ZIO[R, E, A],
    release: (A, Exit[E, B]) => ZIO[R, Nothing, _],
    use: A => ZIO[R, E, B]
  ): ZIO[R, E, B] =
    ZIO.uninterruptibleMask[R, E, B](
      restore =>
        acquire.flatMap(ZIOFn(traceAs = use) { a =>
          restore(use(a)).run.flatMap(ZIOFn(traceAs = release) { e =>
            release(a, e) *>
              ZIO.done(e)
          })
        })
    )
```

**Comment by joroKr21** [comment]
I just removed the override to `guarangee` and that solves the issue.

**Comment by jdegoes** [comment]
@joroKr21 I have to apologize for my tardiness on this pull request! I got overwhelmed a bit with LambdaConf preparations.

I'm just getting caught up now.

> I took a closer look at the bracket vs guarangee failure. @jdegoes I think the problem is that ensuring will halt when the finalized halts, whereas

Is the problem we get the wrong error from `bracketExit`? I see it ignores the release error now, which I can fix quite simply (an oversight).

Anything else that needs attention? After we get this sorted, we may have to move the PR Over to `interop-cats`, where the "official" version now lives.

**Comment by joroKr21** [comment]
> Is the problem we get the wrong error from bracketExit? I see it ignores the release error now, which I can fix quite simply (an oversight).

Ah yes, that's true. So we can change `bracketExit` or remove the override to `guarantee` (which is what I did here). What would you prefer? 

> Anything else that needs attention?

There is one last failing law: "bracket release is called on completed or error" which is actually an `Async` law so I think it's important to get to the bottom of it. Note that we are not generating any interrupted ZIOs.

Also I started seeing some scala.js linking errors, maybe I changed the build in a wrong way during rebase?

**Comment by joroKr21** [comment]
I opened #1041 for the `bracketExit` change.

**Comment by jdegoes** [comment]
@joroKr21 I will close this. Can you reopen on interop-cats repository? I'd love to help you get this through!

**Comment by joroKr21** [comment]
This one failing law has become my nemesis :D

**Pull request closed without merging**
