### PR TITLE
Improve build configuration

### PR DESCRIPTION
**Pull request by sideeffffect**
Upgrade and consolidate versions

### CODE REVIEW

**Review by jdegoes — DISMISSED** [review]

**Comment by jdegoes** [comment]
Be sure to run `fmt` to format the build files.

**Comment by sideeffffect** [comment]
Some spurious failures. Can somebody please restart the builds? :pray:

**Review by mijicd — APPROVED** [review]
Looks good to me! Please verify that giter8 template is also up to date :pray:

**Comment by sideeffffect** [comment]
@mijicd sorry, I don't know what you mean. Btw could you restart that dead build?

**Comment by mijicd** [comment]
@sideeffffect Sorry,  I was referring to https://github.com/zio/zio-project-seed.g8 :). Restarting build now.

**Comment by sideeffffect** [comment]
@mijicd done https://github.com/zio/zio-project-seed.g8/pull/26

**Comment by sideeffffect** [comment]
one build died, but otherwise we're good to go
can you @mijicd please restart it?

**Comment by sideeffffect** [comment]
we're green :tada:

**Review by adamgfraser — APPROVED** [review]

**Comment by sideeffffect** [comment]
Thanks @adamgfraser! Do you think you could restart that one failed job? :pray: 
https://app.circleci.com/pipelines/github/zio/zio/8958/workflows/2bdcdd4b-a998-4211-b6ef-67d11720c9dd

**Pull request merged**
