### PR TITLE
Fix delim-splitting for Config.secret

### PR DESCRIPTION
**Pull request by domartynov**

### CODE REVIEW

**Comment by jdegoes** [comment]
@domartynov Can you check that this is fixed by @adamgfraser's PR?

**Comment by jdegoes** [comment]
Would be great to merge in your test!

**Comment by adamgfraser** [comment]
Yes we deleted the separate logic path for this so now this just works. I think the fact that we had to special case it was an indication that there was something wrong because we didn't have the ability to load a whole value versus a collection of values. Just added a test.

**Comment by adamgfraser** [comment]
Superseded by #7724.

**Pull request closed without merging**
