### PR TITLE
Implement test reporter

### PR DESCRIPTION
**Pull request by adamgfraser**
Implements a default console reporter for new test framework as discussed in #1229. Displaying successful and failed tests, as well as highlighting of failed predicate fragments, is implemented. Options for turning display of colors on / off and summary of failures is not yet implemented.

The only change I made to the rest of the API is adding a `R` type parameter to the `Reporter`, since the `Reporter` may need to access an environment (typically `Console` but I suppose it could be something else if the report writes the results to a file or something) to report the results. This also facilitates testing the `Reporter` itself using a `MockConsole`. Changes were pretty minor but open to feedback if you think there is a better way to do this.

### CODE REVIEW

**Comment by jdegoes** [comment]
@adamgfraser Circle CI couldn't download the OpenJDK which screwed up a bunch of builds. Can you fix conflicts and I'll re-trigger a full build?

**Comment by jdegoes** [comment]
On adding `R` to `TestReporter`, just for simplicity I might do:

```scala
object TestReporter {
  def console(console: Console): TestReporter = ...
}
```

Although I don't have a big preference. But if we have `R` in `TestReporter`, we should probably add to the other things as well, `TestExecutor`, etc. to describe the set of all dependencies required to run something.

**Comment by jdegoes** [comment]
giphy

**Comment by adamgfraser** [comment]
Thanks John!

**Pull request merged**
