### PR TITLE
Silencer: checkUnused

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
blocked on https://github.com/zio/zio/pull/4551

**Review by adamgfraser — APPROVED** [review]

**Comment by sideeffffect** [comment]
Can we please check _Automatically delete head branches_ in GitHub settings, so that we don't have to do it manually? I don't want to have "dangling" branches in my fork repo of ZIO, but I don't always remember to click the delete button.
:pray:

**Comment by sideeffffect** [comment]
And analogously for the ZIO Prelude repository
:bow:

**Comment by adamgfraser** [comment]
@sideeffffect Just updated that setting.

**Pull request merged**
