### PR TITLE
Make Cats fibers interruptible

### LINKED ISSUE #945: Cats Effect interop needs updating in light of inherited interruption status
In Cats Effect, interruption status is not inherited, and every "started" fiber starts off as interruptible. In the interop layer, we need to match Cats Effect semantics.

We should also look for other places where semantics have changed to warrant introduction of, e.g. `interruptibleMask`.

### PR DESCRIPTION
**Pull request by ghostdogpr**
Fixes #945

### CODE REVIEW

**Comment by iravid** [comment]
Is there a test you could add to demonstrate what got broken? I think someone posted a problematic case with `Resource` on Gitter.

**Comment by ghostdogpr** [comment]
@iravid I added a test. It hangs with the old code, passes with the new.

**Comment by kaishh** [comment]
Is it possible for a fiber to get leaked if an interrupt comes exactly during execution of `Fork`? Not sure about that...

**Comment by jdegoes** [comment]
@ghostdogpr Awesome work, this will warrant RC5 as soon as Scaladoc is fixed.

**Pull request merged**
