### PR TITLE
Set `Test / fork := true` to improve log readability

### PR DESCRIPTION
**Pull request by sideeffffect**
@adpi2
> @swoogles @sideeffffect I looked into your problem and this is what I found:
> - It is not specific to zio-test framework. I can reproduce it with any other test framework.
> - The problem disappears with `Test / fork := true` but that's a weird side effect of the `concurrentRestrictions` on `forked-test-group`

https://discord.com/channels/632150470000902164/922600050989875282/1016386123322364074

### CODE REVIEW

**Review by swoogles — DISMISSED** [review]
Yep, if this behaves acceptably in CI, it's what we need to do according to the SBT folks

**Comment by swoogles** [comment]
Ah, not surprising that this blows up in ScalaJS. We'll have to make sure it's not applied there.

**Review by swoogles — APPROVED** [review]
Thanks for this!

**Comment by swoogles** [comment]
Shoot, I just realized this was only targeting `1.x`.

That's fine, but we'll also want it in `2.x`

**Comment by sideeffffect** [comment]
Fixes bad readability introduced in https://github.com/zio/zio/pull/7049

**Pull request merged**
