### PR TITLE
Support use of @accessible macro with implicits (#4466)

### PR DESCRIPTION
**Pull request by nadenf**
Existing automated tests pass but not sure how useful they are given that never picked up the bug described in #4466.

However manual testing with various combinations of implicits and normal parameters appear to work fine.

### CODE REVIEW

**Comment by nadenf** [comment]
@ioleo .. Are you able to review/approve this ?

**Review by ioleo — APPROVED** [review]
Thanks for bringing that one to my attention. It looks good to me.

**Comment by adamgfraser** [comment]
@nadenf Thanks for working on this and apologies for the delay! Can you merge upstream changes to trigger CI and then we can get this in?

**Review by adamgfraser — APPROVED** [review]

**Review by ioleo — APPROVED** [review]

**Comment by ioleo** [comment]
@adamgfraser can you merge it?

**Pull request merged**
