### PR TITLE
[WIP] Scala Native: run tests, ZIO 2

### PR DESCRIPTION
**Pull request by sideeffffect**
complements https://github.com/zio/zio/pull/7031

### CODE REVIEW

**Comment by sideeffffect** [comment]
Unfortunately the test's don't run at all, they seem to crash right after they are supposed to start, e.g.:
```sh
sbt> coreTestsNative/testOnly zio.ZIOSpec
[info] Starting process '/home/ondra/Projects/zio/core-tests/native/target/scala-2.13/core-tests-test-out' on port '40119'.
[info] No tests were executed
[error] Error during tests:
[error] 	zio.ZIOSpec
[error] (coreTestsNative / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1 s, completed Feb 28, 2023, 12:47:43 PM
```
@lolgab would you have any idea or hint what could be going wrong here? Or how to debug it? :pray:

**Comment by jdegoes** [comment]
@sideeffffect Try to see why the tests failed execution (turn on verbose error output or view last error in SBT).

**Comment by sideeffffect** [comment]
Here's the output. I hope it will be helpful. How do I "turn on verbose error output"?
```
coreTestsNative/test
[info] Starting process '/home/ondra/Projects/zio/core-tests/native/target/scala-2.13/core-tests-test-out' on port '40795'.
[info] Starting process '/home/ondra/Projects/zio/core-tests/native/target/scala-2.13/core-tests-test-out' on port '33325'.
[info] No tests were executed
[error] Error during tests:
[error] 	zio.PromiseSpec
[error] 	zio.QueueSpec
[error] 	zio.stm.TRandomSpec
[error] 	zio.ConfigProviderEnvSpec
[error] 	zio.stm.ZSTMSpec
[error] 	zio.stm.TSetSpec
[error] 	zio.ZStateSpec
[error] 	zio.ZIOLazinessSpec
[error] 	zio.ScopedRefSpec
[error] 	zio.FiberRefsSpec
[error] 	zio.ChunkBuilderSpec
[error] 	zio.ZIOSpec
[error] 	zio.ZKeyedPoolSpec
[error] 	zio.HubSpec
[error] 	zio.UnsafeSpec
[error] 	zio.internal.FastListSpec
[error] 	zio.ChunkAsStringSpec
[error] 	zio.CauseSpec
[error] 	zio.NonEmptyChunkSpec
[error] 	zio.ChunkSpecVersionSpecific
[error] 	zio.autowire.InjectParameterizedServicesSpec
[error] 	zio.stm.TReentrantLockSpec
[error] 	zio.stm.TSemaphoreSpec
[error] 	zio.autowire.AutoWireSpec
[error] 	zio.ZPoolSpec
[error] 	zio.ChunkBufferSpec
[error] 	zio.stm.TMapSpec
[error] 	zio.metrics.PollingMetricSpec
[error] 	REPLSpec
[error] 	zio.stm.THubSpec
[error] 	zio.FiberSpec
[error] 	zio.BitChunkIntSpec
[error] 	zio.SupervisorSpec
[error] 	zio.RuntimeFlagsSpec
[error] 	zio.ReloadableSpec
[error] 	zio.stm.STMLazinessSpec
[error] 	zio.TaggedSpec
[error] 	zio.StackTracesSpec
[error] 	zio.internal.WeakConcurrentBagSpec
[error] 	zio.TagCorrectnessSpec
[error] 	zio.DurationSpec
[error] 	zio.ChunkSpec
[error] 	zio.TrivialSpec
[error] 	zio.CancelableFutureSpec
[error] 	zio.stm.TPriorityQueueSpec
[error] 	zio.RefSpec
[error] 	zio.stm.TArraySpec
[error] 	zio.CanFailSpec
[error] 	zio.RandomSpec
[error] 	zio.DifferSpec
[error] 	zio.ClockSpec
[error] 	zio.MetricSpec
[error] 	zio.BitChunkByteSpec
[error] 	zio.HigherKindedTagCorrectness
[error] 	zio.internal.GrowableArraySpec
[error] 	zio.ScheduleSpec
[error] 	zio.internal.HubSpec
[error] 	zio.internal.StackSpec
[error] 	zio.internal.metrics.ConcurrentSummarySpec
[error] 	zio.FiberRefSpec
[error] 	zio.CachedSpec
[error] 	zio.ConfigSpec
[error] 	zio.ScopeSpec
[error] 	zio.ConfigProviderSpec
[error] 	zio.ChunkPackedBooleanSpec
[error] 	zio.ImportlessSpec
[error] 	zio.LoggingSpec
[error] 	zio.ExecutorSpec
[error] 	zio.internal.MutableConcurrentQueueSpec
[error] 	zio.ZEnvironmentSpec
[error] 	zio.RefSynchronizedSpec
[error] 	zio.ZIOAppSpec
[error] 	zio.stm.TQueueSpec
[error] 	zio.ZLayerSpec
[error] 	zio.ZEnvironmentIssuesSpec
[error] 	zio.BitChunkLongSpec
[error] 	zio.ThreadLocalBridgeSpec
[error] 	zio.internal.metrics.MetricListenerSpec
[error] (coreTestsNative / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 5 s, completed Mar 8, 2023, 12:21:46 AM
[IJ]last coreTestsNative/Test/test
[debug] Running TaskDef(zio.PromiseSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@51cafe96, false, [SuiteSelector])
[debug] Running TaskDef(zio.QueueSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@66f85504, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TRandomSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@1d958952, false, [SuiteSelector])
[debug] Running TaskDef(zio.ConfigProviderEnvSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@1c6d3a57, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.ZSTMSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@3ac8c8e5, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TSetSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@5f1538ef, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZStateSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@35310d8e, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZIOLazinessSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@639fe514, false, [SuiteSelector])
[debug] Running TaskDef(zio.ScopedRefSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@1a59bd1, false, [SuiteSelector])
[debug] Running TaskDef(zio.FiberRefsSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@303dc849, false, [SuiteSelector])
[debug] Running TaskDef(zio.ChunkBuilderSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2dd51bf9, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZIOSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@327817ab, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZKeyedPoolSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@38d96d1, false, [SuiteSelector])
[debug] Running TaskDef(zio.HubSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@7ee5a493, false, [SuiteSelector])
[debug] Running TaskDef(zio.UnsafeSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@1d71446b, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.FastListSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@38c214cb, false, [SuiteSelector])
[debug] Running TaskDef(zio.ChunkAsStringSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2a710104, false, [SuiteSelector])
[debug] Running TaskDef(zio.CauseSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@6265b8a0, false, [SuiteSelector])
[debug] Running TaskDef(zio.NonEmptyChunkSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@3aa58d87, false, [SuiteSelector])
[debug] Running TaskDef(zio.ChunkSpecVersionSpecific, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@108bf457, false, [SuiteSelector])
[debug] Running TaskDef(zio.autowire.InjectParameterizedServicesSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@cd01ef8, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TReentrantLockSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@76a21e06, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TSemaphoreSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@15c03ff0, false, [SuiteSelector])
[debug] Running TaskDef(zio.autowire.AutoWireSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@53f088d4, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZPoolSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@4b39e3c4, false, [SuiteSelector])
[debug] Running TaskDef(zio.ChunkBufferSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@75588692, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TMapSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@140be219, false, [SuiteSelector])
[debug] Running TaskDef(zio.metrics.PollingMetricSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@77a009b2, false, [SuiteSelector])
[debug] Running TaskDef(REPLSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@116e2752, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.THubSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@15e24b7c, false, [SuiteSelector])
[debug] Running TaskDef(zio.FiberSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@74048a21, false, [SuiteSelector])
[debug] Running TaskDef(zio.BitChunkIntSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@7d105b43, false, [SuiteSelector])
[debug] Running TaskDef(zio.SupervisorSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@21bb42ac, false, [SuiteSelector])
[debug] Running TaskDef(zio.RuntimeFlagsSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2d35b96c, false, [SuiteSelector])
[debug] Running TaskDef(zio.ReloadableSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2ba9544d, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.STMLazinessSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@5bacdb11, false, [SuiteSelector])
[debug] Running TaskDef(zio.TaggedSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@405a185b, false, [SuiteSelector])
[debug] Running TaskDef(zio.StackTracesSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@734b21c1, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.WeakConcurrentBagSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@19aae60b, false, [SuiteSelector])
[debug] Running TaskDef(zio.TagCorrectnessSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@712a2821, false, [SuiteSelector])
[debug] Running TaskDef(zio.DurationSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@601717c8, false, [SuiteSelector])
[debug] Running TaskDef(zio.ChunkSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2dca3f3e, false, [SuiteSelector])
[debug] Running TaskDef(zio.TrivialSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@47431fe9, false, [SuiteSelector])
[debug] Running TaskDef(zio.CancelableFutureSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2d296092, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TPriorityQueueSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@4f6817c5, false, [SuiteSelector])
[debug] Running TaskDef(zio.RefSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@1178ee91, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TArraySpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@86d5e8c, false, [SuiteSelector])
[debug] Running TaskDef(zio.CanFailSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@5cf3602a, false, [SuiteSelector])
[debug] Running TaskDef(zio.RandomSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@3980e6f, false, [SuiteSelector])
[debug] Running TaskDef(zio.DifferSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2e060cde, false, [SuiteSelector])
[debug] Running TaskDef(zio.ClockSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@49c0c703, false, [SuiteSelector])
[debug] Running TaskDef(zio.MetricSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@67fd6b35, false, [SuiteSelector])
[debug] Running TaskDef(zio.BitChunkByteSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@734211ba, false, [SuiteSelector])
[debug] Running TaskDef(zio.HigherKindedTagCorrectness, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@46e200f2, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.GrowableArraySpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@4f6e75ac, false, [SuiteSelector])
[debug] Running TaskDef(zio.ScheduleSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@44b19c01, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.HubSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@3a684999, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.StackSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@41c8bb54, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.metrics.ConcurrentSummarySpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@27725dac, false, [SuiteSelector])
[debug] Running TaskDef(zio.FiberRefSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@326a60f, false, [SuiteSelector])
[debug] Running TaskDef(zio.CachedSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@43bfe43c, false, [SuiteSelector])
[debug] Running TaskDef(zio.ConfigSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2987132b, false, [SuiteSelector])
[debug] Running TaskDef(zio.ScopeSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@48300955, false, [SuiteSelector])
[debug] Running TaskDef(zio.ConfigProviderSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@1e185fe, false, [SuiteSelector])
[debug] Running TaskDef(zio.ChunkPackedBooleanSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@3e581428, false, [SuiteSelector])
[debug] Running TaskDef(zio.ImportlessSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@7bd0c797, false, [SuiteSelector])
[debug] Running TaskDef(zio.LoggingSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@5720195f, false, [SuiteSelector])
[debug] Running TaskDef(zio.ExecutorSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@453f6052, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.MutableConcurrentQueueSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@4455a188, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZEnvironmentSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@4bdf00cb, false, [SuiteSelector])
[debug] Running TaskDef(zio.RefSynchronizedSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@7d9ea50, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZIOAppSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@73a7be45, false, [SuiteSelector])
[debug] Running TaskDef(zio.stm.TQueueSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@3fefe3a1, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZLayerSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2e22e5ef, false, [SuiteSelector])
[debug] Running TaskDef(zio.ZEnvironmentIssuesSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@60824d48, false, [SuiteSelector])
[debug] Running TaskDef(zio.BitChunkLongSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@1535e40c, false, [SuiteSelector])
[debug] Running TaskDef(zio.ThreadLocalBridgeSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@819eb3a, false, [SuiteSelector])
[debug] Running TaskDef(zio.internal.metrics.MetricListenerSpec, scala.scalanative.testinterface.common.Serializer$FingerprintSerializer$$anon$5@2c51fe5f, false, [SuiteSelector])
[info] No tests were executed
[error] Error during tests:
[error] 	zio.PromiseSpec
[error] 	zio.QueueSpec
[error] 	zio.stm.TRandomSpec
[error] 	zio.ConfigProviderEnvSpec
[error] 	zio.stm.ZSTMSpec
[error] 	zio.stm.TSetSpec
[error] 	zio.ZStateSpec
[error] 	zio.ZIOLazinessSpec
[error] 	zio.ScopedRefSpec
[error] 	zio.FiberRefsSpec
[error] 	zio.ChunkBuilderSpec
[error] 	zio.ZIOSpec
[error] 	zio.ZKeyedPoolSpec
[error] 	zio.HubSpec
[error] 	zio.UnsafeSpec
[error] 	zio.internal.FastListSpec
[error] 	zio.ChunkAsStringSpec
[error] 	zio.CauseSpec
[error] 	zio.NonEmptyChunkSpec
[error] 	zio.ChunkSpecVersionSpecific
[error] 	zio.autowire.InjectParameterizedServicesSpec
[error] 	zio.stm.TReentrantLockSpec
[error] 	zio.stm.TSemaphoreSpec
[error] 	zio.autowire.AutoWireSpec
[error] 	zio.ZPoolSpec
[error] 	zio.ChunkBufferSpec
[error] 	zio.stm.TMapSpec
[error] 	zio.metrics.PollingMetricSpec
[error] 	REPLSpec
[error] 	zio.stm.THubSpec
[error] 	zio.FiberSpec
[error] 	zio.BitChunkIntSpec
[error] 	zio.SupervisorSpec
[error] 	zio.RuntimeFlagsSpec
[error] 	zio.ReloadableSpec
[error] 	zio.stm.STMLazinessSpec
[error] 	zio.TaggedSpec
[error] 	zio.StackTracesSpec
[error] 	zio.internal.WeakConcurrentBagSpec
[error] 	zio.TagCorrectnessSpec
[error] 	zio.DurationSpec
[error] 	zio.ChunkSpec
[error] 	zio.TrivialSpec
[error] 	zio.CancelableFutureSpec
[error] 	zio.stm.TPriorityQueueSpec
[error] 	zio.RefSpec
[error] 	zio.stm.TArraySpec
[error] 	zio.CanFailSpec
[error] 	zio.RandomSpec
[error] 	zio.DifferSpec
[error] 	zio.ClockSpec
[error] 	zio.MetricSpec
[error] 	zio.BitChunkByteSpec
[error] 	zio.HigherKindedTagCorrectness
[error] 	zio.internal.GrowableArraySpec
[error] 	zio.ScheduleSpec
[error] 	zio.internal.HubSpec
[error] 	zio.internal.StackSpec
[error] 	zio.internal.metrics.ConcurrentSummarySpec
[error] 	zio.FiberRefSpec
[error] 	zio.CachedSpec
[error] 	zio.ConfigSpec
[error] 	zio.ScopeSpec
[error] 	zio.ConfigProviderSpec
[error] 	zio.ChunkPackedBooleanSpec
[error] 	zio.ImportlessSpec
[error] 	zio.LoggingSpec
[error] 	zio.ExecutorSpec
[error] 	zio.internal.MutableConcurrentQueueSpec
[error] 	zio.ZEnvironmentSpec
[error] 	zio.RefSynchronizedSpec
[error] 	zio.ZIOAppSpec
[error] 	zio.stm.TQueueSpec
[error] 	zio.ZLayerSpec
[error] 	zio.ZEnvironmentIssuesSpec
[error] 	zio.BitChunkLongSpec
[error] 	zio.ThreadLocalBridgeSpec
[error] 	zio.internal.metrics.MetricListenerSpec
[error] (coreTestsNative / Test / test) sbt.TestsFailedException: Tests unsuccessful
[IJ]
```

**Comment by adamgfraser** [comment]
Here's what I get:

```
[error] Found 1 missing definitions while linking
[error] Not found Member(Top(zio.ZLayer$),D7succeedL16java.lang.ObjectL17izumi.reflect.TagL10zio.ZLayerEO)
[error]         at /Users/adamfraser/zio/test/shared/src/main/scala/zio/test/DefaultMutableRunnableSpec.scala:37
```

**Comment by adamgfraser** [comment]
After cleaning it completes but there is no output:

```
[info] Starting process '/Users/adamfraser/zio/core-tests/native/target/scala-2.13/core-tests-test-out' on port '55464'.
[success] Total time: 4 s, completed Mar 7, 2023, 3:57:29 PM
```

**Comment by alterationx10** [comment]
I hope I don't cloud the issue, but I was taking a brief look at this, and if I bump the scala-native version to `0.4.9` (matches the current version in zio) I get (a seemingly fail-fast):

```
[info] No tests were executed
[error] Error during tests:
[error]         zio.ZIOSpec
[error] (coreTestsNative / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 32 s, completed Mar 8, 2023, 3:02:21 PM
```

and checking the corresponding `target/test-reports` there is a

```
<error message="java.util.concurrent.TimeoutException: Future timed out after [Duration.Inf]" type="scala.scalanative.testinterface.common.RPCCore$RPCException">scala.scalanative.testinterface.common.RPCCore$RPCException: java.util.concurrent.TimeoutException: Future timed out after [Duration.Inf]
	at scala.scalanative.testinterface.common.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:66)
	at scala.Option.foreach(Option.scala:407)
	at scala.scalanative.testinterface.common.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:64)
	at scala.scalanative.testinterface.common.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:43)
	at scala.scalanative.testinterface.common.Serializer$.withInputStream(Serializer.scala:52)
	at scala.scalanative.testinterface.common.RPCCore.handleMessage(RPCCore.scala:43)
	at scala.scalanative.testinterface.NativeRunnerRPC.$anonfun$runner$1(NativeRunnerRPC.scala:31)
	at scala.scalanative.testinterface.NativeRunnerRPC.$anonfun$runner$1$adapted(NativeRunnerRPC.scala:31)
	at scala.scalanative.testinterface.ComRunner$$anon$1.run(ComRunner.scala:61)
Caused by: java.util.concurrent.TimeoutException: Future timed out after [Duration.Inf]
	at java.lang.StackTrace$.currentStackTrace(Unknown Source)
	at java.lang.Throwable.fillInStackTrace(Unknown Source)
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Unknown Source)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Unknown Source)
	at zio.CancelableFuture.result(Unknown Source)
	at scala.concurrent.Await$.$anonfun$result$1(Unknown Source)
	at scala.concurrent.Await$$$Lambda$2.apply(Unknown Source)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(Unknown Source)
	at scala.concurrent.package$.blocking(Unknown Source)
	at scala.concurrent.Await$.result(Unknown Source)
	at zio.test.sbt.BaseTestTask.execute(Unknown Source)
	at scala.scalanative.testinterface.TestAdapterBridge.$anonfun$executeFun$1(Unknown Source)
	at scala.scalanative.testinterface.TestAdapterBridge$$Lambda$4.apply(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC.$anonfun$attach$3(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$8.apply(Unknown Source)
	at scala.util.Try$.apply(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC.$anonfun$attach$2(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$2.apply(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC.$anonfun$attachMux$3(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$10.apply(Unknown Source)
	at scala.Option.fold(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC.$anonfun$attachMux$1(Unknown Source)
	at scala.scalanative.testinterface.common.RunMuxRPC$$Lambda$11.apply(Unknown Source)
	at scala.concurrent.impl.Promise$Transformation.run(Unknown Source)
	at scala.scalanative.runtime.ExecutionContext$.loop(Unknown Source)
	at scala.scalanative.runtime.package$.loop(Unknown Source)
	at scala.scalanative.testinterface.NativeRPC.loop(Unknown Source)
	at scala.scalanative.testinterface.TestMain$.main(Unknown Source)
	at scala.scalanative.testinterface.TestMain.main(Unknown Source)
	at &lt;none&gt;.main(Unknown Source)
</error>
```

In `BaseTestTask.scala` there is the `Await.result(res, Duration.Inf)` in the `execute` method. Could it be this blocking that is causing issues with Scala Native?

**Comment by adamgfraser** [comment]
@alterationx10 I don't think you are clouding the issue at all as there was not a lot of clarity on the issue and if anything you are shedding a light on it. 😃

I think the platform specific `execute` in `ZTestTask` should be being called but maybe something is not working there.

**Comment by alterationx10** [comment]
@adamgfraser I think you are correct.

Concerning `ZTestTask`:

`ZTestRunnerJS.scala` has an `execute` method that *is* run, but it does not override the `execute` from `BaseTestTask`.

`ZTestRunnerNative.scala` has a similar `execute` method implementation as defined in the JS version, but it does not seem to be called!

I added a quick/similar override to the native implementation:

```
  override def execute(eventHandler: EventHandler, loggers: Array[Logger]): Array[Task] = {
    implicit val trace = Trace.empty

    val zTestHandler = new ZTestEventHandlerSbt(eventHandler, taskDef())
    val effect = run(zTestHandler)
    val fiber = Runtime.default.unsafe.fork(effect)(trace, Unsafe.unsafe)
    val result = fiber.unsafe.addObserver { exit =>
      exit match {
        case Exit.Failure(cause) => Console.err.println(s"$cause")
        case _ =>  Console.println(s":-)")
      }
    }(Unsafe.unsafe)
    Array()
  }
```

and it prints this error:

```
[info] Starting process '/Users/alt/Projects/sideeffffect/zio/core-tests/native/target/scala-2.13/core-tests-test-out' on port '65244'.
Die(java.lang.Error: Defect in zio.ZEnvironment: Could not find ExecutionEventSink inside ZEnvironment(ZIOAppArgs -> ZIOAppArgs(Chunk()), Annotations -> zio.test.Annotations$$anon$1@35a883, Live -> zio.test.Live$$anon$1@2d00f3, Sized -> zio.test.Sized$$anon$1@33f6a3, TestClock -> Test(Ref(Data(1970-01-01T00:00:00Z,List(),UTC)),zio.test.Live$$anon$1@2d00f3,zio.test.Annotations$$anon$1@35a883,zio.Ref$Synchronized$$anon$1@3998e3,zio.Ref$Synchronized$$anon$1@39a3a3), (TestConfig & {def repeats(): Int, def retries(): Int, def samples(): Int, def shrinks(): Int}) -> zio.test.TestConfig$$anon$1@30acc3, TestConsole -> Test(Ref(Data(List(),Vector(),Vector())),zio.test.Live$$anon$1@2d00f3,zio.FiberRef$unsafe$$anon$2@2e9693), TestRandom -> Test(Ref(Data(1071905196,1911589680,Queue())),Ref(Buffer(List(),List(),List(),List(),List(),List(),List(),List(),List()))), TestSystem -> Test(Ref(Data(Map(),Map(),
))), Scope -> zio.Scope$$anon$2@24a3d3),Stack trace for thread "zio-fiber-":
)
[info] No tests were executed
```

**Comment by alterationx10** [comment]
🤯 

image

**Comment by alterationx10** [comment]
@adamgfraser @sideeffffect 

So, I essentially copy/pasted the JS implementation into an override of execute in the native implementation, and they run now.

In the `ZTestTask` of `ZTestRunnerNative.scala`:

```
  override def execute(eventHandler: EventHandler, loggers: Array[Logger]): Array[Task] = {
    val fiber = Runtime.default.unsafe.fork {
      val logic =
        ZIO.consoleWith { console =>
          (for {
            summary <- spec
              .runSpecAsApp(FilteredSpec(spec.spec, args), args, console)
            _ <- sendSummary.provide(ZLayer.succeed(summary))
            // TODO Confirm if/how these events needs to be handled in #6481
            //    Check XML behavior
            _ <- ZIO.when(summary.status == Summary.Failure) {
              ZIO.attempt(
                eventHandler.handle(
                  ZTestEvent(
                    fullyQualifiedName0 = taskDef.fullyQualifiedName(),
                    // taskDef.selectors() is "one to many" so we can expect nonEmpty here
                    selector0 = taskDef.selectors().head,
                    status0 = Status.Failure,
                    maybeThrowable = None,
                    duration0 = 0L,
                    fingerprint0 = ZioSpecFingerprint
                  )
                )
              )
            }
          } yield ())
            .provideLayer(
              sharedFilledTestLayer +!+ (Scope.default >>> spec.bootstrap)
            )
        }
      logic
    }(Trace.empty, Unsafe.unsafe)
    fiber.unsafe.addObserver { exit =>
      exit match {
        case Exit.Failure(cause) => Console.err.println(s"$runnerType failed.")
        case _ =>
      }
      Array()
    }(Unsafe.unsafe)
    Array()
  }
```

**Comment by adamgfraser** [comment]
@alterationx10 Great! Do
You want to submit a pull request?

**Comment by alterationx10** [comment]
Sure! I can try to clean up a PR later tonight, if @sideeffffect doesn't beat me to it!

**Pull request closed without merging**
