### PR TITLE
Make Type Signature Of ZIO.forkAllDiscard More Specific

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by shawjef3** [comment]
I approve!

**Comment by shawjef3** [comment]
@adamgfraser  Oddly, this `forkAllDiscard` implementation seems slower than `forkAll`.

See https://github.com/shawjef3/ZioBenchmarks/blob/master/src/main/scala/benchmarks/ZioForkAllBenchmark.scala and https://github.com/shawjef3/ZioBenchmarks/blob/master/src/main/scala/benchmarks/ZioNewForkAllDiscardBenchmark.scala.

**Comment by shawjef3** [comment]
@adamgfraser I added `forkAll` and `forkAllDiscard` benchmarks to my ZIO repo.

rebased on [series/2.x](https://github.com/zio/zio/tree/series/2.x) https://github.com/shawjef3/zio/tree/forkall-benchmarks

rebased on [forkalldiscard](https://github.com/adamgfraser/zio/tree/forkalldiscard) https://github.com/shawjef3/zio/tree/forkall-benchmarks-new

Feel free to pull these into your branch.

The original `forkAllDiscard` is still faster.

original implementation
```
[info] Benchmark                    (count)   Mode  Cnt      Score      Error  Units
[info] ForkAllDiscardBenchmark.run        1  thrpt   20  55778.627 ± 8122.723  ops/s
[info] ForkAllDiscardBenchmark.run      128  thrpt   20    957.757 ±  232.126  ops/s
[info] ForkAllDiscardBenchmark.run     1024  thrpt   20    133.026 ±   13.752  ops/s
```
new implementation
```
[info] Benchmark                    (count)   Mode  Cnt      Score      Error  Units
[info] ForkAllDiscardBenchmark.run        1  thrpt   20  30928.358 ± 1589.038  ops/s
[info] ForkAllDiscardBenchmark.run      128  thrpt   20    371.711 ±   38.834  ops/s
[info] ForkAllDiscardBenchmark.run     1024  thrpt   20     45.418 ±    2.981  ops/s
```

```
[info] Benchmark             (count)   Mode  Cnt      Score      Error  Units
[info] ForkAllBenchmark.run        1  thrpt   20  30182.184 ± 1537.810  ops/s
[info] ForkAllBenchmark.run      128  thrpt   20    414.265 ±   14.132  ops/s
[info] ForkAllBenchmark.run     1024  thrpt   20     44.438 ±    4.115  ops/s
```

**Comment by shawjef3** [comment]
Actually I just made a PR for the benchmarks. That's easier. https://github.com/zio/zio/pull/7353

**Comment by adamgfraser** [comment]
@shawjef3 You are not benchmarking the same thing. In your first benchmark you just fork all the tasks. In your second benchmark you fork all the tasks, then wait for them to actually be executed, then join them all.

This change is not about performance but correctness. The original implementation will always be "faster" if you are just forking fibers because you just fork the fibers and don't do anything else, whereas any implementation that returns a fiber will have to collect the original fibers and convert them into a synthetic fiber.

**Comment by shawjef3** [comment]
@adamgfraser I guess I just figured that `forkAllDiscard` would have some significant performance benefit over `forkAll`. It doesn't generate a collection so that's a benefit. It just doesn't show up in JMH. I'm happy with it.

**Comment by adamgfraser** [comment]
@shawjef3 I think the original version possibly would have because you didn't actually have to build the collection but to return the composite fiber we do need to build the collection, we just use it to build a synthetic fiber with slightly more optimized variants of some operators. So I'm not surprised that it isn't significantly faster than `forkAll`.

The alternative would be to return to the original signature and update the documentation. That wouldn't give you a fiber, but that was the signature in ZIO 1.

**Comment by shawjef3** [comment]
@adamgfraser maybe having both implementations would be beneficial?

**Comment by adamgfraser** [comment]
@shawjef3 I think that is way too much complexity for what is already a very minor optimization.

**Comment by shawjef3** [comment]
I see. I guess I don't have a strong opinion either way. This new implementation is good, or updating the scaladoc to match the original signature is fine too.

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
