### PR TITLE
Add ZManaged.fromAutoCloseable

### LINKED ISSUE #960: Add ZManaged.fromAutoCloseable

### PR DESCRIPTION
**Pull request by iravid**
I swear we had this at some point.

Resolves #960

### CODE REVIEW

**Comment by iravid** [comment]
Ah, we have `bracketAuto` in interop-shared. Does anyone know why is that there and not in core?

**Comment by regiskuckaertz** [comment]
@iravid From [the man himself](https://github.com/zio/zio/issues/166#issuecomment-412058772), it is interop with the Java library.

**Comment by iravid** [comment]
Hmm but this interface requires no extra dependencies and exists on scalajs too - so it is portable.

**Comment by regiskuckaertz** [comment]
Oh, then I say let's move it into core ✌️

**Comment by jdegoes** [comment]
I'm good moving into core. 👍 

We did that for all the Scala Future stuff as well.

**Comment by iravid** [comment]
Sounds good. Moved them over.

**Pull request merged**
