### PR TITLE
Update Scalafmt and Scalafix rules

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
Can you please restart those flaky builds? :pray:

**Review by softinio — DISMISSED** [review]

**Comment by sideeffffect** [comment]
I'm afraid there are some flaky dead builds. Could somebody restart them?

**Comment by adamgfraser** [comment]
Yep, will do.

**Comment by sideeffffect** [comment]
We're getting there! 2 more to go :pray:

**Comment by sideeffffect** [comment]
last failed build standing :laughing:

**Comment by sideeffffect** [comment]
@adamgfraser we're green :tada: Thank you very much for your help here!
This is ready to be merged :muscle:

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
