### PR TITLE
Run ZIO Test Internal Test Suite in Dotty

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by adamgfraser** [comment]
@softinio Could you take a look at this when you get the chance? I edited the `config.yml` file to change `compile_dotty` to `test_dotty` since I want to run the ZIO Test internal test suite on Dotty now. Is there something we need to do on the backend to remove `compile_dotty` from the list of required checks and add `test_dotty`?

**Comment by adamgfraser** [comment]
It looks like we have an existing `test_dotty_jdk8_jvm` check that is commented out. Maybe we make that required and get rid of `compile_dotty`?

**Comment by ghostdogpr** [comment]
@adamgfraser to change required checks, you have to go to the Settings pages of this github repo, then Branches > Branch protection rules > `edit` master > Require status checks to pass before merging then you can check/uncheck the ones you want. Better to do it once this is merged.

**Comment by adamgfraser** [comment]
@ghostdogpr Can you approve one more time?

**Comment by softinio** [comment]
@adamgfraser Great work sir. Sorry I got to your comment late. Let me know if there is anything else I can help with.

**Pull request merged**
