### PR TITLE
ZStream#retry (with tests this time)

### PR DESCRIPTION
**Pull request by svroonland**
Implements #3785, followup of #3902

### CODE REVIEW

**Review by iravid — COMMENTED** [review]
Looks great. Not sure about the default parameter to schedule - what's your thinking on this?

**Comment by svroonland** [comment]
I figured that 'retry immediately' would make sense as a default semantic for stream retrial. Not particularly attached to it though.

**Comment by iravid** [comment]
Ok. I tend to agree but the need for consistency with ZIO#retry ranks higher. So i would suggest that we drop the default argument.

**Review by iravid — APPROVED** [review]
Thank you @svroonland!

**Pull request merged**
