### PR TITLE
fix `SinkUtils#sinkWithLeftover`

### LINKED ISSUE #2126: Test sink `sinkWithLeftover` is broken
Seems that it has been corrupted at some point.
Will fix it.

```
val s: stream.Stream[Nothing, Int] = zio.stream.Stream(1,2,3,4,5,6,7)
val sink = sinkWithLeftover(3, 1,-42).zip(ZSink.collectAll[Int])
val x = s.run(sink).flatMap(k => console.putStrLn(k.toString))
//Expected: (3,List(4, 5, 6, 7))
//Got: (3,List(4, 6, 7))
```

### PR DESCRIPTION
**Pull request by simpadjo**
Fixes #2126

### CODE REVIEW

**Comment by jdegoes** [comment]
@simpadjo Apologies for taking so long on this. Can you fix conflicts so we can see if the tests are now passing?

**Comment by simpadjo** [comment]
Rebased

**Comment by jdegoes** [comment]
Can you run `fmt` and `scalafix` to format the code?

**Comment by simpadjo** [comment]
`fmt` and `scalafix` had no effect but `fix` did the job

**Comment by simpadjo** [comment]
Rebased again. 
TBH it become too tiresome to maintain such a tiny PR. Tomorrow it is turning 3 months.
I'm learning more about zio api changes by rebasing it than by actually using zio :)
I know that we all do it in our free time and don't want to sound entitled.
Especially given that I'm not a frequent contributor.

**Comment by jdegoes** [comment]
Thank you so much for this contribution, and apologies again for the delay!

**Pull request merged**
