### PR TITLE
update comment for cause

### PR DESCRIPTION
**Pull request by phderome**
changing from "did not succeed" to "did succeed"

### CODE REVIEW

**Comment by phderome** [comment]
@adamgfraser I fail on CircleCI, what's wrong? It's just a comment edit.

**Comment by adamgfraser** [comment]
@phderome Unrelated CI flakiness. Rerunning now.

**Comment by phderome** [comment]
> @phderome Unrelated CI flakiness. Rerunning now.

still failing!

**Comment by ghostdogpr** [comment]
I wonder if it’s https://github.com/zio/zio/issues/3851 causing test failures.

**Comment by adamgfraser** [comment]
Yes I was thinking the same thing.

**Pull request merged**
