### PR TITLE
Update dotty

### PR DESCRIPTION
**Pull request by lukasz-golebiewski**
https://github.com/zio/zio/issues/1021

### CODE REVIEW

**Comment by jdegoes** [comment]
@LukasGasior1 Thank you for working on this! Did you make sure Dotty compiles all the code? (Dotty compilation is _not_ currently part of the Circle CI.)

**Comment by lukasz-golebiewski** [comment]
Yes, it works like a charm!
https://github.com/zio/zio/issues/1021#issuecomment-504681585

**Comment by softinio** [comment]
> Yes, it works like a charm!
> [#1021 (comment)](https://github.com/zio/zio/issues/1021#issuecomment-504681585)

Good to hear in that case once this PR is merged I will rebase into #1064 to add the circleci step back

Great work thanks for this PR

**Comment by softinio** [comment]
Are we ready to merge then?

**Comment by jdegoes** [comment]
@softinio Yes, whenever you're ready!

@LukasGasior1 Thanks for your work on this issue!

**Comment by softinio** [comment]
@lukasz-golebiewski @jdegoes Building dotty fails ... if it affects `master` will revert this and we can continue to work on it together with #1064 

Still waiting for `master` to run to see fate.

**Comment by softinio** [comment]
Failing build: https://circleci.com/gh/zio/zio/2977

**Comment by softinio** [comment]
Ok master not affected so no need to revert will fix issues under #1064

**Pull request merged**
