### PR TITLE
Remove INT signal handler for Windows (#7494)

### PR DESCRIPTION
**Pull request by rudolfduplessis**

### CODE REVIEW

**Comment by jdegoes** [comment]
What's the motivation for this?

**Comment by jdegoes** [comment]
Ah, i see the linked ticket. Perhaps we could limit the scope of this change to native images, somehow, since that's all it seems to affect?

**Comment by rudolfduplessis** [comment]
I'm at a loss to say whether it only affects native images and even more so of how to go about that way. All commenters to the ticket noted they were running on windows, and just like @zynque, I am running a basic scala app. Ran the same on linux and mac and there its fine. I don't necessarily know what I'm doing here - the effect on stuff around this change - just found that the signal hander "swallows" the INT signal before it gets to the shutdown hook "if os = windows". Still, glad to help with guidance.

**Comment by jdegoes** [comment]
Maybe we should investigate not swallowing the interrupt, and instead propagating it?

**Pull request closed without merging**
