### PR TITLE
Catch defects in effectAsyncM (could cause deadlocks)

### PR DESCRIPTION
**Pull request by neko-kai**
added test did not pass before the change

### CODE REVIEW

**Comment by neko-kai** [comment]
@iravid 
Actually no, this is completely wrong wrt Cats laws – the example should deadlock since the callback is not called; failures in `asyncF` action should be dropped/logged but should not be used in continuation.
Current implementation creates a race condition wrt what completes first – the callback or the failure.

Was there a discussion on deviating from cats-effect here or did it just happen?

**Comment by iravid** [comment]
Really. That sounds strange.

I'm mostly unfamiliar with the typeclass laws of  cats-effect, so can't comment intelligently on that.

**Comment by neko-kai** [comment]
Ok, sorry! The change was introduced here https://github.com/zio/zio/pull/823 - and discussion has moved to https://github.com/typelevel/cats-effect/pull/615 & https://github.com/typelevel/cats-effect/pull/612

**Comment by iravid** [comment]
Looks like I was asking the same questions there ;-)

**Pull request merged**
