### PR TITLE
revisit Zstream.mapZIOPar and Zstream.mapZIOParUnordered optimization

### PR DESCRIPTION
**Pull request by eyalfa**
revisited recent optimizations done in #8819 in face of the technique used to optimize `ZStream.flatMapPar` in #8863.

basic idea is to significantly reduce the number of forked fibers:
1.  employ a 'fibers pool' instead of forking a fiber per message.
2. two queues, one feeding the fibers pool another one for the results going downstream.
3.  avoid `race` operations, especially per message as each such operation forks two fibers.
4. rely on fiber's hierarchy to interrupt and close all child fibers.

# mapZioParUnordered
attempting to implement on top of `flatMapPar` resulted with marginal gain, moving to a specialized implementation won the gold 😎 which makes sense as it eliminates the nested streams `OutDone` messages which effectively halves the number of messages going through the queue.
The implementation places upstream messages in a queue, worker fibers drain the queue and apply the function on the dequeued elements, the result (success or failure) is then enqueued into the downstream queue. notice that failures are immediately forwarded to the downstream (unlike `mapZioPar`) so there's no need for a special purpose `failureSignal` promise like the previous implementation had.

# mapZioPar
similarly to `mapZioParUnordered` leverages two queues and a 'fibers pool', however here the downstream queue is a queue of promises. These promises are completed by the workers after evaluating the function on upstream elements.
unlike `mapZioParUnordered`, this method requires explicit means to signal errors to all fibers and specifically to the downstream channel. this is achieved by leveraging a ref to implement a mechanism taking after scala's promise implementation, the ref either holds an error (`Cause`) or a promise to be completed. subscribe and signal operations atomically updates the ref and completes the promise when required to.
* the signal/subscribe mechanism is used only to make sure the downstream channel sees the error (otherwise we risk an indefinite wait), the workers are interrupted by their parent fiber once the entire channel completes/fails.

# numbers!
## original benchmark results (including akka and fs2 for reference)
```
Benchmark                                   (chunkCount)  (chunkSize)  (parChunkSize)   Mode  Cnt   Score   Error  Units
StreamParBenchmark.akkaFlatMapPar                  10000         5000              50  thrpt   15   1.304 ± 0.003  ops/s
StreamParBenchmark.akkaMapPar                      10000         5000              50  thrpt   15   1.616 ± 0.102  ops/s
StreamParBenchmark.akkaMapParUnordered             10000         5000              50  thrpt   15   1.634 ± 0.072  ops/s
StreamParBenchmark.fs2FlatMapPar                   10000         5000              50  thrpt   15   0.115 ± 0.026  ops/s
StreamParBenchmark.fs2MapPar                       10000         5000              50  thrpt   15   0.304 ± 0.013  ops/s
StreamParBenchmark.fs2MapParUnordered              10000         5000              50  thrpt   15   0.251 ± 0.031  ops/s
StreamParBenchmark.zioFlatMapPar                   10000         5000              50  thrpt   15   0.865 ± 0.015  ops/s
StreamParBenchmark.zioFlatMapParChunks             10000         5000              50  thrpt   15  29.875 ± 1.310  ops/s
StreamParBenchmark.zioFlatMapParChunksFair         10000         5000              50  thrpt   15   2.519 ± 0.041  ops/s
StreamParBenchmark.zioMapPar                       10000         5000              50  thrpt   15   0.466 ± 0.003  ops/s
StreamParBenchmark.zioMapParUnordered              10000         5000              50  thrpt   15   0.771 ± 0.015  ops/s
```

## optimized results
```
Benchmark                              (chunkCount)  (chunkSize)  (parChunkSize)   Mode  Cnt  Score   Error  Units
StreamParBenchmark.zioMapPar                  10000         5000              50  thrpt   15  0.803 ± 0.017  ops/s
StreamParBenchmark.zioMapParUnordered         10000         5000              50  thrpt   15  1.973 ± 0.031  ops/s
```

notice the comparison to `akkaMapParUnordered` 😎

### CODE REVIEW

**Comment by eyalfa** [comment]
cc: @jdegoes

**Comment by eyalfa** [comment]
> cc: @jdegoes

@jdegoes  ☝️

**Comment by jdegoes** [comment]
Amazing you've been able to catch up to (and surpass, in one case) Akka. Brilliant work!

**Review by jdegoes — APPROVED** [review]

**Comment by varshith257** [comment]
@jdegoes Can please have a look at https://github.com/zio/zio-http/pull/2838


Sorry, if I have reached out you in wrong way! But I have been waiting for your review from a long back.

**Pull request merged**
