### PR TITLE
Adding an IntelliJ page to the docs (under Ecosystem)

### PR DESCRIPTION
**Pull request by hmemcpy**
It's a bit of a shameless promotion, but I'd really love if the plugin could be listed in the docs, showcasing some of its functionality (with images and gifs). The full docs of the plugin are being worked on (currently, to be placed on the Wiki page of the plugin repo).

### CODE REVIEW

**Comment by adamgfraser** [comment]
@hmemcpy Can you add update the nav so we can get this merged?

**Comment by hmemcpy** [comment]
Hey Adam, sorry for the late reply. I'm fine with including just the link to the repo and not have an advertisement page! But just to clarify, the link should be in the Ecosystem page? I don't think I should link it under "Official ZIO Libraries", as it's neither official nor a library :)
How about another section, "Tools powered by ZIO"? It could be a place to list other projects, such as https://github.com/ScalaConsultants/panopticon-tui?

**Comment by adamgfraser** [comment]
Sounds great!

**Comment by hmemcpy** [comment]
Done! Also removed one period for consistency :)

**Comment by adamgfraser** [comment]
Maybe "Tools with Direct ZIO Support"?

**Comment by hmemcpy** [comment]
I thought about it, but the one below it says "Libraries with...", so I didn't want to constrain it. I'm good with either title :)
Should I change it?

**Comment by adamgfraser** [comment]
"Tooling with Direct ZIO Support"? "Tools Powered by ZIO" just seemed a little broad because like Polynote or something could be considered a tool powered by ZIO. I think the idea is that these are tools that make it easier to develop software with ZIO. Good with whatever.

**Comment by ghostdogpr** [comment]
How about simply “Tools for ZIO”?

**Comment by adamgfraser** [comment]
Sounds great!

**Comment by hmemcpy** [comment]
Great! I changed the title, and moved it further down (after libraries)

**Pull request merged**
