### PR TITLE
Update things for Scala Native (still no running tests)

### PR DESCRIPTION
**Pull request by sideeffffect**
/cc @adamgfraser @mijicd @DamianReeves 

salvaged from https://github.com/zio/zio/pull/7031

(this can be merged as _Squash_ merge)

### CODE REVIEW

**Comment by sideeffffect** [comment]
@mijicd :pray:

**Review by mijicd — APPROVED** [review]

**Review by adamgfraser — APPROVED** [review]

**Comment by DamianReeves** [comment]
Awesome work @sideeffffect

**Comment by DamianReeves** [comment]
Is similar work required for the 2.x series?

**Comment by sideeffffect** [comment]
I will merge (or arrange a PR) `series/1.x` to `series/2.x`

**Comment by sideeffffect** [comment]
https://github.com/zio/zio/pull/7436

**Pull request merged**
