### PR TITLE
Further optimize ch exec read

### PR DESCRIPTION
**Pull request by eyalfa**
1. few more optimizations on top of #8761 

initial benchmark results:
```
Benchmark                                     (chunkCount)  (chunkSize)   Mode  Cnt    Score   Error  Units
StreamBenchmarks.zioChunkToConstBaseline             10000         5000  thrpt   15  148.078 ± 4.111  ops/s
StreamBenchmarks.zioChunkToConstDirect               10000         5000  thrpt   15  232.269 ± 2.481  ops/s
StreamBenchmarks.zioChunkToConstFromFunction         10000         5000  thrpt   15  133.889 ± 0.352  ops/s
```

after applying the optimizations:
```
[info] Benchmark                                     (chunkCount)  (chunkSize)   Mode  Cnt    Score   Error  Units
[info] StreamBenchmarks.zioChunkToConstBaseline             10000         5000  thrpt   15  244.041 ± 1.084  ops/s
[info] StreamBenchmarks.zioChunkToConstDirect               10000         5000  thrpt   15  366.264 ± 1.715  ops/s
[info] StreamBenchmarks.zioChunkToConstFromFunction         10000         5000  thrpt   15  245.392 ± 1.611  ops/s
```

optimization techniques applied:
1. `ChannelExecutor.readUpstream`
   a. make the internal read method tail recursive
   b. instead of suspending on each recurse, count consecutive operations and suspend every N steps (currently set to 128), this is important in order to keep the stream interruptible.
   c. reduce stack mutations by separating the current `Read` from the rest, for some reads this means they'd never make it into the stack, for others it avoids pushing the same read immediately after popping it from the stack.
2. `ChannelExecutor.execToPullingChannel`, implement `readUpstream` as a channel. this avoids going through effects for some code paths and eliminate the need for the `onSuccess` and `onFailure` effects.
3.  reorder cases in `ChannelExecutor.run`, make sure frequent channel constructors appear earlier in the pattern matching.

### CODE REVIEW

**Comment by eyalfa** [comment]
@ghostdogpr I'd appreciate your review on this

**Comment by ghostdogpr** [comment]
> @ghostdogpr I'd appreciate your review on this

I'm completely unfamiliar with ZStream internals. Not sure who is, maybe @jdegoes ?

**Comment by eyalfa** [comment]
@vigoo seems like you were on of the last to touch this area, can u please review?

**Comment by eyalfa** [comment]
@jdegoes , @vigoo , can u please review this?

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
