### PR TITLE
Use a `ConcurrentHashMap` as a cache in `ZEnvironment`

### PR DESCRIPTION
**Pull request by kyri-petrou**
@eyalfa pointed out that there is an (insanely small) chance that two threads try to update the cache at the same time, resulting in a resize of the hash tables, a runtime error will be thrown. To guard against the very small chance this happens, we use a ConcurrentHashMap which guards against the possibility of this happening

### CODE REVIEW

**Comment by kyri-petrou** [comment]
@eyalfa let me know if you're happy with this

**Review by ghostdogpr — APPROVED** [review]
Any impact on benchmarks?

**Comment by kyri-petrou** [comment]
There is but it's very small (< 5% for some of the cases). Performance is still better than the previous approach of using an immutable map

**Comment by eyalfa** [comment]
@kyri-petrou did u benchmark the 'reset cache on fork' approach?
do we have a baseline of not using a cache at all? environments are not supposed to be extremely large, right? so how important is the cache anyway? (I guess it is, but numbers are stronger than guesses 😎 )

**Comment by kyri-petrou** [comment]
> did u benchmark the 'reset cache on fork' approach

I haven't, but I really can't see how this is going to be performant. It would require:
1. Update of `FiberRefs` for each fork (which is expensive). This would also make joining the fork more expensive because now we can't rely on the shortcut method of checking whether the fiber ref was modified by a child
2. Allocation of a new ZEnvironment per fork

Plus we lose the caching

> so how important is the cache anyway

Very. It's highly dependent on the size of the ZEnvironment and other factors but without the cache the ZEnvironment becomes considerably slower.

Accessing a single service in a small environment (~10 entries) with/without caching, without caching it's ~17x slower

```
With caching:
[info] Benchmark                         Mode  Cnt          Score         Error  Units
[info] ZEnvironmentBenchmark.accessOne  thrpt    6  101652028.150 ± 1700714.288  ops/s

Without caching:
[info] Benchmark                         Mode  Cnt        Score       Error  Units
[info] ZEnvironmentBenchmark.accessOne  thrpt    6  5887623.098 ± 76329.180  ops/s
```

**Comment by kyri-petrou** [comment]
@eyalfa I'll merge this one in; if you have any comments or other reservations let me know

**Pull request merged**
