### PR TITLE
Added Hello World working example 

### PR DESCRIPTION
**Pull request by tampler**

### CODE REVIEW

**Comment by adamgfraser** [comment]
@tampler I think with recent changes to include the `ZEnv` in the default runtime again we don't need this anymore. What do you think?

**Comment by tampler** [comment]
Alright, I don't monitor all those changes in real time. If this is not actual, should I close it?

**Comment by adamgfraser** [comment]
I think so. See #3055. The behavior is going to be the same as in RC17.

**Comment by tampler** [comment]
not actual anymore

**Pull request closed without merging**
