### PR TITLE
Fix Tag support for generic type arguments

### LINKED ISSUE #8834: Finding implicit Tag fails sometimes for generic type argument
I couldn't find a pattern why these errors are happening.

ZIO: 2.0 and 2.1
Scala: 3.3 and 3.4

# Example1
https://scastie.scala-lang.org/YYk2KAU0T8e51QTozYJZeg

```scala
import zio.ZIOApp
import zio.*

trait SourceOfC

trait ABC[MyC: Tag] {

  def run: ZIO[Any, Any, Any] = {
    val t = (for {
      _ <- ZIO.service[MyC]
      _ <- ZIO.service[SourceOfC] // Comment 1
      p <- useMyC() // Comment 2
    } yield ())
    
    val o = t.provide(sourceOfCLayer, obtainC)

    o
  }

  val sourceOfCLayer: ZLayer[Any, Throwable, SourceOfC] = ???
  val obtainC: ZLayer[SourceOfC, Any, MyC] = ???
  def useMyC(): ZIO[MyC & SourceOfC, Nothing, Unit] = ???
}
```

Commenting either line 11 or 12 fixes the issue. Replacing `MyC` with empty trait also fixes it.

# Example 2
https://scastie.scala-lang.org/cuewZKmkT8mE0lOldDBcZw
```scala
import zio.ZIOApp
import zio.*

trait ABC[MyC: Tag] {

  def run2() = {
    (for {
      _ <- ZIO.service[MyC]
    } yield ()).provide(provideC, anotherLayer) // Removing anotherLayer fixes
  }

  val provideC: ZLayer[Any, Any, MyC] = ???
  val anotherLayer: ZLayer[Any, Any, Unit] = ???

}
```

Here the existence of `Unit` layer (like Logging ones) breaks stuff. Making `anotherLayer` return type non-Unit or extracting `MyC` to empty trait fixes.

At the beginning I thought it has to do with number of abstract arguments, but that's not the case: https://scastie.scala-lang.org/6h5rekHNSZKybKnOEMYO2A

Error for SEO: 
```
ABC.this.MyC is a type parameter without an implicit Tag!
  could not find implicit value for izumi.reflect.Tag[ABC.this.MyC]. Did you forget to put on a Tag, TagK or TagKK context bound on one of the parameters in ABC.this.MyC? e.g. def x[T: Tag, F[_]: TagK] = ...
```

### PR DESCRIPTION
**Pull request by andrzejressel**
Fixes #8834
/claim #8834

### CODE REVIEW

**Comment by andrzejressel** [comment]
I'm wondering if I should also add it to `ServiceTagVersionSpecific`

**Comment by andrzejressel** [comment]
There is some issue with JUnit test runner - I'm drafting it

**Comment by andrzejressel** [comment]
I was summoning the wrong tag ...

**Comment by andrzejressel** [comment]
Now when I'm thinking about it - I will add today evening tests for error messages that are shown. I want to show izumi's messages, not mine.

**Comment by andrzejressel** [comment]
All right - I think it's ready - I wanted to add tests where we set `A` bound to izumi's tag, but it does not work for Scala 2.13

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
