### PR TITLE
add Scalac logo to the Sponsors section

### PR DESCRIPTION
**Pull request by jczuchnowski**
Would be great if someone confirmed it's ok visually.

### CODE REVIEW

**Comment by jczuchnowski** [comment]
@jdegoes please take a look

**Comment by jdegoes** [comment]
@jczuchnowski Happy to, can you include a screen shot?

**Comment by LGLO** [comment]
I can help:
```
sbt docusaurusCreateSite
cd website
yarn start
```
Screenshot from 2019-10-05 22-43-33

**Comment by jdegoes** [comment]
@LGLO 🙏

**Comment by jczuchnowski** [comment]
Thanks @LGLO

**Comment by neko-kai** [comment]
@jczuchnowski @jdegoes 
I guess this needs an addition to README.md section as well. I'm not opening a PR because @jczuchnowski should probably come up with the headline :)

**Pull request merged**
