### PR TITLE
Add Documentation To Contributors Guide Regarding Unsafe

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Review by jdegoes — DISMISSED** [review]

**Review by khajavi — DISMISSED** [review]

**Review by khajavi — DISMISSED** [review]

**Comment by adamgfraser** [comment]
@khajavi You want to submit your changes as a separate PR so we can make this one smaller?

**Comment by khajavi** [comment]
@adamgfraser 
What changes do you mean? I haven't any commit for this PR.

**Comment by adamgfraser** [comment]
@khajavi There are a bunch of changes from the branch from @atooni that was merged into this. I thought those originally came from you but maybe I am misremembering.

**Comment by atooni** [comment]
I think I have just fixed the build on this one, nothing content-wise

**Pull request closed without merging**
