### PR TITLE
fix(ZLayer): collectAll must have a test

### LINKED ISSUE #7784: ZLayer.collectAll is memoized but reexecutes and concatenates to earlier results
`ZLayer.collectAll` reexecutes each time it is uses, and on top of that it concatenates the new result to the memoized result. This keeps on building on each re-use.

https://scastie-dev.scala-lang.org/qxUWXtkPT1yXuIzFfvLRmw

### PR DESCRIPTION
**Pull request by ThijsBroersen**
This should fix #7784

### CODE REVIEW

**Review by adamgfraser — COMMENTED** [review]
The implementation of `collectAll` is correct as is. The issue is the implementation of `suspend`, which is fixed in #7786.

**Comment by ThijsBroersen** [comment]
> The implementation of `collectAll` is correct as is. The issue is the implementation of `suspend`, which is fixed in #7786.

Sweet, thanks!

**Comment by adamgfraser** [comment]
Going to close this but thanks for raising the issue!

**Comment by ThijsBroersen** [comment]
Shouldn't collectAll also have a test?

**Comment by adamgfraser** [comment]
I think this particular issue about suspending side effects is something that needs to be handled by `ZLayer.suspend` and tested there versus separately in every layer operator.

**Pull request closed without merging**
