### PR TITLE
Make `Gen.fromIterable` more lazy

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Review by adamgfraser — COMMENTED** [review]
We generally haven't made `Gen` constructors lazy so would prefer not to make one off changes like this.

**Comment by guizmaii** [comment]
@adamgfraser Do you want me to make them all lazy? I think it's what people expect (at least it's what I was expecting) as ZIO constructors are lazy

**Comment by adamgfraser** [comment]
@guizmaii What did you do where this was an issue?

**Comment by guizmaii** [comment]
@adamgfraser My iterable is loaded from some data from disk, so per say, there's no issue. 
It's just that, because `Gen.fromIterable` isn't lazy, the list is loaded when the `Gen` instance is declared and not when it's used:
```scala
lazy val loadFromDisk = ...
val myGen = Gen.fromIterable(loadFromDisk)
```
Not a big issue but it's not the behaviour I'm expecting seeing all the other ZIO constructors
To keep the laziness, I'd have to make the `val` a `lazy val`, which can be seen as weird in ZIO codebases

**Comment by adamgfraser** [comment]
@guizmaii You can just do `Gen.fromZIO(???).flatMap(Gen.fromIterable)`.

**Comment by guizmaii** [comment]
There's no ZIO involved in the loading of the data. It's testing code, doesn't need to be pure. I could tho

**Comment by adamgfraser** [comment]
Loading the data is an effect. It involves the acquisition and release of a resource.

**Comment by adamgfraser** [comment]
Going to close but will take a look at this more comprehensively.

**Review by adamgfraser — APPROVED** [review]
Thinking about this more I don't think it makes sense for all generators to accept their parameters lazily for performance reasons but in this case the underlying implementation is already lazy so its fine.

**Comment by adamgfraser** [comment]
Actually this change is not binary compatible or even source compatible so I don't think it makes sense. You can use `Gen.fromZIO` or `Gen.suspend` to avoid having to define a `lazy val`.

**Pull request closed without merging**
