### PR TITLE
fix: removed diff rendering from the assertion 

### LINKED ISSUE #8664: zio-test: classic assertion `equalTo` using `Diff`
At the moment the equalTo of smart assertions [uses](https://github.com/zio/zio/blob/ffa64250e82c41df4d15eda9851ada46285d1527/test/shared/src/main/scala/zio/test/internal/SmartAssertions.scala#L280) the `Diff` mechanism, however the classic assertion does [not](https://github.com/zio/zio/blob/ffa64250e82c41df4d15eda9851ada46285d1527/test/shared/src/main/scala-2.13/zio/test/AssertionVariants.scala#L68)

Also, the rendering of the `Diff` seems to happen in the assertion, is that something we would like ?

### PR DESCRIPTION
**Pull request by varshith257**
- Fixes #8664
- /claim #8664

**Changes Made:**

1. Updated the rendering logic to occur outside the assertion function, enabling a more modular architecture for code reuse and alternate renderings.

### CODE REVIEW

**Comment by varshith257** [comment]
@jdegoes This is ready for review. PTAL

**Comment by varshith257** [comment]
@jdegoes Can I get reviewed this PR?

**Comment by varshith257** [comment]
@jdegoes I think it's ready for your final review

**Comment by jdegoes** [comment]
@varshith257 This does not really fix the problem. It reorganizes the diff rendering code, but does not unify it between smart assertions and ordinary assertions.

**Comment by varshith257** [comment]
> @varshith257 This does not really fix the problem. It reorganizes the diff rendering code, but does not unify it between smart assertions and ordinary assertions.

Do I need to include diff mechanism for ordinary assertions too?

**Comment by varshith257** [comment]
> > @varshith257 This does not really fix the problem. It reorganizes the diff rendering code, but does not unify it between smart assertions and ordinary assertions.
> 
@jdegoes Do I need to include diff mechanism for ordinary assertions too  to make use of this reusable of rendering function?

**Comment by varshith257** [comment]
@coderabbitai fix this too: 
```
compiling 109 Scala sources to /home/runner/work/zio/zio/test/jvm/target/scala-2.13/classes ...
[error] /home/runner/work/zio/zio/test/shared/src/main/scala-2.13/zio/test/AssertionVariants.scala:91:1: expected class or object definition
[error] def equalTo[A, B](expected: A)(implicit eql: Eql[A, B]): Assertion[B] =
[error] ^
[error] one error found
```

**Comment by varshith257** [comment]
@coderabbitai fix this errors:
```

error] /home/runner/work/zio/zio/test/shared/src/main/scala-2.13/zio/test/AssertionVariants.scala:81:32: not found: value Diff
[error]               val diffResult = Diff.diff(expected, actual) 
[error]                                ^
[error] /home/runner/work/zio/zio/test/shared/src/main/scala-2.13/zio/test/AssertionVariants.scala:82:15: not found: value AssertionUtils
[error]               AssertionUtils.renderDiffResult(diffResult, expected, actual)
[error]               ^
[error] two errors found
[error] (testsJVM / Compile / compileIncremental) Compilation failed
```

**Comment by varshith257** [comment]
> @coderabbitai fix this errors:
> 
> ```
> 
> error] /home/runner/work/zio/zio/test/shared/src/main/scala-2.13/zio/test/AssertionVariants.scala:81:32: not found: value Diff
> [error]               val diffResult = Diff.diff(expected, actual) 
> [error]                                ^
> [error] /home/runner/work/zio/zio/test/shared/src/main/scala-2.13/zio/test/AssertionVariants.scala:82:15: not found: value AssertionUtils
> [error]               AssertionUtils.renderDiffResult(diffResult, expected, actual)
> [error]               ^
> [error] two errors found
> [error] (testsJVM / Compile / compileIncremental) Compilation failed
> ```

@coderabbitai

**Comment by varshith257** [comment]
@ghostdogpr This PR aims to unify rendering logic to SmartAssertions and ordinary assertions to ensure code reusability. But when the `renderdiff `  is applied to ordinary assertions equalTo function, CI fails with type errors.
Any guidance here?

**Comment by varshith257** [comment]
> @ghostdogpr This PR aims to unify rendering logic to SmartAssertions and ordinary assertions to ensure code reusability. But when the `renderdiff ` is applied to ordinary assertions equalTo function, CI fails with type errors. Any guidance here?

cc : @kyri-petrou

**Comment by varshith257** [comment]
> @ghostdogpr This PR aims to unify rendering logic to SmartAssertions and ordinary assertions to ensure code reusability. But when the `renderdiff ` is applied to ordinary assertions equalTo function, CI fails with type errors. Any guidance here?

cc/ @ghostdogpr

**Review by ghostdogpr — COMMENTED** [review]
It doesn't compile because Diff[A] can only compare 2 values of type A but here we are comparing A and B which are different types. The existing code is using diffProduct which infers the objects to be Any so it can compare anything.

**Comment by varshith257** [comment]
> It doesn't compile because Diff[A] can only compare 2 values of type A but here we are comparing A and B which are different types. The existing code is using diffProduct which infers the objects to be Any so it can compare anything. 

It mean can't we unify this diff rendering to both ordinary and smart assertions?

Or
 
Any typecast is required?

**Comment by ghostdogpr** [comment]
Maybe we can change `equalTo` to return an `Assertion[A]`, that way you can use `Diff[A]`. I wonder if there are cases where type inference won't work when B is a subtype of A but maybe it's okay to explicitly use type parameters in that case.

**Comment by varshith257** [comment]
> Maybe we can change `equalTo` to return an `Assertion[A]`, that way you can use `Diff[A]`. I wonder if there are cases where type inference won't work when B is a subtype of A but maybe it's okay to explicitly use type parameters in that case.

@ghostdogpr This approach making large no of tests flaky to fail. After my trial and error with this equalTo functions of both SmartAssertions and ordinary, I suscept we can't unify the rendering of diff function.

Waiting for your final review

**Comment by ghostdogpr** [comment]
I believe the compile errors are because you changed `OptionalImplicit[Diff[A]]` to `Diff[A]`. I don't think this should be changed.

**Comment by varshith257** [comment]
@ghostdogpr  The changes made to ordinary assertion to unify the same renderdiff of smartAssertions led to fail large chunks of test.

**Comment by varshith257** [comment]
@jdegoes @ghostdogpr  It's making it hard to use the same render diff logic to both smartAssertions and ordinaryAssertions as they behave differently with their input args. You'll be able to verify through my commits. I have been experimenting with it for a while and it's nearly 60 commits.

Waiting for your guidance to solve/alter approaches

**Comment by varshith257** [comment]
The failing test is of ordinary Assertions changed behavior emitting test fails except lint workflow

**Comment by varshith257** [comment]
@ghostdogpr PTAL

**Comment by ghostdogpr** [comment]
I don't have anything better to suggest at the moment 😄

**Comment by varshith257** [comment]
> @varshith257 This does not really fix the problem. It reorganizes the diff rendering code, but does not unify it between smart assertions and ordinary assertions.

> I don't have anything better to suggest at the moment 😄

@jdegoes It's for your review now

**Comment by varshith257** [comment]
@jdegoes PTAL

**Comment by jdegoes** [comment]
@varshith257 Can you please fix the build? There are linting issues and compilation errors under 3.x. Feel free to re-open when fixed. Thank you!

**Pull request closed without merging**
