### PR TITLE
Update Magnolia

### PR DESCRIPTION
**Pull request by nightscape**
There is a bug in Magnolia versions < 0.15 which causes derivation for case classes with default values to fail:
https://github.com/propensive/magnolia/issues/227
The update should fix it.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Magnolia is only available for Scala.js 1.0+, so you will need this merged first: https://github.com/zio/zio/pull/2479

**Comment by adamgfraser** [comment]
@nightscape Thanks! I wonder why this wasn't getting picked up by Scala Steward?

**Comment by ghostdogpr** [comment]
@adamgfraser for the reason above 😄 Scala Steward is smart!

**Comment by adamgfraser** [comment]
@ghostdogpr Ah good point. Well fortunately it looks like we aren't far away on that one.

**Comment by adamgfraser** [comment]
@ghostdogpr Indeed!

**Pull request merged**
