### PR TITLE
Scala Native 0.5.x

### LINKED ISSUE #8786: Publish for Scala native 0.5
Are there plans to publish it there?

### PR DESCRIPTION
**Pull request by sideeffffect**
closes https://github.com/zio/zio/issues/8786

blocked on
 * https://github.com/scala-native/scala-native-loop/pull/47
 * https://github.com/lolgab/scala-native-crypto/pull/15
 * https://github.com/cquiroz/scala-java-time/pull/508

### CODE REVIEW

**Comment by jdegoes** [comment]
@sideeffffect Would love to get this in, but it's failing two builds. Can you re-open when fixed? 🙏

**Comment by jivanic-demystdata** [comment]
@sideeffffect Could you re-open this PR, please? It would be interesting to merge this ASAP

**Comment by kyri-petrou** [comment]
@jivanic-demystdata I think we need to wait for https://github.com/scala-native/scala-native-loop/pull/47 first

**Comment by kyri-petrou** [comment]
Having said that, there haven't been any commits to the library in 2 years, so I'm not sure whether we should start looking into alternatives

**Comment by guizmaii** [comment]
@kyri-petrou Yup! Just asked on Twitter if people could have a look. See: https://x.com/guizmaii/status/1801197843727946219

**Comment by guizmaii** [comment]
> so I'm not sure whether we should start looking into alternatives

Do we know what it's used for? Can we get rid of it maybe? 🤔
An ugly solution could be to copy paste the code of this lib in ZIO codebase 🤔

**Comment by lolgab** [comment]
I published the library yesterday. You can bump to `0.3.0` to get the version released for Scala Native `0.5`.
This library was first introduced to have concurrency on a single threaded and is based on libuv. After that Cats Effect started using `kqueue` and `epoll` directly which don't require any library and fs2 implemented the support for sockets based on the same `epoll` and `kqueue` primitives.
Scala Native 0.5 supports multithreading which introduces new problems for libuv (which needs to be called from the same thread).

**Comment by sideeffffect** [comment]
@jdegoes or @ghostdogpr or anybody who can, please re-open this PR. All the dependencies are now available. We can move ZIO to Scala Native 0.5.x :tada:

**Comment by kyri-petrou** [comment]
@sideeffffect seems that `scalafix` needs to be updated to `1.18.0` and `scalafix-testkit` to `1.12.1`

**Comment by DamianReeves** [comment]
Any idea when this will be available?

**Comment by sideeffffect** [comment]
Unfortunately there are problems in the tests. The process running the tests fails in an unexpected manner
```
[error] Test runner interrupted by fatal signal 11
[warn] Force close java.lang.RuntimeException: Process /home/runner/work/zio/zio/core-tests/native/target/scala-2.13/core-tests-test finished with non-zero value 139 (0x8b)
[error] Error: Total 81, Failed 0, Errors 81, Passed 0
```
I don't really know what to do about it. Perhaps @lolgab would?

**Comment by lolgab** [comment]
@sideeffffect Can you try `nativeConfig ~= {_.withMultithreading(false)}`?

**Comment by sideeffffect** [comment]
@lolgab that didn't seem to help :(

**Comment by DamianReeves** [comment]
Any idea what's up with the testPlatforms build for Native?

**Comment by kyri-petrou** [comment]
I'm leaving this here in case it helps someone with figuring out what on earth is going on. I isolate the issue when using `nativeConfig ~= {_.withMultithreading(false)}` to [this line](https://github.com/zio/zio/blob/e2cb5028e34201cdfcd58419461849f199beba26/core/native/src/main/scala/zio/ClockPlatformSpecific.scala#L38-L42).

I really don't know why that line is causing a `SIGSEGV` (code 11) error, but I created a fresh project and it works fine. It also fails even if you do something like this:

```scala
Timer.timeout(FiniteDuration(nanos, TimeUnit.NANOSECONDS)){ () => () }
```

**Comment by kyri-petrou** [comment]
@sideeffffect I managed to fix it via a small dirty trick. Do you mind if I push to your branch?

**Comment by sideeffffect** [comment]
@kyri-petrou not at all! Please go ahead. I'm very happy that this will get fixed :tada:

**Comment by kyri-petrou** [comment]
@sideeffffect "fixed" is a strong word. With the changes I just pushed, the test suite works (locally at least, hopefully CI agrees) only when with `nativeConfig ~= {_.withMultithreading(false)}`. I really can't figure out why it doesn't work with multi-threading enabled.

@lolgab do you happen to have any ideas on why that might be happening?

**Comment by sideeffffect** [comment]
All green :tada: Would be awesome to merge this, so that the rest of the libraries can be upgraded :pray:

**Review by kyri-petrou — APPROVED** [review]
I'm still fairly concerned that the tests are failing when multi-threading is enabled, but I think it's probably better not to hold up every single library that depends on ZIO until we figure it out.

We should definitely mention this in the release notes though

**Comment by sideeffffect** [comment]
@jdegoes @ghostdogpr :pray: 
we need you to merge this PR

**Comment by sideeffffect** [comment]
@kyri-petrou do you think we'll get a new release with SN 0.5 anytime soon?

**Comment by kyri-petrou** [comment]
@sideeffffect, I was about to create a release today, but after a discussion with @ghostdogpr and @regiskuckaertz, we'd like to get #9054 in as well since we're getting a lot of reports of edge cases in ZStream parallel processing since 2.1.3. So I'll release once that's merged in.

**Pull request merged**
