### PR TITLE
add size function in TArray and TMap

### PR DESCRIPTION
**Pull request by PyAntony**
Added `size` function for TArray and TMap. This is for ticket #3552

### CODE REVIEW

**Comment by PyAntony** [comment]
Is there something wrong with the format?

**Comment by adamgfraser** [comment]
Did you run `set prepare`?

**Comment by PyAntony** [comment]
> Did you run `sbt prepare`?

I didn't. I am running `build` now and I am getting some errors:

[error] stack trace is suppressed; run last testJS / Compile / compile for the full output
[error] stack trace is suppressed; run last coreJS / Compile / compile for the full output
[error] stack trace is suppressed; run last streamsJS / Compile / compile for the full output
[error] stack trace is suppressed; run last coreJVM / Compile / compile for the full output
[error] stack trace is suppressed; run last streamsJVM / Compile / compile for the full output
[error] stack trace is suppressed; run last streamsJS / Test / compile for the full output
[error] stack trace is suppressed; run last testJS / Test / compile for the full output
[error] stack trace is suppressed; run last coreJS / Test / compile for the full output
[error] stack trace is suppressed; run last streamsJVM / Test / compile for the full output
[error] stack trace is suppressed; run last coreJVM / Test / compile for the full output
[error] (testJS / Compile / compile) java.nio.channels.OverlappingFileLockException
[error] (coreJS / Compile / compile) java.nio.channels.OverlappingFileLockException
[error] (streamsJS / Compile / compile) java.nio.channels.OverlappingFileLockException
[error] (coreJVM / Compile / compile) java.nio.channels.OverlappingFileLockException
[error] (streamsJVM / Compile / compile) java.nio.channels.OverlappingFileLockException
[error] (streamsJS / Test / compile) java.nio.channels.OverlappingFileLockException
[error] (testJS / Test / compile) java.nio.channels.OverlappingFileLockException
[error] (coreJS / Test / compile) java.nio.channels.OverlappingFileLockException
[error] (streamsJVM / Test / compile) java.nio.channels.OverlappingFileLockException
[error] (coreJVM / Test / compile) java.nio.channels.OverlappingFileLockException
[error] Total time: 61 s (01:01), completed May 7, 2020, 4:47:22 PM

Should I do it all over again and run `build` before pushing? Also, I have added the changes to a new branch, is this expected or should I just stick with master branch ?

**Comment by adamgfraser** [comment]
It is generally good practice to create a new branch like you have done. I haven't seen those errors before but they look like local to your system. I might try quitting your IDE, doing `clean` in SBT, and then trying to run `prepare` again.

**Comment by PyAntony** [comment]
I keep getting some errors. Maybe Intellij already messed up everything. I will re-do it following the steps indicated and place another pull request.

**Pull request closed without merging**
