### PR TITLE
NOTICE.MD with attribution for MUnit

### PR DESCRIPTION
**Pull request by dkarlinsky**
https://github.com/dkarlinsky/zio/commit/a156a7d07a5733a76161b5104e2e44bb9c45eeee#r37650151

### CODE REVIEW

**Comment by softinio** [comment]
best have our own implementation as per the original PR comments Adam linked to. 

cc @jdegoes

**Comment by jdegoes** [comment]
Indeed, our own implementation would be ideal. Who likes algorithms and data structures? 😆

**Comment by jdegoes** [comment]
This one uses dynamic programming which can also be done via memoizing a recursive solution, in a cleaner and more functional way (albeit not as fast, but probably won't matter for any reasonable-sized diffs).

**Comment by neko-kai** [comment]
Do we need a notice for attribution? You could probably just add a comment linking to original as in `AkkaLineNumbers`

**Comment by dkarlinsky** [comment]
@neko-kai I added a comment linking to the original class in MUnit, in the original PR.
This PR is in response to a comment by @olafurpg  on the original PR, asking that we add the NOTICE file.

@adamgfraser I guess I misunderstood you. I thought it was fine to take just the myers diff implementation from MUnit (like was done with `AkkaLineNumbers`).

I can look into reworking it to be more functional

**Comment by softinio** [comment]
@dkarlinsky Please take a look at this comment: 

https://github.com/zio/zio/issues/2784#issuecomment-584627350

> we want to implement our own diffing functionality based on the Myers diff algorithm

so not usiing munit implementation is the end goal is how I understand it and preferred

**Comment by adamgfraser** [comment]
Superseded by #3056.

**Pull request closed without merging**
