### PR TITLE
Fully qualify timeouts and other failures in test Summary

### PR DESCRIPTION
**Pull request by swoogles**
Before:
Screen Shot 2022-04-22 at 10 23 17 AM

After:
Screen Shot 2022-04-22 at 10 32 42 AM

### CODE REVIEW

**Comment by vigoo** [comment]
Why not show the failed ones as a tree as well? What if multiple child nodes are timing out?

**Review by adamgfraser — APPROVED** [review]

**Comment by adamgfraser** [comment]
This just makes the reporting of all failures consistent. We definitely could have a more tree versus list like view in the failure summary but since the summary is already list like I think it is probably better to get this additional information in there and then we can move to a tree like view if we think it makes sense.

**Comment by swoogles** [comment]
> Why not show the failed ones as a tree as well? What if multiple child nodes are timing out?

Yeah, I was considering tree-rendering at the bottom. There was precedent before where we flattened things into 1 line for the summary, so I've left it that way for now. 

One of the issues is that, since these failures are isolated events by this time that have already been handed off to SBT, we can't leverage our parent suites already being printed, and we would have to recreate the tree for each failure.

That last explanation feels confusing, so I'll demo what I mean.

If we print the tree view, it wouldn't look like this:
```
 - outter suite
    - inner suite
      - test failure 1
      - test failure 2
```
But would instead be:
```
 - outter suite
    - inner suite
      - test failure 1
 - outter suite
    - inner suite
      - test failure 2      
```

It might still be an improvement, but it wouldn't be as clear as it looks when the tests are streaming their output.

**Comment by adamgfraser** [comment]
I think if we did it we would definitely want the first view. I would think there would be a way to augment our summary data structure to support that. Going to merge this and we can work on that in a follow up.

**Pull request merged**
