### PR TITLE
Avoid additional `Function1` allocation when using `ZIO.succeed` in Scala 3

### PR DESCRIPTION
**Pull request by kyri-petrou**
## Context

In Scala 3, the `ZIO.succeed` method signature is different than in Scala 2:

Scala 2:
```scala
def succeed[A](a: => A)(implicit trace: Trace): ZIO[Any, Nothing, A] =
  ZIO.Sync(trace, () => a)
```

Scala 3:
```scala
def succeed[A](a: Unsafe ?=> A)(implicit trace: Trace): ZIO[Any, Nothing, A] =
  ZIO.Sync(trace, () => a(using Unsafe.unsafe))
```

The problem with the Scala 3 variant is that the context function `Unsafe ?=> A` is a `Function1`, whereas the `() => A` function of Sync is a `Function0` (same as `=> A`). Therefore, when we call `ZIO.succeed` in Scala 3 we: 
1. Allocate a `Function1`
2. Allocate a `Function0` via a closure

## Main changes

The solution to this is to make the `succeed` method and the parameter inline, which prevents the allocation of the intermediate `Function1`. However, since `inline` methods don't exist in the bytecode, we need to add the following method to make this change binary compatible:

```scala 3
@targetName("succeed")
def succeedCompat[A](a: Unsafe ?=> A)(implicit trace: Trace): ZIO[Any, Nothing, A] =
  succeed(a)
```

The usage of the `@targetName` annotation is so that the `succeedCompat` method's name changes to `succeed` in the generated bytecode, which means that code compiled with older ZIO versions can still use it.

## Other changes

In order to get the best possible performance out of these changes, we also make the companion object of Unsafe extend Unsafe itself and use this directlly. The reasoning behind this is that in Scala, a `val` (e.g., `val unsafe: Unsafe = ???`) placed in an object is compiled to the following:

```scala
private <static> val unsafe: Unsafe
def unsafe(): Unsafe = zio.Unsafe.unsafe
```

Inspecting the bytecode, we can see that calls to `Unsafe.unsafe` require both a GETSTATIC on the object and a method call:

```
GETSTATIC zio/Unsafe$.MODULE$ : Lzio/Unsafe$;
INVOKEVIRTUAL zio/Unsafe$.unsafe ()Lzio/Unsafe;
```

But when we use `Unsafe` directly, we avoid the additional method call which is more performant:
```
GETSTATIC zio/Unsafe$.MODULE$ : Lzio/Unsafe$;
```

The "downside" to this is that now users have access to an instance of Unsafe directly. However, I don't really think this is much of an issue, because previously they could also do this simply by doing this:

```scala
val unsafe: Unsafe = Unsafe.unsafe(identity)
```

If we're OK with this change, I can also change all usages of `Unsafe.unsafe` in the codebase to use `Unsafe` directly, or at least all usages that are in the hot path (e.g., FiberRuntime loop)

### CODE REVIEW

**Comment by 987Nabil** [comment]
@kyri-petrou could you check, what happens if you use `inline val unsafe`? Is it maybe more byte code efficient? Would that be a preferable solution?

**Comment by kyri-petrou** [comment]
`inline val` won't work because it won't be binary compatible and it only works for Scala 3. Might be able to make it work with `final val` though, I'll give it a try.

As for byte code efficiency, this implementation is as efficient as possible, but it does have the downside that it requires code changes to see the benefit so ideally we want to make it possible without that

**Comment by hearnadam** [comment]
2 other ideas that may improve compatibility of this code with previous versions:
1. `UnsafeVersionSpecific` with `inline def unsafe` and `unsafeCompat`
2. private `UnsafeInstance`

Would need to explore the bytecode more here, but that may remove the necessity for changes...

**Comment by kyri-petrou** [comment]
> 2 other ideas that may improve compatibility of this code with previous versions:
> 
> 1. `UnsafeVersionSpecific` with `inline def unsafe` and `unsafeCompat`
> 2. private `UnsafeInstance`
> 
> Would need to explore the bytecode more here, but that may remove the necessity for changes...

Interestingly this is what I had at first, but instead of `inline def unsafe` I used `@static val unsafe` (new annotation in Scala 3). Only Scala 3 will see the benefit from these changes but I think this is still better than having to change the code everywhere

**Comment by kyri-petrou** [comment]
Aghh unfortunately I can't make neither `@static` nor `inline def` binary compatible :( It seems it's disagreeing with the overloaded `unsafe` method :/

**Comment by hearnadam** [comment]
@kyri-petrou did you ever get a chance to configure CI to upload Jars? I would like to take a look at the resulting bytecode.

**Comment by jdegoes** [comment]
@kyri-petrou Definitely in favor of this!

**Comment by kyri-petrou** [comment]
@hearnadam unfortunately no, not yet. If it's any reassuring, I did that extensively (looking both at compiler outputs and the decompiled JVM code) and it looks much better

@jdegoes Let's get this PR merged in and I'll do the changes to use `Unsafe` directly in a followup one

**Review by hearnadam — APPROVED** [review]

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
