### PR TITLE
Make `test` compile to JS

### PR DESCRIPTION
**Pull request by vasilmkd**
Addresses #1227.

### CODE REVIEW

**Comment by jdegoes** [comment]
@vasilmkd Thank you again! Great work. 🙏

**Comment by LGLO** [comment]
@vasilmkd I'm bit late to the party. Could you check that when some project depends on `test` and is ScalaJS itself, then it will not "compile" zio test cases?
What I mean: we don't want zio-core test cases to be JS "compiled" when someone needs zio-test framework.

**Comment by vasilmkd** [comment]
I'm sorry, I don't quite understand what you mean. These changes are already merged, maybe you could try this yourself? I'm sorry for the confusion.

**Comment by LGLO** [comment]
Ok, I'll do!

**Comment by LGLO** [comment]
@vasilmkd All is good, sorry for my false alarm!
zio-test jar contains only "framework" files!

**Comment by vasilmkd** [comment]
I'm glad to hear it because I definitely did not foresee that. 😅

**Pull request merged**
