### PR TITLE
Implement ZLayer#flatMap

### LINKED ISSUE #5339: ZIO 2.0: Add ZLayer#flatMap
Mainly so people can choose what layer to make based on data read from configuration.

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #5339.

### CODE REVIEW

**Comment by octavz** [comment]
hi, can this be back ported to 1.x?

**Comment by adamgfraser** [comment]
@octavz Yes when this is merged.

**Comment by octavz** [comment]
thanks.

**Review by jdegoes — APPROVED** [review]

**Comment by valentin-panalyt** [comment]
Looking forward to the backport :)

**Comment by adamgfraser** [comment]
@valentin-panalyt It has already been done and is available in `1.0.11`.

**Pull request merged**
