### PR TITLE
Pull out all core tests into `core-tests`

### PR DESCRIPTION
**Pull request by mgibowski**
Addresses #1225

Some comments:

* The core module was publishing test classes as part of the artifact (`publishArtifact in (Test, packageBin) := true` ), so I moved that setting to the new `core-tests` module as this is where the core tests now reside.
* Most of the tests were moved to `core-tests` module, but some base classes (`TestRuntime`, `BaseCrossPlatformSpec`) were also used in the `test` module, so they landed over there.
* Moved back some tests in `test` module from `shared` to `jvm`, as previously they were actually not run in JS. More details [here](https://github.com/zio/zio/issues/1227#issuecomment-515421446)

### CODE REVIEW

**Comment by jdegoes** [comment]
@mgibowski Looks great!

What did this end up doing with "not truly JS" tests?

**Comment by mgibowski** [comment]
@jdegoes thanks for the review!

> What did this end up doing with "not truly JS" tests?

I needed to move back the tests from `test/shared/src/test/scala/zio/test/mock/` to `test/jvm/src/test/scala/zio/test/mock/`. Otherwise there were JS compilation errors.

The difference is that currently on the master the `test` module doesn't get compiled and tested in JS (some non-obvious `sbt` behavior). In this branch it does.

**Comment by jdegoes** [comment]
@mgibowski That's totally fine, we can move them back once `TestRuntime` is gone, hopefully next week.

Ready to merge as soon as conflicts are fixed!

**Comment by mgibowski** [comment]
@jdegoes ok, great!

Conflicts fixed.

**Pull request merged**
