### PR TITLE
Chunk#flatMap construct result array from the back

### PR DESCRIPTION
**Pull request by vasilmkd**
@iravid @jdegoes

### CODE REVIEW

**Comment by iravid** [comment]
I’m all for optimizations but this one needs to be benchmarked, as not many things are faster than preprnding to a list

**Comment by iravid** [comment]
See http://www.lihaoyi.com/post/BenchmarkingScalaCollections.html#construction-performance

**Comment by vasilmkd** [comment]
Hmmm, TIL. Thanks. I have another idea.

**Comment by vasilmkd** [comment]
@iravid How about now?

**Pull request merged**
