### PR TITLE
Delete ZTrace#prettyPrint, use Cause#prettyPrint instead (#5853)

### PR DESCRIPTION
**Pull request by zhrebicek**
Hope it is intended to use the printer from `Cause` like this `Cause.traced(Cause.empty, _).prettyPrint`

### CODE REVIEW

**Comment by zhrebicek** [comment]
It compiles locally just fine but fails in CI because it supposedly can't find `Cause#traced`  what am I missing here?

**Comment by adamgfraser** [comment]
It looks like it is trying to find Scaladoc for that which doesn't really make sense. Does it help if you extract the variable out of the string interpolation?

**Comment by zhrebicek** [comment]
@adamgfraser tried that with no luck

**Comment by zhrebicek** [comment]
The reason was me force pushing stuff over new implementation of `Cause` that was really missing `traced`

**Review by adamgfraser — APPROVED** [review]
Thank you! 🙏

**Pull request merged**
