### PR TITLE
Update Dotty (Scala 3) to 3.0.0-M1

### PR DESCRIPTION
**Pull request by atrianac**

### CODE REVIEW

**Comment by sideeffffect** [comment]
Those read builds just need restarting, @mijicd @softinio could you please do that for us?

**Review by sideeffffect — CHANGES_REQUESTED** [review]
You'll also have to change the CircleCI config here.
Yes, Scala versions have to be changed at two places, I know :crying_cat_face:

**Comment by sideeffffect** [comment]
:+1:

**Comment by atrianac** [comment]
> You'll also have to change the CircleCI config here.
> Yes, Scala versions have to be changed at two places, I know 😿

I did it. Thanks

**Comment by atrianac** [comment]
I will update with izumi-1.0.0-m10: https://github.com/zio/izumi-reflect/releases/tag/v1.0.0-M10

**Comment by sideeffffect** [comment]
Hint: it's `scala.util.Not` now :wink:

**Comment by sideeffffect** [comment]
Another hint: if you get errors like `x: AppendN[A]` `cannot be checked at runtime`, just throw away the type variable like this: `x: AppendN[_]`

**Comment by sideeffffect** [comment]
@atrianac did you get my hint or was I being too cryptic? :smile:

**Comment by sideeffffect** [comment]
@atrianac The builds are green :tada: Now you just need to sign CLA and we're good to go

**Comment by atrianac** [comment]
> @atrianac The builds are green 🎉 Now you just need to sign CLA and we're good to go

Great! It is green

**Comment by sideeffffect** [comment]
Can we please get an approval and have this PR merged? :pray: 
@atrianac has been kind enough to put up the necessary work to publish ZIO for Scala 3.0.0-M1 (so that he could do the same for ZIO Prelude).

/cc @jdegoes @adamgfraser @mijicd @softinio

**Review by ghostdogpr — APPROVED** [review]

**Comment by ghostdogpr** [comment]
@atrianac thank you! 🎉

**Pull request merged**
