### PR TITLE
Rename all packages from scalaz.zio to zio._

### PR DESCRIPTION
**Pull request by ReiReiRei**
Rename all packages from scalaz.zio to zio._

### CODE REVIEW

**Comment by jdegoes** [comment]
@ReiReiRei This looks great! Can you fix the merge conflicts?

**Comment by ReiReiRei** [comment]
Yes, of course

**Comment by ReiReiRei** [comment]
@jdegoes I've finished the fixes, I think this PR should be merged as soon as possible because of a lot of file's path have been renamed, and any new file can produce a merge conflict

**Comment by jdegoes** [comment]
@ReiReiRei Done. Thank you for your work on this (I really _hope_ you had tool support! 😄), and congratulations on your first PR to ZIO!

giphy

**Pull request merged**
