### PR TITLE
Accumulate errors in parallel stream operators

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Added to `mapOutZIOPar*` and `mergeAllWith`. Also did some tidying up for clarity and fixed a couple of bugs:

1. unbounded queue worker creation:

```
queue.offer(x) *> worker.fork.unlessZIO(queue.isEmpty)
```
should be
```
worker.fork.unlessZIO(queue.isEmpty) <* queue.offer(x)
```

2. missing accumulation of the done signals in `mergeAllWith` with a buffer sliding strategy (nobody complained so perhaps this method is never used)

3. error handling in worker should be out of the repeat loop (though i see somebody else noticed it too, great)

4. cancellers in `mergeAllWith` were in a queue but that's wrong. it will ensure the FIFO order but what is workers that started late have finished early? then there is no need to cancel anything. so, a `SortedMap` is a better approach for this, where the key is the worker id (i.e. its insertion order).

I really don't know what's that `mergeAllWith0` laying around, what is the meaning of it?

### CODE REVIEW

**Comment by kyri-petrou** [comment]
Hey thanks for these! I'll try and review it in detail over the next few days but it'd be good if @eyalfa can take a look as well since he wrote most of that code.

> I really don't know what's that mergeAllWith0 laying around, what is the meaning of it?

AFAICT that was the pre-2.1.3 implementation. @eyalfa what was the reason that you kept it in a public method?

**Comment by regiskuckaertz** [comment]
There is also a `mapOutZIOParUnordered1`. If these functions have meaningful semantics that are needed to achieve X, they need a correct name. Or else they should be removed.

**Comment by regiskuckaertz** [comment]
@kyri-petrou ping

**Comment by kyri-petrou** [comment]
@eyalfa can you please take a look at this PR? I know you're working on something here in parallel just want to make sure there aren't any conflicts or overlaps

**Comment by kyri-petrou** [comment]
@regiskuckaertz is this PR still needed now that #9054 was merged in?

**Comment by regiskuckaertz** [comment]
@kyri-petrou yes! there are bugs in the old-but-new implementation too, I am closing this one and will reopen separate PRs, easier to review.

**Comment by eyalfa** [comment]
I know I'm late for the game, for some reason missed the notification and seeing this on mobile atm.

One thing that pops to my eye:
The change to this line:

queue.offer(x) *> worker.fork.unlessZIO(queue.isEmpty)

Is incorrect, the idea was to place a msg in the queue,  give existing workers a chance to grab it before spawning a new one. Changing this increases the chances of spawning unnecessary workers

**Comment by regiskuckaertz** [comment]
oh, I understand your reasoning. I was coming from the view that if the queue is empty, there is a chance at least one worker is waiting. It seems your version will put that chance to the test indeed. Now that I think about it, there is a way to know if that is the case since `queue.size` will be negative if there are fibers awaiting, so maybe this is addressing both:
```scala
worker.fork.unlessZIO(queue.size.map(_ < 0)) *> queue.offer(x)
```
now if size is 0 we know that all workers are busy. What do you think?

**Pull request closed without merging**
