### PR TITLE
Update scala 2.12.12, 2.13.3, 0.25.0, silencer 1.7.0 & enable docs for scala 2.13

### PR DESCRIPTION
**Pull request by ohze**
This PR also includes changes in #4001, #4002 #4003
Almost all changes are auto-generated by scalafix

### CODE REVIEW

**Comment by adamgfraser** [comment]
@ohze Thanks! Can you fix the compilation errors?

**Comment by adamgfraser** [comment]
Looks like there is a Dotty compilation issue. Not sure why the `lint` and `mdoc` steps in CI aren't running.

**Comment by adamgfraser** [comment]
@ohze Can you resolve conflicts and fix the compilation errors?

**Comment by jdegoes** [comment]
@ohze I will close this for now as there are still Dotty compilation errors. Let us know if you need any hints to sort them out, and feel free to re-open anytime!

**Pull request closed without merging**
