### PR TITLE
Added encoders for ZIO Streams.

### LINKED ISSUE #5630: ZIO Streams 2.0: Encoders to match decoders
We have utf8Decode but not utf8Encode, etc.

### PR DESCRIPTION
**Pull request by ithinkicancode**
Resolves #5630

### CODE REVIEW

**Comment by ithinkicancode** [comment]
First attempt to add encoders that corresponds to existing decoders. Fixed a bug in `utfDecode` along the way.

**Comment by ithinkicancode** [comment]
TODO's
- [ ] Add scaladoc for the new methods
- [ ] Implement the same for `ZSink`
- [ ] Implement all these as Aspects

**Comment by jdegoes** [comment]
@ithinkicancode Awesome work! Let us know when you are ready for a review. 👍

**Review by adamgfraser — CHANGES_REQUESTED** [review]
Do you want to move this over to the channel encoding?

**Comment by ithinkicancode** [comment]
Yes, the v2 encoders will be implemented as pipelines. 

What has been implemented in this PR are the encoders for the v1 ZStream, which might be removed when the `experimental` ZStream takes over.

**Comment by adamgfraser** [comment]
Yeah I think we are close enough to merging the experimental stream encoding that I would just go straight to that.

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
