### PR TITLE
update canfail docs url

### PR DESCRIPTION
**Pull request by contrun**

### CODE REVIEW

**Comment by adamgfraser** [comment]
@softinio If you have a chance could you look at the CI here? It isn't being run with the usual size and I don't have the ability to rerun.

**Comment by softinio** [comment]
@adamgfraser something unusual might be a circleci glitch if you look at this circle build its for `contrun` org and not `zio` (see its url below) and hence I don't have access either. Never seen this happen before.

https://circleci.com/gh/contrun/zio/97?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Will investigate more.

**Comment by adamgfraser** [comment]
@softinio I think we saw this once before. I think it occurs when the contributor has their own CircleCI account so the build is run under that account instead of the ZIO organization. I think last time the contributor had to temporarily disconnect but hopefully there is a way we can set it up so that it is run on our account.

**Comment by softinio** [comment]
@adamgfraser and if you look at our builds I can't find one for this PR: https://circleci.com/gh/zio/zio

**Comment by softinio** [comment]
> @softinio I think we saw this once before. I think it occurs when the contributor has their own CircleCI account so the build is run under that account instead of the ZIO organization. I think last time the contributor had to temporarily disconnect but hopefully there is a way we can set it up so that it is run on our account.

Ok I had never seen it facinating :-) 

Will leave for @contrun to help with that then

Ping me if I can help more

**Comment by adamgfraser** [comment]
Can we raise an issue with CircleCI to see if there is anything we can do to prevent this from happening or resolve more easily in the future?

**Comment by softinio** [comment]
@adamgfraser good idea ! Let me see if I can do that.

**Comment by softinio** [comment]
@adamgfraser raised support ticket with circle. Will let you know when I hear back.

```
Standard: No SLA guarantee (we typically do our best to respond within 3 business days)
```

**Comment by contrun** [comment]
@softinio @adamgfraser I just retriggered tests. It has passed.

**Comment by adamgfraser** [comment]
@contrun Thank you! Sorry for the hassle there.

**Comment by contrun** [comment]
@adamgfraser no problem.

**Comment by softinio** [comment]
@adamgfraser @contrun This is what I got back from CircleCI support:

```
Hello,

Thank you for reaching out to CircleCI support!

This will typically occur when a user follows their fork on our end, rather than the original project. Asking the user to unfollow their project within CircleCI and follow the original project should allow their builds to trigger normally under the organization's CircleCI account.

Let us know if you have any other questions, happy building!

Gabriel Simmer
Support Engineer @ CircleCI
```

**Comment by contrun** [comment]
@softinio Thank you for your efforts. I am glad to learn this.

**Pull request merged**
