### PR TITLE
Add ZManaged.makeExit that allows to handle `Exit` by the finalizer.

### LINKED ISSUE #1231: Add ZManaged.makeExit
The signature might be: 
```scala
def makeExit[R, E, A](acquire: ZIO[R, E, A])(release: (A, Exit[_, _]) => ZIO[R, Nothing, _]): ZManaged[R, E, A]
```
or
```scala
def makeExit[R, E, A](acquire: ZIO[R, E, A])(release: (A, Option[Cause[_]]) => ZIO[R, Nothing, _]): ZManaged[R, E, A]
```

One possible use case for this can be the saga pattern.

Created as discussed on gitter.

### PR DESCRIPTION
**Pull request by vvlevykin**
Resolves #1231.

### CODE REVIEW

**Comment by iravid** [comment]
This needs a rebase and a fix to mdoc and should be good to go!

**Comment by vvlevykin** [comment]
This example from the doc becomes clunky, what do you suggest instead of `???` here?
```scala
val data: IO[IOException, String] = for {
  p <- Promise.make[IOException,File]
  res = Reservation(openFile("x", p), _ => closeFile(p))
  result <- (for {
      fiber  <- res.acquire.fork
      ex     <- fiber.interrupt
      data   <- ex.toEither.fold(e => IO.fail(new InterruptedIOException("Stop!")), file => readFile(file))
    } yield data).ensuring(res.release(???))
} yield result
```

**Comment by iravid** [comment]
@vvlevykin I'd just delete the entire section on that. `Reservation` doesn't have any value outside the context of `ZManaged` and that example does not make sense to me.

**Comment by iravid** [comment]
Nicely done - thanks @vvlevykin!

**Pull request merged**
