### PR TITLE
Remove FixScalafmtPlugin

### PR DESCRIPTION
**Pull request by denisgarci**
Fix https://github.com/zio/zio/issues/944
It's not clear if https://github.com/scalameta/scalafmt/issues/1399 is fixed in scalafmt 2.0.0-RC8 but it's worth trying it out.

### CODE REVIEW

**Comment by denisgarci** [comment]
@softinio Did you get the `classpath is corrupted` every time or is it flaky?

**Comment by softinio** [comment]
@denisgarci `classpath is corrupted ` is the issue I got. Great to see new release which hopefully fixes this issues. 

@iravid is making some changes to our circleci build process if ok lets wait till he is done before we test and move forward with this PR. 

Really appreciate the PR thank you.

**Comment by denisgarci** [comment]
Thanks for the quick reply @softinio . I'll rebase once the CircleCI PRs are merged.

**Comment by jdegoes** [comment]
@softinio @NeQuissimus @denisgarci Is this good to merge?

**Comment by softinio** [comment]
@denisgarci can you rebase with latest with master to get the latest circle changes. That will start a new build and as long as that passes we can move forward.

@jdegoes We can merge as soon as ^^

Looked at Scalafmt , their new release should have fixed the issue but there will be a small risk it doesn't. We can revert if so but risk low as new build I suggested we do before merge should highlight it.

**Comment by denisgarci** [comment]
@softinio just rebased.

**Comment by softinio** [comment]
@denisgarci Thanks. Build failed so rebuilding lets see how it goes

**Pull request merged**
