### PR TITLE
Add rightOrFailWith and leftOrFailWith and error transform docs

### PR DESCRIPTION
**Pull request by Fristi**
I had some functions already which were doing this already, would be nice if we can lift these boxes inside a ZIO effect without too much folding and such :)

### CODE REVIEW

**Comment by adamgfraser** [comment]
Thanks for contributing!

I think several of these are very similar to existing combinators. In particular:

- `fromEitherM(v)` <-> `v.absolve`
- `ofEither(v, ifLeft)` <-> `fromEither(v).mapError(ifLeft)`
- `ofEitherM(v, ifLeft)` <-> `v.flatMap(fromEither(_).mapError(ifLeft))`
- `ofOption(v, ifEmpty)` <-> `fromOption(v).orElseFail(ifEmpty)`
- `ofOptionM(v, ifEmpty)` <-> `v.someOrFail(ifEmpty)`

I think most of these are pretty straightforward and at most take two method calls when you essentially want to do two things: lifting a value into an effect an transform the error value. The one that is not quite as nice is the replacement for your `ofEitherM` method. `rightOrFail` almost does what we need but not quite because it just lets us specify a new error value and not transform the existing error value. Maybe we add a `rightOrFailWith` variant for that?

**Comment by adamgfraser** [comment]
@Fristi Are you interested in working on the `leftOrFailWith` and `rightOrFailWith` variants?

**Comment by Fristi** [comment]
Yes, let's see if I can squeeze some time on it this week

**Comment by adamgfraser** [comment]
Sounds good. Let me know if there is anything I can do to help.

**Comment by Fristi** [comment]
I added those combinators and some helpful documentation I think :) Let me know what you think

**Comment by Fristi** [comment]
Great! Looking forward to have it in the next release

**Comment by adamgfraser** [comment]
@Fristi Thanks for your contribution on this!

**Pull request merged**
