### PR TITLE
Rename layer -> environmentLayer in ZIOApp

### PR DESCRIPTION
**Pull request by kitlangton**
I often find myself defining a `layer` val in `ZIOAppDefault` but it ends up causing unexpected complier errors because I'm overriding the empty default layer. Similar ergonomics improvement to #6639

### CODE REVIEW

**Review by adamgfraser — COMMENTED** [review]
I agree we need to rename this. `environmentLayer` is a little bit of a weird name because every later outputs an environment. Maybe these should be `zioAppLayer` and `zioAppTag`? Not sure. Open to other naming ideas as well. Unfortunately there is a trade off between simple names here and avoiding name clashes.

**Comment by kitlangton** [comment]
I was only thinking that because it outputs the `Environment` type :P But yeah, happy with `appLayer` and `appTag` or `zioApp*`. That's probably weird enough to avoid most collisions.

**Comment by adamgfraser** [comment]
Yeah that is the argument for `environment`. I don't love any of the names but I also don't know if I have a better one and don't feel strongly. Maybe we give it a bit and then we just pick something?

**Comment by adamgfraser** [comment]
Could also be `sharedLayer`.

**Comment by kitlangton** [comment]
> Yeah that is the argument for `environment`. I don't love any of the names but I also don't know if I have a better one and don't feel strongly. Maybe we give it a bit and then we just pick something?

Sounds good :) No rush

**Pull request closed without merging**
