### PR TITLE
Update test_effects.md

### PR DESCRIPTION
**Pull request by serragnoli**
Fixed examples with `suite`

### CODE REVIEW

**Comment by jdegoes** [comment]
@serragnoli This is great. Would be even nicer to make these compile using the `mdoc` annotation. Would you be interested in taking a look at that?

**Comment by serragnoli** [comment]
@jdegoes / @adamgfraser 
How does it look now?

**Comment by serragnoli** [comment]
@jdegoes The [doc](https://github.com/zio/zio/blob/master/docs/about/contributing.md#get-your-pull-request-merged) says the author should merge the PR, but I don't have write access to it. Can you do it please?

**Comment by adamgfraser** [comment]
@serragnoli Just merged it.

**Pull request merged**
