### PR TITLE
Bug fix: `ZStream#timeoutError` has a by-name error parameter that is eagerly evaluated

### LINKED ISSUE #4725: `ZStream#timeoutError` has by-name error parameter, but evaluates it in any case
```scala
  final def timeoutError[E1 >: E](e: => E1)(d: Duration): ZStream[R with Clock, E1, O] =
    timeoutErrorCause(Cause.fail(e))(d)

  final def timeoutErrorCause[E1 >: E](cause: Cause[E1])(d: Duration): ZStream[R with Clock, E1, O] =
    ..

  //in Cause
  def fail[E](error: E): Cause[E] = Internal.Fail(error)
```

Probably the most reasonable solution would be to make `timeoutErrorCause`'s `cause` a by-name too, but that breaks binary compatibility. Possibly a workaround can be done by making the existing method `private` and shadowing it with a public one with the right signature.

### PR DESCRIPTION
**Pull request by harveywi**
Resolves #4725.

### CODE REVIEW

**Comment by iravid** [comment]
Nice work @harveywi! It's surprising to me that this works because I would assume that calling a function that requires a strict parameter with a by-name parameter would cause the by-name parameter to be evaluated.

This is what I'm seeing in the REPL:
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)
def strict(s: String) = "not s"

def byName(s: => String) = strict(s)

// Exiting paste mode, now interpreting.

def strict(s: String): String
def byName(s: => String): String

scala> byName(s())
evaluating
val res0: String = not s
```

**Comment by iravid** [comment]
Sorry I forgot to paste the definition of `s` in the snippet above; fixed now.

**Comment by iravid** [comment]
So we might have a problem with `assertLazy`? 🤔

**Comment by harveywi** [comment]
> Nice work @harveywi!

🥳 Thank you!

> It's surprising to me that this works because I would assume that calling a function that requires a strict parameter with a by-name parameter would cause the by-name parameter to be evaluated.

In this particular case, the by-name parameter `e` is only evaluated if the right-hand side of the argument here is evaluated: `.mapErrorCause(_ => Cause.fail(e))`. So we don't actually pass `e` in as a strict parameter: It is only evaluated if it must be wrapped in a `Cause`, which happens lazily by virtue of the mechanics of function evaluation. Conceptually, it looks okay to me, but I may have overlooked something.

To put your mind at ease a bit about `assertLazy`: The new test that was added to the `zio.stream.StreamLazinessSpec` suite fails if we use the original implementation of `timeoutError`. So it appears that `assertLazy` is working properly.

**Review by iravid — APPROVED** [review]
Oh you're right @harveywi. I had the example backwards. This is good to merge then; could you just check why the lint step is failing?

**Review by iravid — APPROVED** [review]
Great work @harveywi!

**Pull request merged**
