### PR TITLE
Backport #6743 to 1.x

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by kubukoz** [comment]
cc @kitlangton

**Review by kitlangton — DISMISSED** [review]
Beautiful! Thank you so much @kubukoz! Don't know why CI isn't running though. Hrm.

**Comment by adamgfraser** [comment]
Can you try merging upstream changes? We just made a change to CI that I think should fix this.

**Comment by kubukoz** [comment]
done - it was a busy week :)

**Comment by adamgfraser** [comment]
@kubukoz Sorry, can you pull upstream changes one more time? There was a fix to the CI configuration that should get that last task passing.

**Comment by kubukoz** [comment]
hmm, git seems not to see anything new on series/1.x

**Comment by adamgfraser** [comment]
Sorry, try now.

**Review by adamgfraser — APPROVED** [review]

**Comment by kubukoz** [comment]
@adamgfraser can you drop a release, please?

**Comment by adamgfraser** [comment]
@kubukoz Will do!

**Pull request merged**
