### PR TITLE
Make `Chunk.IsText` serializable by extending `Serializable`

### PR DESCRIPTION
**Pull request by 987Nabil**
See https://github.com/zio/zio/pull/7098

### CODE REVIEW

**Comment by 987Nabil** [comment]
@adamgfraser I could reproduce the failure locally and this fixed it.

**Comment by adamgfraser** [comment]
@987Nabil Wh are we capturing this?

**Comment by 987Nabil** [comment]
> @987Nabil Wh are we capturing this?

@adamgfraser I am not sure I get your question. But I just thought about, why this actually happens. I guess, it is because the instances are lazy vals and we try to serialize the instance. Then I realized, that it is most likely wrong that `IsText` is in the `Chunk` trait and belongs in the companion object.
I removed again the `extends Serializable` and moved the trait/companion object of `IsText` to the `object Chunk`.
I guess this makes more sense.

**Comment by adamgfraser** [comment]
Yes exactly! It is only an issue that it is not serializable because we are trying to serialize it, but why are we trying to serialize it? There seems to be some weird combination of Java and Scala versions that cause it to occur but I think you are right it is because it is in the trait.

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
