### PR TITLE
Add a samplePercent pipeline to randomly sample a stream

### PR DESCRIPTION
**Pull request by gnp**

### CODE REVIEW

**Review by adamgfraser — COMMENTED** [review]
Maybe just `sample`?

**Comment by gnp** [comment]
> Maybe just `sample`?

I chose `samplePercent` because there are other ways of sampling. For example, I'm also planning to do `sampleN` where you specify a number of elements you want from an arbitrary (finite) length stream. That one probably will be implemented on `ZSink` though. Then, `sample1` is a slight optimization that would have element instead of chunk success type. These could reasonably called `chooseN` and `choose1` instead.

That said, I would not object to calling this one just `sample` if that is important to you, since that is the main and obvious thing. If ever there are variants, it could be those that have a qualifier suffix.

**Comment by gnp** [comment]
I added one additional test and changed the name.

**Comment by adamgfraser** [comment]
That gets a bit to my other concern which is that sampling can be its own entire domain so potentially this belongs in a library that is based on ZIO Stream that focuses on that.

**Comment by gnp** [comment]
I don't think I'm in a good position to design a larger stats / random based stream utilities module. I can see the need for `ZPipeline.sample`, `ZSink.chooseN` and `ZSink.choose1` because I needed `choose1` for some testing I was doing and the others are obvious.

**Comment by gnp** [comment]
Still want this contribution @adamgfraser?

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
