### PR TITLE
Documentation: adding a section on JUnit integration to testing.md

### PR DESCRIPTION
**Pull request by dkarlinsky**
@adamgfraser

### CODE REVIEW

**Comment by jdegoes** [comment]
@dkarlinsky Failure when merged to master, can you take a look?

<https://circleci.com/gh/zio/zio/50708>

**Comment by adamgfraser** [comment]
@jdegoes It was a flaky test unrelated to this PR. Issue created in #2642 and marked as flaky in #2643 to fix build failure until we can address.

**Comment by jdegoes** [comment]
@adamgfraser Thank you! I feel we need a bot some day to auto-post these.

**Comment by adamgfraser** [comment]
@jdegoes That's a great idea!

**Pull request merged**
