### PR TITLE
Contributing to Documentation

### PR DESCRIPTION
**Pull request by khajavi**
In this pull request, I'm going to learn users, how to contribute to the ZIO documentation.

### CODE REVIEW

**Comment by khajavi** [comment]
Hey @atooni 
The CI fails after renaming page routes. Although I changed the sidebar configuration, I am not sure what the exact problem is. Do you have any idea why this is happening? Do you know if it is related to the versioned sidebar (having two different routes on the sidebar)?

**Comment by atooni** [comment]
> Hey @atooni
> The CI fails after renaming page routes. Although I changed the sidebar configuration, I am not sure what the exact problem is. Do you have any idea why this is happening? Do you know if it is related to the versioned sidebar (having two different routes on the sidebar)?

Its a bit tricky ... the normal website takes the 1.x and the 2.x docs and bundles them together. The website check only runs on the 2.x docs. I would guess there is some change that needs to be replicated from the actual website publishing to the check. This having said - I can  have a look later today to see where exactly it is failing. 

Can you build the docs locally to continue with your stuff ?

**Comment by khajavi** [comment]
> > Hey @atooni
> > The CI fails after renaming page routes. Although I changed the sidebar configuration, I am not sure what the exact problem is. Do you have any idea why this is happening? Do you know if it is related to the versioned sidebar (having two different routes on the sidebar)?
> 
> Its a bit tricky ... the normal website takes the 1.x and the 2.x docs and bundles them together. The website check only runs on the 2.x docs. I would guess there is some change that needs to be replicated from the actual website publishing to the check. This having said - I can have a look later today to see where exactly it is failing.
If you could take a look at it, that would be great.

> Can you build the docs locally to continue with your stuff ?

I can build locally without any problem.

**Comment by atooni** [comment]
@khajavi I think you need to merge the latest changes from the `documentation` branch. You can look into `.github/workflows/ci.yml` to see which steps are executed to perform the documentation sanity check. These steps are required as the sanity check only checks whether the 2.x portion of the site can be built to save some time. 

I think I will stick these steps into a script eventually just as I have done it for creating the site. If that doesnt help, let me know and we will a time slot to pair up and get it solved.

**Comment by khajavi** [comment]
> @khajavi I think you need to merge the latest changes from the `documentation` branch. You can look into `.github/workflows/ci.yml` to see which steps are executed to perform the documentation sanity check. These steps are required as the sanity check only checks whether the 2.x portion of the site can be built to save some time.
> 
> I think I will stick these steps into a script eventually just as I have done it for creating the site. If that doesnt help, let me know and we will a time slot to pair up and get it solved.

Thank you for your help!
Since I am not in a hurry, I can continue working on this until your work is ready on the series/2.x branch. After rebasing my branch on yours, I fix any problems found.

**Comment by khajavi** [comment]
@atooni 
Another question raised for me, what is the plan for the `documentation` branch? Where it is going to be merged?

**Comment by atooni** [comment]
Hi @khajavi, 

I have an open todo to add a page to the docs explaining the structure and the build of the ZIO site. In a nutshell, we have decided to have a branch `documantation` and whenever that branch gets pushed the site will update. This allows us to have a different lifecycle of the site than we have for ZIO itself. Before the site was updated upon release only. 

As a result, we regularly merge `series/2.x` into `documentation` to keep it in sync. In other words, the `documentation` branch is rather a merge target than a merge source. 

In your case however, while working on the 2.0 docs, you should eventually merge `documentation`into your branch. All in all, I think it would make more sense to base your work on `documentation` than on `series/2.x`

Hope that makes sense

**Comment by khajavi** [comment]
Fantastic! It makes sense to have a separate lifecycle for documentation. Will try to reflect those change in my branch.

**Comment by khajavi** [comment]
@jdegoes 
It is ready for your review.

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
