### PR TITLE
Compile ZIO Streams for Scala Native

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by adamgfraser** [comment]
Great!

**Review by adamgfraser — APPROVED** [review]

**Comment by sideeffffect** [comment]
@adamgfraser can you pleaes restart the dead builds?

**Comment by adamgfraser** [comment]
@sideeffffect Yep, just did! Hopefully we won't have to deal with this anymore soon. I think I found the root of the problem that should help with the ZIO Prelude builds too.

**Comment by sideeffffect** [comment]
Great news! :muscle: 
Because one build has died again :laughing:

**Comment by adamgfraser** [comment]
😃 I will take care of it and get this merged.

**Comment by sideeffffect** [comment]
@adamgfraser could you please restart the dead builds here https://app.circleci.com/pipelines/github/zio/zio/9074/workflows/f640a5d3-6eff-4290-8deb-20fd6da2df30 ?

**Comment by adamgfraser** [comment]
@sideeffffect Sure.

**Comment by sideeffffect** [comment]
Still one to go https://app.circleci.com/pipelines/github/zio/zio/9074/workflows/e4b61ec9-8941-4855-8909-3109ec9b5793 :pray:

**Comment by sideeffffect** [comment]
this PR deserves the [`scala-native` badge](https://github.com/zio/zio/issues?q=label%3Ascala-native)
@adamgfraser :pray:

**Comment by adamgfraser** [comment]
@sideeffffect We normally use the badges for issues as opposed to PRs. Is there a reason you think the badges would be useful for these in particular?

**Comment by sideeffffect** [comment]
Oh, OK then. It's not necessary :wink:

**Pull request merged**
