### PR TITLE
add updateSome in Ref and RefM

### PR DESCRIPTION
**Pull request by wi101**
In order to be able to modify a `Ref` / `RefM` for some values, I implemented a new function `updateSome`which takes a `PartialFunction`

### CODE REVIEW

**Review by jdegoes — DISMISSED** [review]
Wonderful addition to ZIO! 😄

**Comment by wi101** [comment]
@jdegoes Could you please review modifySome in Ref and RefM ?

**Review by jdegoes — APPROVED** [review]
Looks awesome! Thanks for this contribution, including tests and documentation! ❤️ 🙏

**Comment by zkerriga** [comment]
Hi, @wi101! Was there any reason why the default parameter was not implemented lazy in `modifySome`?
Can I do
```scala
def modifySome[B](default: => B)(pf: PartialFunction[A, (B, A)]): UIO[B]
```
instead of
```scala
def modifySome[B](default: B)(pf: PartialFunction[A, (B, A)]): UIO[B]
```

It seemed to me that this parameter could be used as some kind of error signal:
```scala
for
  ensureWasChanged <- ref.modifySome(ZIO.fail("wasn't changed")) {
    case smth if smth.condition => 
      ZIO.unit -> smth.changed
  }
  _ <- ensureWasChanged // will fail if smth wasn't changed
yield ()
```
And in this case, we should not calculate the parameter immediately. What do you think?

**Comment by adamgfraser** [comment]
@zkerriga A `ZIO` is just a description so you can write the code above regardless of whether the parameter is by name. Also we can't change the signature due to binary compatibility.

**Comment by zkerriga** [comment]
Thanks for the answer @adamgfraser! Yes, `ZIO.fail` can indeed be safely placed as a default value. 

I would like to see a more consistent API compared to other functions like `getOrElse`, `orElse`. But in this case, we can't do anything because of compatibility, so the question is closed :)

**Pull request merged**
