### PR TITLE
docs: add clarification note on initialization of test bootstrap layers

### LINKED ISSUE #8993: Clarify documentation on initialization of test bootstrap layers
At the moment, it's not entirely clear from the [documentation](https://zio.dev/reference/test/sharing-layers-between-multiple-files/) that layers of the same type that are shared between different test suites will be re-initialized unless they are actually the same reference.

For example, having a common super class for database tests that defines a connection layer at the class level will create one connection (or connection pool) for each test suite, and not close them until after all suites have finished, potentially exhausting the database connection allowance.

It would be useful, I think to document that it is necessary to define such layers in a central place, such as the companion object.

### PR DESCRIPTION
**Pull request by varshith257**
/claim #8993
fixes #8993

### CODE REVIEW

**Comment by varshith257** [comment]
@tjarvstrand Does this note provide clarification? or can we also add an example of demonstrating it?

**Comment by varshith257** [comment]
@ghostdogpr @hearnadam Could you review this?

**Comment by tjarvstrand** [comment]
>...such as in the `bootstrap` layer to be shared properly across multiple test suites.

I think this should read "...such as in the companion object...". Otherwise looks all right to me.

**Comment by varshith257** [comment]
@jdegoes Have a look into it

**Comment by varshith257** [comment]
@jdegoes Please take a look 🙏

**Review by ghostdogpr — APPROVED** [review]

**Pull request merged**
