### PR TITLE
Upgrade Dotty Version

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by jdegoes** [comment]
👍

**Comment by smarter** [comment]
The version number is also hardcoded into the CI config, it needs to be changed there too: https://github.com/zio/zio/blob/a92283028641031842d36eb0ad40da121f7dcdeb/.circleci/config.yml#L13

**Comment by adamgfraser** [comment]
@smarter Thanks! Will fix!

**Comment by smarter** [comment]
(Also 0.18.1-RC1 was just released (announcement blog post incoming), so might as well upgrade to that).

**Comment by adamgfraser** [comment]
Sweet! 😃

Congratulations!

**Pull request merged**
