### PR TITLE
Run tests in Circle for non-Dotty builds

### PR DESCRIPTION
**Pull request by iravid**

### CODE REVIEW

**Comment by softinio** [comment]
@iravid I think be good to keep Java11 support.

Here is my idea for overcoming the yarn problem: 

- As we only need yarn to publish our website we replace its docker image in circleci with `- image: circleci/node:8.11.1`
- instead of using SBT to publish docusaurus site to github pages we use yarn to do it with: `cd website && yarn install && GIT_USER=${GH_NAME} yarn run publish-gh-pages`

Here is a draft of the step: 

```
microsite:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "11:2c:fa:98:69:d8:a1:d5:76:2e:38:d0:91:39:85:ce"
      - checkout
      - restore_cache:
          key: node-cache
      - run:
          name: Deploying to Netlify
          command: |
            git config --global user.email "${GH_NAME}@users.noreply.github.com"
            git config --global user.name "${GH_NAME}"
            echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
            cd website && yarn install && GIT_USER=${GH_NAME} yarn run publish-gh-pages
      - save_cache:
          key: node-cache
          paths:
            - "~/website/node_modules"
```

Friday I am short of time as a busy day at work but happy to jump and help with this weekend (Saturday or Sunday).

Let me know how I can help.

ps: The other idea I had we create our own custom base docker image that has all dependencies we need for the ZIO org

**Comment by iravid** [comment]
Thanks @softinio. The main issue right now is that the tests are failing on memory. Got any advice on that? Thought about switching away from containers to using the regular machine executor.

**Comment by iravid** [comment]
Wow I am *this* close to just paying for larger containers

**Comment by softinio** [comment]
@iravid This is painful agreed. Going to reach out to a contact I have at circleci to see if they can help with something with more resources for our OSS project. As Friday prob won't hear back till Monday. 

Though I am a fan of circleci as a backup plan should I evaluate other CI alternatives? Maybe Azure pipelines:

https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

no info on what their limits are which is annoying.

**Comment by iravid** [comment]
We're actually good! I think we can re-add the JDK11 builds now. I switched to the machine executors and they're much more stable. @softinio

**Comment by softinio** [comment]
@iravid Awesome dude! Let me know if anything I can help with this weekend then.

**Comment by iravid** [comment]
This is ready for a review @softinio @NeQuissimus.

**Comment by iravid** [comment]
(I opened a follow-up ticket for re-adding the JDK11 builds)

**Pull request merged**
