### PR TITLE
Implement zipWithLatest

### PR DESCRIPTION
**Pull request by luis3m**
Part of #4886

### CODE REVIEW

**Review by iravid — DISMISSED** [review]
Very cool implementation.

**Comment by iravid** [comment]
Can you resolve conflicts @luis3m?

**Comment by luis3m** [comment]
Sure, I'm on it.

**Comment by luis3m** [comment]
Done, @iravid

**Comment by luis3m** [comment]
Actually, simplified the implementation.

**Comment by iravid** [comment]
Scala.js seems to be hanging 🤔

**Comment by iravid** [comment]
Oh just on 1.8...

**Comment by iravid** [comment]
Yeah sorry this seems to be hanging on all the Scala.js builds. Can you look into that?

**Comment by luis3m** [comment]
@iravid it seems ZChannel#mergeWith doesn't work well in JS. `ZStream.fromChunks(...).zipWithLatest(ZStream.fromChunks(...))` only emits elements from the first stream (because of mergeWith).

**Comment by luis3m** [comment]
@iravid marked hanging test as JVM only, added an alternative test for JS.

**Pull request merged**
