### PR TITLE
Added netlify badge to website

### PR DESCRIPTION
**Pull request by softinio**
Website footer sample from running local: 

https://shared.softinio.com/Screen-Shot-2020-03-13-19-47-23.32.png

### CODE REVIEW

**Comment by softinio** [comment]
> Thanks!
> Do you add it to the live website or shall I?

@ghostdogpr haven't added to site yet! If you have time, can you do it? bit short of time tonight

**Comment by ghostdogpr** [comment]
Oki, i will.

**Comment by softinio** [comment]
> Oki, i will.

@ghostdogpr thx dude! If you feel brave you can try this which I never had and just publish the site from your laptop with the correct version:

`coursier launch org.scalameta:mdoc_2.12:2.1.3 -- --site.VERSION 1.0.0-RC18-2`

See docs: https://scalameta.org/mdoc/docs/installation.html#help

**Comment by ghostdogpr** [comment]
Done! I didn't feel brave and did it manually 😄 I'll contact Netlify to validate our open source status.

**Comment by softinio** [comment]
@ghostdogpr  ty

fingers crossed they will be fine with it being on the home page only till next release.

**Pull request merged**
