### PR TITLE
Clarify Provide Variants

### PR DESCRIPTION
**Pull request by adamgfraser**
Clarifies provide variants by using `provideLayer` for variants that provide layers without use of macros for advanced uses, and `provide` for macro powered variants for improved ergonomics.

### CODE REVIEW

**Review by jdegoes — APPROVED** [review]

**Comment by kitlangton** [comment]
@adamgfraser pushed mdoc fix (at least locally 🤞 )

**Comment by kitlangton** [comment]
I'd also renamed `.wire` to `.make` on my lil' thing. I can open up a follow-up tomorrow for that though. Doesn't involve any renames :)

**Comment by kitlangton** [comment]
Haha! Thank you :D

**Comment by adamgfraser** [comment]
😃

**Review by kitlangton — APPROVED** [review]

**Pull request merged**
