### PR TITLE
clarify state of zio http

### PR DESCRIPTION
**Pull request by TomTriple**

### CODE REVIEW

**Comment by erikvanoosten** [comment]
Since zio-http is quite in flux and documentation is lagging, are we sure we want to point people to zio-http already? I would recommend that we continue to point to dream11's version until zio-http is more stable and documentation is up to date.

**Comment by vigoo** [comment]
> Since zio-http is quite in flux and documentation is lagging, are we sure we want to point people to zio-http already? I would recommend that we continue to point to dream11's version until zio-http is more stable and documentation is up to date.

Although the API is definitely not stable, a lot of bugs have been fixed and missing features were added since the last dream11 release. Also that repo has been transferred so its not really possible to point to the "old one" - it not longer exists.

**Comment by TomTriple** [comment]
Also shouldn't we move the docs in the `official libraries` section? Currently it is listed in the `community libraries` section.

**Comment by adamgfraser** [comment]
@TomTriple Yes.

**Comment by jdegoes** [comment]
@khajavi Please take care of the documentation issue!

**Comment by khajavi** [comment]
The way we introduce docs has changed a lit bit. And there are some more works needed to make this PR ready for go. So I'm going to close this PR.

@TomTriple  Could you please make a PR on `zio-http` project by moving this work to the [`zio-http/docs/index.md`](https://github.com/zio/zio-http/blob/main/docs/index.md) file?

**Comment by TomTriple** [comment]
> 



> The way we introduce docs has changed a lit bit. And there are some more works needed to make this PR ready for go. So I'm going to close this PR.
> 
> @TomTriple Could you please make a PR on `zio-http` project by moving this work to the [`zio-http/docs/index.md`](https://github.com/zio/zio-http/blob/main/docs/index.md) file?

No problem: https://github.com/zio/zio-http/pull/2018

**Pull request closed without merging**
