### PR TITLE
added annotation + log for future error handle

### PR DESCRIPTION
**Pull request by rituraj2342**

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
I don't think these type annotations really increase the clarity of the code.

**Comment by rituraj2342** [comment]
> I don't think these type annotations really increase the clarity of the code.

reverted annotation + only optimizerOptions added in one case

**Review by adamgfraser — COMMENTED** [review]
Okay. Is there a specific reason we want to add those options on Scala 2.11? This is an area where it is easy to introduce regressions so want to make sure there is actually a problem we are trying to solve and there isn't a reason we didn't add this in the past. This is especially true because this only impacts Scala 2.11 so the benefit is minimal.

**Comment by adamgfraser** [comment]
@rituraj2342 Going to close this but please feel free to reopen if you think this is something we should explore further.

**Pull request closed without merging**
