### PR TITLE
Micro optimize Semaphore

### PR DESCRIPTION
**Pull request by erikvanoosten**
- Case class Reservation has smaller footprint as it no longer links to the owning class.
- Use eq/ne where possible.
- Re-use incoming variable in match statement, instead of reconstructing it.

Also, lots of renaming, and use of an ADT (instead of Either and tuples) to increase readability.

### CODE REVIEW

**Review by adamgfraser — COMMENTED** [review]
Is there a problem we are trying to solve here? Otherwise this looks less readable to me.

**Comment by He-Pin** [comment]
I think it's the memory footprint.

**Comment by erikvanoosten** [comment]
This is dense code, it took me an hour to grasp it (though I am still not entirely sure I fully do). The variable `permits` always counts permits, but _what_ permits are counted can be quite different. The biggest problem I faced on the way to understanding was that the state contains the number of still required permits for a given blocked zio. Another confusing thing is that the `acquire` method was not passed as the `acquire` parameter of `acquireRelease`. Anyways, all this is now excruciatingly explicit. Along the way I did some minor micro optimizations.

If you do not like this style of making things explicit, then please do not merge.

**Comment by adamgfraser** [comment]
Okay I think as the person who probably has to maintain this if there are issues here I don't think this would make things easier so going to close this but thanks for your work on this and will take a look at the points you raised!

**Pull request closed without merging**
