### PR TITLE
Documentation: Sharing Services Between Multiple Specs

### LINKED ISSUE #6992: Add Documentation Regarding Shared Test Layers
It looks like we have documentation regarding sharing services within a spec but not between multiple specs.

https://zio.dev/datatypes/test/spec#sharing-layers-within-a-suite

### PR DESCRIPTION
**Pull request by khajavi**
resolves #6992

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
I think what we want to show here is the use of the `bootstrap` layer to share resources between specs in different files. So I think we want this section to have two parts:

1. The previous content you had. you can use `provideXYZShared` for either multiple specs within the same suite or for multiple suites. Whatever layer it is provided to is the scope in which that resource will be shared.
2. New content regarding sharing layers between different Spec files. You can't use the previous pattern here because the specs are in entirely different files and we don't want the boilerplate of creating a "master spec" that references the other specs and needing to update that. So instead we define the resource we want to share as part of the `bootstrap` layer of `ZIOApp`.

**Comment by khajavi** [comment]
@adamgfraser 
This is ready for your review.

**Review by adamgfraser — CHANGES_REQUESTED** [review]
This looks great!

Do you think we can consolidate the sections on `Sharing Layers Within A Suite` and `Sharing Layers Between Multiple Specs`?

I view these as essentially the same thing. We can use `provideShared` and whatever level we call that at we will share between all of those specs. So if we have a simple spec that is just a suite within ten tests and do `provideShared` we will share between all those ten tests. If we have a very complicated spec with multiple nested spec and we can `provideShared` on that whole thing we will share between everything in there.

That way there are only two things you need. `provideShared` variants for anything in the same file, and `bootstrap` technique if you want to share between multiple files.

**Comment by swoogles** [comment]
@adamgfraser I think @khajavi covered everything you asked for. Any remaining concerns to get this merged?

Also, great work Milad! These are going to be very helpful.

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
