### PR TITLE
Added benchmarks for Chunk methods inherited from IndexedSeq

### PR DESCRIPTION
**Pull request by Ethan-Edmond**
I added benchmarks for all of the IndexedSeq methods that weren't already implemented, were present on all tested versions of scala and weren't methods meant for partial functions. It seems to pass all of the tests and has been formatted by sbt fmt.

ref #3353

### CODE REVIEW

**Review by adamgfraser — COMMENTED** [review]
@Ethan-Edmond Thanks for adding! Where did these come from? Did you end up going with the collection benchmarks from the Scala library or are these your own benchmarks? Did you get a chance to run?

**Comment by Ethan-Edmond** [comment]
They are all mine, but I did have a look through the collection benchmarks beforehand so there may be some crossover. I'm running it now. Currently, the only surprises are that combinations is super slow, even though the benchmark for it is pretty much a best case scenario.

**Review by adamgfraser — APPROVED** [review]
@Ethan-Edmond Thanks for your work on this! Would be great to see the benchmark results and make a plan for further optimizations but going to merge this for now.

**Comment by Ethan-Edmond** [comment]
Here's a table of the results.

| Method | Average Time per Operation (ns) | Average Error (ns) |
|------------|---------------------------------------|--------------------|
| addString | 59462.064 | ± 2537.291 |
| canEqual | 8.085 | ± 0.069 |
| collect | 14137.493 | ± 1151.583 |
| collectFirst | 327.980 | ± 10.643 |
| combinations | 166421.025 | ± 1748.654 |
| contains | 10.595 | ± 0.220 |
| containsSlice | 144.499 | ± 1.020 |
| copyToArray | 14.925 | ± 1.260 |
| count | 4089.077 | ± 2.218 |
| diff | 38690.270 | ± 1739.926 |
| distinct | 62443.994 | ± 822.209 |
| dropRight | 18619.845 | ± 75.075 |
| endsWith | 94.899 | ± 2.774 |
| filterNot | 11419.049 | ± 59.763 |
| flatMap | 205951.328 | ± 1488.432 |
| fold | 8326.331 | ± 23.371 |
| foreach | 9.331 | ± 0.128 |
| groupBy | 33110.990 | ± 2314.540 |
| grouped | 115.029 | ± 0.438 |
| indexOf | 12.560 | ± 0.238 |
| indexOfSlice | 234.788 | ± 6.718 |
| indices | 21.829 | ± 0.112 |
| init | 18621.563 | ± 102.374 |
| inits | 80.176 | ± 0.345 |
| intersect | 24248.288 | ± 1912.520 |
| isDefinedAt | 8.427 | ± 0.006 |
| isTraversableAgain | 7.400 | ± 0.205 |
| iterator | 21.902 | ± 0.083 |
| last | 9.359 | ± 0.015 |
| lastIndexOf | 18.598 | ± 0.180 |
| lastIndexOfSlice | 185.641 | ± 1.333 |
| lastIndexWhere | 9.300 | ± 0.394 |
| lengthCompare | 8.423 | ± 0.005 |
| max | 28197.061 | ± 146.167 |
| maxBy | 22265.590 | ± 158.194 |
| min | 28387.716 | ± 160.236 |
| minBy | 19111.526 | ± 118.084 |
| mkString | 54451.117 | ± 559.043 |
| padTo | 21222.655 | ± 299.578 |
| partition | 28691.310 | ± 1597.187 |
| patch | 20674.187 | ± 706.770 |
| permutations | 170911.203 | ± 4502.129 |
| product | 14087.223 | ± 78.748 |
| reduce | 16196.462 | ± 78.510 |
| reduceLeft | 16191.359 | ± 53.726 |
| reduceLeftOption | 16250.190 | ± 60.990 |
| reduceOption | 17665.523 | ± 111.677 |
| reduceRight | 16627.981 | ± 254.322 |
| reduceRightOption | 16199.918 | ± 72.168 |
| reverse | 18032.316 | ± 890.934 |
| reverseIterator | 14.646 | ± 0.079 |
| sameElements | 7.384 | ± 0.208 |
| scan | 22681.097 | ± 120.212 |
| scanLeft | 24522.227 | ± 1519.298 |
| scanRight | 40788.724 | ± 385.918 |
| segmentLength | 651.591 | ± 1.743 |
| sizeBenchmark | 7.579 | ± 0.005 |
| slice | 9.574 | ± 0.477 |
| sliding | 115.236 | ± 0.566 |
| sortBy | 23602.940 | ± 1071.897 |
| sortWith | 28494.576 | ± 945.062 |
| sorted | 24245.401 | ± 1002.580 |
| span | 18865.752 | ± 1266.859 |
| startsWith | 68.673 | ± 0.817 |
| sum | 21188.090 | ± 131.186 |
| tail | 21.791 | ± 0.072 |
| tails | 80.142 | ± 0.170 |
| takeRight | 14922.232 | ± 431.041 |
| toIndexedSeq | 7.195 | ± 0.045 |
| toIterable | 7.204 | ± 0.049 |
| toSeq | 7.171 | ± 0.015 |
| toSet | 215433.845 | ± 3216.272 |
| transpose | 156690.751 | ± 1947.847 |
| unzip | 40046.218 | ± 1339.840 |
| unzip3 | 57491.282 | ± 2731.634 |
| updated | 14955.575 | ± 782.946 |
| view | 12.403 | ± 0.074 |

**Pull request merged**
