### PR TITLE
ZTransducer.dropWhile

### PR DESCRIPTION
**Pull request by regiskuckaertz**

### CODE REVIEW

**Review by iravid — APPROVED** [review]

**Comment by iravid** [comment]
Can you fix the conflicts @regiskuckaertz?

**Comment by regiskuckaertz** [comment]
All set @iravid I commented out the test as it failed. My assumption is that the failing element should just bypass the aggregation step, but it didn't. There may be a bit more work needed there. What do you think?

**Comment by iravid** [comment]
The error handling combinators currently short-circuit the stream. Is that a test from the previous version?

**Review by iravid — APPROVED** [review]

**Comment by regiskuckaertz** [comment]
No, I wrote it thinking about pull safety.

**Comment by iravid** [comment]
Ok, we'll get there soon!

**Pull request merged**
