### PR TITLE
[Do Not Merge] New encodings for ZStream/ZSink

### PR DESCRIPTION
**Pull request by iravid**
We will use this branch as a staging branch for the big encoding refactor.

### CODE REVIEW

**Comment by jdegoes** [comment]
Looking good! Would be good to update this with the latest encoding so we can do the command / query independent of progressing the stream / sink.

**Comment by jdegoes** [comment]
Closed in favor of #2726

**Comment by iravid** [comment]
@jdegoes The point is to merge all the incremental ports of combinators to this branch, and when we're done - merge this branch into master...

**Comment by jdegoes** [comment]
Ah, ok, please ignore me! 😂

**Comment by iravid** [comment]
After more iterations on the design, closing this in favour of #2934.

**Pull request closed without merging**
