### PR TITLE
ZIO Test: Implement Gen#run

### LINKED ISSUE #2270: Single random element
Would it make sense to add this method?

```scala
  final def genValue[R, A](gen: Gen[R, A]): ZIO[R, Unit, A] =
    gen.sample.map(_.value).forever.take(1).runCollect.flatMap(l => ZIO.fromOption(l.headOption))
```

Sometimes I just want a single random element from a `Gen` rather than a full-blown `checkM` test.

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #2270. Adds methods to run a generator to produce a single value, all values, or a specified number of values.

### CODE REVIEW

**Comment by adamgfraser** [comment]
We definitely could. I thought about that and things that led me in this direction and trying to align more with `check`, `checkSome`, and `checkAll` (though in retrospect I think you were right about `zip` so very open to this):

* `run` / `runHead` - getting a single value seemed like a very common use case and the original motivator so wanted to keep that short. Also understand the collection analogy but not sure it is entirely intuitive that a generator has a "head".
* `runAll` / `runCollect` - this one only makes sense for deterministic generators so wanted to try to be explicit about that, though you could say the same thing about `runCollect` and infinite streams
* `runSome` / `???` - not sure what the right name would be to align with stream because of the way we're doing `forever` and `take`.

**Comment by iravid** [comment]
For the last one we could call it `runCollectN`. I wanted to add such a combinator to stream too.

In theory it could also be useful to add a `Gen[A]#run(s: Sink[A])` method, but let's do that when someone actually needs it. Just means that we should reserve the name `run`.

**Comment by adamgfraser** [comment]
I like that! Implemented in the latest version.

**Comment by jdegoes** [comment]
Incidentally, I was thinking `checkSome` => `checkN` is possibly more consistent with the rest of ZIO...

**Comment by adamgfraser** [comment]
I will change that!

**Pull request merged**
