### PR TITLE
Add test assertions for infinite/nan values

### PR DESCRIPTION
**Pull request by fsarradin**
I have added some assertions on types Float and Double in the test module.

I'm not that satisfied with assertion names, but they are the best that I've found.

### CODE REVIEW

**Review by adamgfraser — DISMISSED** [review]
Agree with your feelings about the names but think they are the best there is.

**Comment by fsarradin** [comment]
@adamgfraser I've brought a fix to this PR because `isFinite` is not defined in Scala 2.11. I've directly used the Java definition instead. Can you perform review again?

**Comment by adamgfraser** [comment]
@fsarradin Will do today!

**Review by adamgfraser — APPROVED** [review]
Thank you! 🙏

**Pull request merged**
