### PR TITLE
Add zio nebula graph to sidebar

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
I missed to add the project to the sidebar

### CODE REVIEW

**Review by adamgfraser — DISMISSED** [review]

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by adamgfraser** [comment]
@khajavi Any idea what is going on with the CI failure here?

**Comment by jxnu-liguobin** [comment]
What did CI complain about?

**Comment by khajavi** [comment]
Just start running this on my local machine to diagnose the issue!

**Comment by adamgfraser** [comment]
@khajavi Thank you! 🙏

**Review by khajavi — APPROVED** [review]

**Pull request merged**
