### PR TITLE
Remove debug code from Ref-backed proxy class macro

### PR DESCRIPTION
**Pull request by SHSongs**
Remove debug code from Ref-backed proxy class macro
https://github.com/zio/zio/pull/8061

### CODE REVIEW

**Comment by adamgfraser** [comment]
@SHSongs Thanks for this! Noticed a couple of other things as I was working on using this to implement the `reloadable` functionality.

We want to be able to use the `generate` method in higher level code like this:

```scala
def reload[A: Tag]: IO[ServiceReloader.Error, Unit] =
  ??? // uses generate internally
```

Right now this doesn't work because for a polymorphic type "disallowed" methods such as `getClass` exist and it looks like even if this ignores there are other issues with the macro implementation.

Perhaps we could package this evidence up into a trait, say `ReloadableService` and automatically generate instances of that trait for any data type in which the constraints you implemented are satisfied?

**Comment by guersam** [comment]
Here's a quick sketch. Is this what you mentioned, @adamgfraser?

```scala
trait ReloadableService[A] {
  def tag: Tag[A]
  def serviceProxy: A // macro generated proxy
  def set[R, E](acquire: ZIO[R with Scope, E, A]): ZIO[R, E, Unit] // forward to underlying `ref: ScopedRef[A]`
}
```

```scala
// Use `ReloadableService[A]` instead of `Tag[A]`
def register[A: ReloadableService](serviceLayer: ZLayer[Any, Any, A]): IO[ServiceReloader.Error, A]
```

**Comment by adamgfraser** [comment]
@guersam Yes I think so!

**Comment by jdegoes** [comment]
@guersam @SHSongs All revisions done & ready for review??

**Comment by guersam** [comment]
@jdegoes I think this one is done as it is, but the issue @adamgfraser [pointed out](https://github.com/zio/zio/pull/8092#issuecomment-1531399444) should be addressed. 

As the purpose #8061 was to support #8077, I'd like to ensure that the reworked macro works with `ZLayer#reloadable`. 

Possible future actions:
1. Open a new PR against [zio/zio](https://github.com/zio/zio/) that depends on #8077 
2. Open a new PR against [adamgfraser/zio](https://github.com/adamgfraser/zio) so that the new commits will eventually a part of #8077 

@jdegoes @adamgfraser Which way do you prefer?

**Comment by adamgfraser** [comment]
@guersam I don't think we will be able to merge #8077 until the comment above is addressed because right now `generate` fails to compile when called from polymorphic code like `ZLayer.reloadable`. I think it is fine to make those changes here or we can merge this as is and you can open another PR depending on your preference. Thanks again for your work on this! 🙏

**Comment by guersam** [comment]
@adamgfraser Understood that option 1 is impossible. Then I'll make another PR against your fork (option 2) to discuss more design details in relation to ServiceReloader and to make sure the implementation meets the real requirement.

**Comment by adamgfraser** [comment]
@guersam Sounds good!

**Review by adamgfraser — APPROVED** [review]

**Comment by guersam** [comment]
Opened https://github.com/adamgfraser/zio/pull/12 for further discussion.

**Pull request merged**
