### PR TITLE
Add sandboxWith to ZManaged

### PR DESCRIPTION
**Pull request by saraiva132**

### CODE REVIEW

**Comment by saraiva132** [comment]
Some how 2 ZIOSpec tests failed. I am not sure if they are flaky because I can't see how this changes affect them but I will take a look at it

**Comment by saraiva132** [comment]
I am not able to reproduce these failures. Can someone re-trigger the tests, perhaps they are flaky? @iravid @adamgfraser . 

Failing tests are ZIO -> ForkAll -> propagates defects

**Comment by adamgfraser** [comment]
Can you mark the test as `flaky`? There is already an open issue for it in #2096.

**Comment by iravid** [comment]
Thanks @saraiva132!

**Pull request merged**
