### PR TITLE
Implement ZPipeline#fromFunction

### PR DESCRIPTION
**Pull request by adamgfraser**
Allows creating a pipeline from a stream transformation function so you can do with a pipeline anything you can do with a stream operator.

### CODE REVIEW

**Review by vigoo — APPROVED** [review]

**Comment by vigoo** [comment]
Feels a bit weird to me doing this if you have only a single `ZPipeline.fromFunction` applied to the stream (as if it would be a `ZStream` aspect it could directly transform the stream). But I guess it makes sense if you start composing it with other pipelines.

**Comment by adamgfraser** [comment]
This couldn't be implemented as a stream aspect because it potentially changes the element type.

**Comment by vigoo** [comment]
That's right. I just meant that it introduces extra channel components while in theory it could be just applied to the stream when it is "via'd" (or whatever it is called) to the stream. But that does not fit into our current model.

**Comment by adamgfraser** [comment]
Yeah I think the main use case is if you want to represent a stream transformation as a pipeline so it is a first class value and you can compose it with other pipelines. It solves the problem of something being implemented as a stream operator and not a pipeline.

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
