### PR TITLE
Implement CanSucceed

### PR DESCRIPTION
**Pull request by adamgfraser**
Implements `CanSucceed` analogous to `CanFail` and `NeedsEnv` to provide evidence that an effect can succeed and prevent combinators that don't make sense from compiling.  Here is a table of ZIO combinators that would not compile and value preserving rewrites. If we are good with this I can expand to other ZIO types.

Code | Rewrite
-- | --
fail.absolve | fail
fail.andThen(zio) | fail
fail.as(b) | fail
fail.bimap(f, g) | fail.mapError(f)
fail.bracket(release, use) | fail.uninterruptible
fail.bracket_(release, use) | fail.uninterruptible
fail.bracketExit(release, use) | fail.uninterruptible
fail.bracketOnError(release, use) | fail.uninterruptible
fail.collect(e)(pf) | fail
fail.collectM(e)(pf) | fail
fail.const((b) | fail
fail.doUntil(f) | fail
fail.doWhile(f) | fail
fail.either | fail.flip*
fail.filterOrDie(p)(t) | fail
fail.filterOrDieMessage(p)(message) | fail
fail.filterOrElse(p)(f) | fail
fail.filterOrElse_(p)(zio) | fail
fail.filterOrFail(p)(e) | fail
fail.flatMap(f) | fail
fail.flatten | fail
fail.fold(failure, success) | fail.catchAll(failure andThen ZIO.succeed)
fail.foldCause(failure, success) | fail.catchAllCause(failure andThen ZIO.succeed)
fail.foldCauseM(failure, succeed) | fail.catchAllCause(failure)
fail.foldM(failure, success) | fail.flatMapError(failure)
fail.forever | fail
fail.get | fail*
fail.head | fail*
fail.map(f) | fail
fail.none | fail *
fail.onFirst | fail
fail.onSecond | fail
fail.option | fail.ignore* 
fail >>> zio | fail
fail.left | fail*
fail.leftOrFail(e) | fail*
fail.leftOrFailException | fail
fail.right | fail
fail.rightOrFail | fail
fail.rightOrFailException | fail
fail.reject(pf) | fail
fail.rejectM(pf) | fail
fail.repeat(schedule) | fail
fail.repeatOrElse(schedule, orElse) | fail.flatMapError(orElse(_, None))
fail.repeatOrElseEither(schedule, orElse) | fail.flatMapError(orElse(_, None))*
fail.some | fail
fail.someOrFail(e) | fail
fail.someOrFailException | fail
fail.tap(f) | fail
fail.tapBoth(f, g) | fail.tapError(f)
fail.unit | fail
fail.void | fail
fail.withFilter(f) | fail
fail.zip(zio) | fail
fail.zipLeft(zio) | fail
fail.zipRight(zio) | fail
fail.zipWith(zio)(f) | fail
fail >>= zio | fail
fail *> zio | fail
fail <* zio | fail
fail &&& zio | fail
fail <*> zio | fail

* Existing combinator wraps a value in an extraneous combinator (e.g. `Left`, `Right`, `Some`) that can also be eliminated.

### CODE REVIEW

**Comment by neko-kai** [comment]
Personally, this feels like maybe a bit too much – there are very few operations that return Nothing to guard against, yet there are costs associated with the technique – more complex signatures and compile-time cost of implicit search.

**Comment by adamgfraser** [comment]
@neko-kai Yes, this one ends up being much more ubiquitous than the other implicit evidence we use because so many operations are defined in terms of `flatMap`. @jdegoes had expressed interest in this so wanted to put something together but if people are not feeling it I am fine chocking it up as an experiment.

**Comment by jdegoes** [comment]
I think I agree this experiment did not turn out favorable. What do you think?

**Comment by adamgfraser** [comment]
I agree.

**Pull request closed without merging**
