### PR TITLE
Metrics Documentation

### PR DESCRIPTION
**Pull request by khajavi**
In this pull request, I'm going to document ZIO Metrics, which addresses the #5542 issue.

### CODE REVIEW

**Review by atooni — DISMISSED** [review]
LGTM

**Comment by adamgfraser** [comment]
And now when this is ready we can make it available right away!

**Comment by khajavi** [comment]
The work is ready for review

/cc @jdegoes and @adamgfraser

**Review by adamgfraser — APPROVED** [review]
This looks fantastic! Eventually we should add additional documentation regarding how to connect metrics clients from `zio-metrics` but they need to implement versions of their metrics clients that use the new runtime hooks first.

**Pull request merged**
