### PR TITLE
Add ZManaged.runtime

### PR DESCRIPTION
**Pull request by fsvehla**
Adds `ZManaged.runtime`, analogous to `ZIO.runtime`

### CODE REVIEW

**Review by iravid — APPROVED** [review]
Thank you!

**Comment by fsvehla** [comment]
@iravid Force pushed because of flaky CI suite—I didn’t find a way to restart the build. Will not do this in the future so this is ready for review again.

**Comment by fsvehla** [comment]
I don’t see how the failing tests can be related to the changeset

**Comment by iravid** [comment]
No worries, the suite is flaky. Thank you for adding this!

**Pull request merged**
