### PR TITLE
Implement ZIO#traced

### LINKED ISSUE #5785: Include the JVM stack up to `Runtime.unsafeRun*` in the fiber trace
**The problem:**
Currently the fiber traces collected and attached to errors only cover the execution inside ZIO universe.
Which is fine if your whole app (or most of it) is ZIO. 
But when interoperating with non-ZIO code we often have flows where non-ZIO code is invoking ZIO effects via `Runtime.unsafeRun*` and if the effect fails, or an error is logged by it, the trace doesn't contain any info on where `Runtime.unsafeRun*` was called from in the non-ZIO part of the application.
(For example a future based GRPC request handler calling a library that is implemented in ZIO).

**The proposal:**
When `Runtime.unsafeRunWith` is creating the main `FiberContext` it could capture the current thread's stack, convert it into a `Ztrace` and pass it to the `FiberContext` as `parentTrace`.
Then in the fiber trace it will appear that the main fiber was spawned by this other fiber, whose trace is actually the captured stack.

Example (parent trace appears as `Fiber:Id(0,0) execution trace:`)

```
Exception in thread "main" java.lang.RuntimeException: kaboom
	at zio.Somewhere$.$anonfun$kaboom$5(RuntimeSpec.scala:13)
	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:2864)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:407)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: zio.Cause$FiberTrace: Fiber failed.
A checked error was not handled.
java.lang.RuntimeException: kaboom

Fiber:Id(1634380884543,0) was supposed to continue to:
  a future continuation at zio.Somewhere$.kaboom(RuntimeSpec.scala:11)

Fiber:Id(1634380884543,0) execution trace:
  at zio.Somewhere$.kaboom(RuntimeSpec.scala:13)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO.onInterrupt(ZIO.scala:1066)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$._IdentityFn(ZIO.scala:4248)
  at zio.clock.package$Clock$Service$$anon$1.sleep(package.scala:68)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2740)
  at zio.ZIO$.effectAsyncInterrupt(ZIO.scala:2740)
  at zio.clock.package$.sleep(package.scala:119)
  at zio.Somewhere$.kaboom(RuntimeSpec.scala:12)
  at zio.ZIO$.debug(ZIO.scala:2642)

Fiber:Id(1634380884543,0) was spawned by:

Fiber:Id(0,0) was supposed to continue to: <empty trace>

Fiber:Id(0,0) execution trace:
  at zio.Runtime.unsafeRunWith(Runtime.scala:190)
  at zio.Runtime.unsafeRunSync(Runtime.scala:85)
  at zio.Runtime.unsafeRunSync$(Runtime.scala:82)
  at zio.Runtime$$anon$3.unsafeRunSync(Runtime.scala:286)
  at zio.Runtime.unsafeRunTask(Runtime.scala:74)
  at zio.Runtime.unsafeRunTask$(Runtime.scala:73)
  at zio.Runtime$$anon$3.unsafeRunTask(Runtime.scala:286)
  at zio.Somewhere$.kaboom(RuntimeSpec.scala:12)
  at zio.RuntimeSpec$.delayedEndpoint$zio$RuntimeSpec$1(RuntimeSpec.scala:6)
  at zio.RuntimeSpec$delayedInit$body.apply(RuntimeSpec.scala:5)
  at scala.Function0.apply$mcV$sp(Function0.scala:39)
  at scala.Function0.apply$mcV$sp$(Function0.scala:39)
  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
  at scala.App.$anonfun$main$1(App.scala:76)
  at scala.App.$anonfun$main$1$adapted(App.scala:76)
  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
  at scala.App.main(App.scala:76)
  at scala.App.main$(App.scala:74)
  at zio.RuntimeSpec$.main(RuntimeSpec.scala:5)
  at zio.RuntimeSpec.main(RuntimeSpec.scala)

Fiber:Id(0,0) was spawned by: <empty trace>
```
As the capturing of the stack has some performance overhead, it could be enabled/disabled by a flag on `Platform`.

If this proposal makes sense, I will submit a PR

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #5785.

### CODE REVIEW

**Comment by dkarlinsky** [comment]
@adamgfraser, this is great to simplify adding to the stack trace of errors escaping out of a some instrumented effect.
What my issue also hoped to achieve was to have the "outside" stack trace added to errors that maybe logged inside of the effect being instrumented...
This is why my original [PR](https://github.com/zio/zio/pull/5818) included changes to `Runtime` and `FiberContext`
I noticed that `FiberContext` is initialized with an optional `parentTrace` which is set to `None` in by the runtime.
I was thinking that we could leverage it by passing in the "outside" stack trace.
But perhaps there is a way to allow doing it on effect level, which would look like the `ZIO.traced()` operator you added

**Comment by adamgfraser** [comment]
@dkarlinsky You can simply capture the stack trace and add it:

```scala
import zio._

object Example extends scala.App {

  val workflow =
    ZIO.attemptBlocking(throw new RuntimeException("die"))

  def foo(): Int =
    bar()

  def bar(): Int =
    baz()

  def baz(): Int =
    Unsafe.unsafe { implicit unsafe =>
      val stackTrace = Thread.currentThread().getStackTrace()
      Runtime.default.unsafe.run {
        workflow.traced(StackTrace.fromJava(FiberId.None, stackTrace))
      }.getOrThrowFiberFailure()
    }

  foo()
}
```

**Comment by dkarlinsky** [comment]
@adamgfraser yes, I understand
But what if the workflow catches some errors internally and logs them, for example: 
```scala
  val workflow =
    ZIO.attemptBlocking(throw new RuntimeException("die"))
      .catchAllCause { e =>
        ZIO.logErrorCause("failed", e)
      }
```
This could be something that happens many layers deep inside a complex workflow.
It would be very helpful if `workflow.traced(StackTrace.fromJava(FiberId.None, stackTrace))` also effected the stack traces logged inside the workflow

**Comment by adamgfraser** [comment]
@dkarlinsky I don't think this really makes sense to build into tracing as we don't have the concept of a parent trace anymore and we now conceptualize a ZIO stack trace as analogous to a Java stack trace where it is the stack of a single thread or fiber.

But you can easily add additional contextual information yourself if you want to:

```scala
import zio._

object Example extends scala.App {

  val extraTrace: FiberRef[StackTrace] =
    Unsafe.unsafe { implicit unsafe =>
      FiberRef.unsafe.make(StackTrace.none)  
    }

  def withExtraTrace[R, E, A](trace: StackTrace)(zio: ZIO[R, E, A]): ZIO[R, E, A] =
    extraTrace.locally(trace)(zio)

  def logErrorCause(cause: Cause[Any]): ZIO[Any, Nothing, Unit] =
    extraTrace.get.flatMap { trace =>
      ZIO.logErrorCause(cause.traced(trace))
    }

  val workflow =
    ZIO.attemptBlocking(throw new RuntimeException("die")).tapErrorCause(logErrorCause(_))

  def foo(): Int =
    bar()

  def bar(): Int =
    baz()

  def baz(): Int =
    Unsafe.unsafe { implicit unsafe =>
      val stackTrace = Thread.currentThread().getStackTrace()
      Runtime.default.unsafe.run {
        withExtraTrace(StackTrace.fromJava(FiberId.None, stackTrace))(workflow)
      }
      0
    }

  foo()
}
```

**Comment by dkarlinsky** [comment]
@adamgfraser Oh, my Intellij project was all messed up and I was looking at the old 1.x era code... I guess now  `FiberRuntime` is replacing `FiberContext`.
WRT to propagating my extra trace via `FiberRef` and picking it up at the logging site - I actually did something very similar at the time I submitted the issue and it worked.
In my case however this was for a very large piece of code (our greyhound kafka library) with a lot of layers and internal logging sites, so I was only able to introduce it in few key places.
My hope was that this could be done in a more composable / declarative way at the runtime level...

**Comment by adamgfraser** [comment]
@dkarlinsky You can do this by providing your own logger:

```scala
import zio._

object Example extends scala.App {

  val extraTrace: FiberRef[StackTrace] =
    Unsafe.unsafe { implicit unsafe =>
      FiberRef.unsafe.make(StackTrace.none)
    }

  val logger: ZLogger[String, Unit] =
    new ZLogger[String, Unit] {
      val default = ZLogger.default.map(println(_)).filterLogLevel(_ >= LogLevel.Info)
      def apply(
        trace: Trace,
        fiberId: FiberId,
        logLevel: LogLevel,
        message: () => String,
        cause: Cause[Any],
        context: FiberRefs,
        spans: List[LogSpan],
        annotations: Map[String, String]
      ): Unit =
        default(
          trace,
          fiberId,
          logLevel,
          () => message(),
          cause.traced(context.getOrDefault(extraTrace)),
          context,
          spans,
          annotations
        )
    }

  val runtime: Runtime[Any] =
    Unsafe.unsafe { implicit unsafe =>
      Runtime.unsafe.fromLayer {
        Runtime.addLogger(logger) ++ Runtime.removeDefaultLoggers
      }
    }

  def withExtraTrace[R, E, A](trace: StackTrace)(zio: ZIO[R, E, A]): ZIO[R, E, A] =
    extraTrace.locally(trace)(zio)

  val workflow =
    ZIO.attemptBlocking(throw new RuntimeException("die")).tapErrorCause(ZIO.logErrorCause(_))

  def foo(): Int =
    bar()

  def bar(): Int =
    baz()

  def baz(): Int =
    Unsafe.unsafe { implicit unsafe =>
      val stackTrace = Thread.currentThread().getStackTrace()
      runtime.unsafe.run {
        withExtraTrace(StackTrace.fromJava(FiberId.None, stackTrace))(workflow)
      }
      0
    }

  foo()
}
```

**Comment by dkarlinsky** [comment]
Thank you @adamgfraser for the detailed code samples :)
This is seems like a good solution for the case where all the logging inside `workflow` is indeed done via ZIO logging.
In the real life scenario that motivated me to open the original issue, we were using other logging APIs, spread over a lot of places in the code... 
(most of the code was developed before logging was integrated into ZIO)
But I understand that we don't necessarily want stuff in ZIO core that is intended to solve specific issues in some "legacy" code :)
The reason, I though it would a good ZIO issue, though, is that you could argue, that logically the stack frames leading up to `Runtime.unsafe.run*` can be seen as part of the logical stack trace exposed by ZIO, which in the end is there to answer a developer's question: "so how did we get here?"

**Comment by adamgfraser** [comment]
@dkarlinsky Yeah in ZIO 2 we have moved to the model that a ZIO stack trace should be like a Java stack trace and should represent the stack trace of that particular thread or fiber. That is the model that all legacy code and tooling around it is based on and overall provides a good experience in combination with other tools for monitoring and observability.

You might want to provide a variety of other contextual information about "how we got here" such as a log span, a correlation identifier, or a request, and the answer in all those cases is that you can capture that context in a `FiberRef` and access it with whatever tooling you are using. Libraries such as ZIO Logging provide built in functionality for this and support a variety of logging backend but any observability provider is free to access these values and use them.

I think that is the only sustainable way to do this since there is a variety of contextual information that a user might want and this scales to support capturing and reporting this information in any desired way versus hard coding support for a particular way that I don't think is even the best.

**Comment by adamgfraser** [comment]
Closing as I think this is better handled with existing functionality provided by `FiberRef` and `ZLogger`.

**Comment by dkarlinsky** [comment]
@adamgfraser ok, this makes sense. 
Thanks for your explanations and code samples :)

**Comment by adamgfraser** [comment]
@dkarlinsky No problem! Thanks for raising! 😃

**Pull request closed without merging**
