### PR TITLE
Welcome page improvements

### PR DESCRIPTION
**Pull request by SvMak**
Screenshot 2024-08-09 at 20 37 45

### CODE REVIEW

**Comment by SvMak** [comment]
@regiskuckaertz

I would be happy if you could reviewing the PR

**Comment by SvMak** [comment]
@jdegoes 

I would be happy if you could reviewing the PR

**Comment by SvMak** [comment]
@ghostdogpr 

I would be happy if you could reviewing the PR

**Comment by ghostdogpr** [comment]
Maybe @khajavi would be more appropriate to review this.

**Comment by khajavi** [comment]
@SvMak 
Thanks for your contribution!
Can we have separate PRs for each Improvement? e.g. "Adding Embedded Video Showcase", "Refactoring Welcome Page Components" , ...

**Comment by SvMak** [comment]
> @SvMak Thanks for your contribution! Can we have separate PRs for each Improvement? e.g. "Adding Embedded Video Showcase", "Refactoring Welcome Page Components" , ...

Yes, sure.

List of PRs:

1. Setup
- add prettier & prettier-plugin-tailwindcss
- add google-fonts plugin

2. Video Component
- add video component

3. Refactoring
- setup tailwindcss
- refactoring welcome page

Will this work for you?

**Comment by khajavi** [comment]
@SvMak 
Yeah! Please do it. I appreciate it.

**Comment by khajavi** [comment]
Please create new PRs, I'll close this.

**Pull request closed without merging**
