### PR TITLE
Delete Type Alias Companion Objects

### PR DESCRIPTION
**Pull request by adamgfraser**
The separate "companion objects" for the various type aliases of `ZIO` have some value in reducing need to specify type parameters in certain cases. However, they also create a risk of inconsistency if not all methods that are defined on `ZIO` are also defined for the various companion objects.

The more modern trend has been to simply define these "companion objects" as aliases for the companion object of the underlying type. This way all methods defined on the underlying companion object are automatically available when using any of the type aliases. This PR deletes the companion objects for the various ZIO type aliases to align their treatment with this approach.

### CODE REVIEW

**Comment by nicolasdasriaux** [comment]
This is removing a lot of complexity for sure.

All `val` aliases now point to the `ZIO` companion object hence offering the same set of methods, with exactly the same parameter types and exactly the same return type

I see a lot of code change from using `Task`, `IO`, `UIO` companion object to using the `ZIO` companion object. But at some occurences, original companion object is kept.

It leaves me wondering what additional meaning or intent does calling a method on `Task` val (for example) does convey over calling the same method on the `ZIO` companion object directly  ?

Or maybe the `val` aliases are left for compatibility.

**Comment by adamgfraser** [comment]
I think they can be valuable if you are working with a certain type alias throughout your code base. For example if you are using `Task` everywhere as your return type it is nice to be able to call operators on the `Task` value instead of `ZIO` for consistency. It is also important for consistency with other data structures that have more polymorphic versions where you can call operators on the more monomorphic version (e.g. `Queue.bounded` instead of `ZQueue.bounded`).

**Comment by jdegoes** [comment]
Good to merge when conflicts are fixed! 👍

**Comment by adamgfraser** [comment]
Fixed now!

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
