### PR TITLE
Consolidating all source location macros into `ZTraceElement`

### LINKED ISSUE #5903: ZIO Test 2.0: Use ZTraceElement instead of SourceLocation
ZIO Test independently evolved the ability to capture source locations. Now that we have ZTraceElement which directly captures source locations, we can replace usages of SourceLocation inside ZIO Test with ZTraceElement.

### PR DESCRIPTION
**Pull request by hmemcpy**
Fixes #5903

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
Great cleanup here! Can you resolve conflicts and then we can get this merged assuming tests are passing?

**Review by adamgfraser — APPROVED** [review]
Thank you! 🙏

**Comment by adamgfraser** [comment]
@hmemcpy Can you resolve conflicts?

**Comment by hmemcpy** [comment]
Again!? 😆

**Review by adamgfraser — APPROVED** [review]
Too much good stuff going on! 😃

**Comment by hmemcpy** [comment]
What did I miss, by the way? I noticed you did some work around the test runner?

**Comment by adamgfraser** [comment]
We merged the PR on shared layers in specs so we are going to be replacing `DefaultRunnableSpec` with `ZIOSpec` which will let you define a layer and then if that layer is referenced in multiple tests it will automatically be shared. We also moved all the test services out of the `zio.test.environment` package so you don't need to do as many imports.

**Comment by hmemcpy** [comment]
Ooh very cool! Looking forward to the refactoring :)

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
