### PR TITLE
Optimize ZIO.attempt

### PR DESCRIPTION
**Pull request by adamgfraser**
We can make this slightly faster by only looking up the definition of a fatal error if an exception is thrown.

### CODE REVIEW

**Review by vigoo — APPROVED** [review]

**Comment by adamgfraser** [comment]
This does mean that if a fatal error does occur we need to execute one more workflow after that to get the definition of a fatal error so maybe this doesn't make sense.

**Comment by jdegoes** [comment]
I wonder if we should just intern it.

**Comment by adamgfraser** [comment]
Isn't the problem that the definition of a fatal error is itself a regional setting stored in a `FiberRef` so for correctness we have to look it up at some point? We could move the whole thing into the runtime but I don't think it is worth it. In microbenchmarks `ZIO.succeed` is about 10% faster than `ZIO.attempt` right now and with this change that difference goes down to about 5%.

**Comment by jdegoes** [comment]
All right, sounds good to me.

**Pull request merged**
