### PR TITLE
#1845 Added methods to compose ZStream with ZStreamChunk

### PR DESCRIPTION
**Pull request by Twizty**
Implemented #1845.

### CODE REVIEW

**Comment by iravid** [comment]
@jdegoes Could I get your opinion on this? Not sure what the right approach should be here

**Comment by jdegoes** [comment]
@iravid Looking now...

**Comment by jdegoes** [comment]
The main problem is that by introducing these few methods, we are setting up the user for some inconsistency problems:

1. First, that the methods are not universal: only a few cases have been covered, not all.
2. Second, that the methods aren't symmetrical. Ideally, users who can do `a op b` can also do `b op a`, but that will not be the case in this PR.

We could, using type classes or implicits or even subtyping (with more type parameters!), ensure all methods can be called on all combinations. That seems overkill given the massive impact on the API.

Ultimately a combinator approach may be more useful.

First, we want to carrot toward chunking the non-chunked side, so at least one side is chunked. If a user could type:

```scala
stream1.chunked zip stream2
```

Well, that's almost as good as `stream1 zip stream2`, isn't it?

Now such naive chunking may work fine, if it doesn't, you could do:

```scala
stream1.chunkWith(stream2)(_ zip _)
```

where you would then chunk `stream1` based on `stream2` chunk sizes. But that's more cumbersome / tedious to write, so perhaps we could just start off encouraging the first one?

What do people think?

**Comment by iravid** [comment]
Thanks for your work on this @Twizty. I'm closing this one out as after some thought, it's not the right approach to the problem; we should make the translation between `ZStream/ZStreamChunk` easy, but not allow for sequencing between the types.

**Pull request closed without merging**
