### PR TITLE
The Provider Provides

### PR DESCRIPTION
**Pull request by kitlangton**
istockphoto-659661462-612x612

### CODE REVIEW

**Comment by hmemcpy** [comment]
I'm sorry, this is literally the Abstract Factory pattern, and IMO has no place in ZIO. With ZLayer you had a *value* of a layer which you *provide* to whoever requires it. This creates another entity (*er suffix, already a javaism) just to create whatever's being provided. Overall, 👎, sorry.

**Comment by regiskuckaertz** [comment]
@hmemcpy this does not change anything but the name, this is still a value describing dependency allocation, disposal and wiring, right? Now one SNOT like me may find that providing a provider is a language and logical horror but again that's my OCD 😅

**Comment by hmemcpy** [comment]
Ah, I didn't read the entire thing to see this was just a "naming things" PR :) Still... I feel that ZLayers are/were a killer feature for ZIO 1.0, and if they are simplified for 2.0 that'd be great. I don't, however, think they need to be renamed.

**Comment by kitlangton** [comment]
The people have spoken. Long love ZLayer!

**Pull request closed without merging**
