### PR TITLE
Add video component

### PR DESCRIPTION
**Pull request by SvMak**
@khajavi PR 2. Video Component
- add video component

### CODE REVIEW

**Review by khajavi — APPROVED** [review]

**Comment by SvMak** [comment]
@khajavi 

I can recreate latest two PRs creating branches from main branch(series/2.x) and we can merge it one by one: create add-video-component branch from main -> PR -> merge -> create refactoring-welcome-page from main branch -> PR -> merge.

What you think?

**Comment by khajavi** [comment]
@SvMak Even after merging the pull request, the video component does not appear on the home page. Can you please investigate this issue?

**Comment by SvMak** [comment]
> @SvMak Even after merging the pull request, the video component does not appear on the home page. Can you please investigate this issue?

Because video component added to home page in last PR  https://github.com/zio/zio/pull/9112

**Comment by khajavi** [comment]
> > @SvMak Even after merging the pull request, the video component does not appear on the home page. Can you please investigate this issue?
> 
> Because video component added to home page in last PR #9112

Are you sure? I believe something is wrong! Refactoring involves reorganizing the code, not adding new features like adding new components.

**Comment by SvMak** [comment]
> Are you sure? I believe something is wrong! Refactoring involves reorganizing the code, not adding new features like adding new components.

My bad((( It would be more correct to call it a restyling

Edit: I've fixed the title and description.

**Pull request merged**
