### PR TITLE
Periodically Graduate Root Fibers From Nursery

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
How often will this happen?

**Comment by adamgfraser** [comment]
Every 100 milliseconds.

**Comment by jdegoes** [comment]
100 millis may be too often. Need to find a good way to measure this in realistic scenarios.

**Comment by jdegoes** [comment]
Good to merge for now. 👍

**Comment by adamgfraser** [comment]
Okay yeah if there is a different frequency we want we can definitely change it.

**Pull request merged**
