### PR TITLE
Adopt the new IntelliJ import order

### PR DESCRIPTION
**Pull request by sideeffffect**
Intellij IDEA has recently changed the order of import blocks. For the good of our contributors, we should follow it.

### CODE REVIEW

**Comment by adamgfraser** [comment]
@sideeffffect Good to go when tests are passing!

**Comment by adamgfraser** [comment]
Looks like this one is still having issues.

**Comment by sideeffffect** [comment]
@adamgfraser just one build needs restarting :pray:

**Comment by mijicd** [comment]
Not Adam, but I restarted it :)

**Comment by adamgfraser** [comment]
😃

**Comment by sideeffffect** [comment]
It died again :crying_cat_face:

**Comment by sideeffffect** [comment]
We're green :tada:

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
