### PR TITLE
Documentation: New Section on Dependency Injection

### PR DESCRIPTION
**Pull request by khajavi**
In this PR I added a new section on "Dependency Injection"

image

### CODE REVIEW

**Review by adamgfraser — APPROVED** [review]

**Comment by jdegoes** [comment]
I feel like we need to iterate this content so as to re-focus on using constructors to pass dependencies through to classes, and using layers primarily for wiring. 

Yes, ZIO Environment can be used for passing dependencies too, and there are lots of interesting cases where that's easiest, but to distill the essence, we should focus on the primary use case.

**Comment by adamgfraser** [comment]
Yes I think ideally you only use the environment for capabilities that can be locally eliminated like `Scope` and use layers for everything else.

**Comment by khajavi** [comment]
@jdegoes @adamgfraser 
I think the essence of DI in ZIO is only about thee things: ZIO environment, layer composition, and providing layers, that's it!

```scala
import zio._

class A {
  def foo = ZIO.succeed(42)
}

class B {
  def bar = ZIO.succeed("Hello!")
}

object MainApp extends ZIOAppDefault {
  val myApp: ZIO[A with B, Nothing, (Int, String)] =
    for {
      a  <- ZIO.service[A]
      r1 <- a.foo
      b  <- ZIO.service[B]
      r2 <- b.bar
    } yield (r1, r2)

  def run = myApp.debug.provideLayer(
    ZLayer.succeed(new A) ++ ZLayer.succeed(new B)
  )
}
```

But when it comes to best practices, we have the "Service Pattern" which adds one level of indirection, to package functionalities inside a class and uses constructors to pass dependencies:

```scala
import zio._

trait A {
  def foo: UIO[Int]
}

object A {
  def foo: ZIO[A, Nothing, Int] =
    ZIO.serviceWithZIO[A](_.foo)
}

case class ALive() extends A {
  override def foo: UIO[Int] =
    ZIO.succeed(42)
}

object ALive {
  val layer: ULayer[ALive] =
    ZLayer.succeed(ALive())
}

trait B {
  def bar: UIO[String]
}

object B {
  def bar: ZIO[B, Nothing, String] =
    ZIO.serviceWithZIO[B](_.bar)
}

case class BLive() extends B {
  override def bar: UIO[String] =
    ZIO.succeed("bar")
}

object BLive {
  val layer: ULayer[BLive] =
    ZLayer.succeed(BLive())
}

trait C {
  def baz: UIO[Unit]
}

object C {
  def baz: ZIO[C, Nothing, Unit] =
    ZIO.serviceWithZIO[C](_.baz)
}

case class CLive(a: A, b: B) extends C {
  override def baz: UIO[Unit] =
    for {
      _ <- a.foo
      _ <- b.bar
    } yield ()
}

object CLive {
  val layer: ZLayer[A with B, Nothing, C] =
    ZLayer {
      for {
        a <- ZIO.service[A]
        b <- ZIO.service[B]
      } yield CLive(a, b)
    }
}

object MainApp extends ZIOAppDefault {

  val myApp: ZIO[A with C, Nothing, Unit] =
    for {
      _ <- A.foo
      _ <- C.baz
    } yield ()

  def run =
    myApp.provideLayer(
      (ALive.layer ++ BLive.layer) >>> CLive.layer ++ ALive.layer
    )
}
```

Therefore, instead of presenting a complex example at first, it is better to focus on distilled principles of DI in ZIO. Then we can provide a full practical example of using DI in ZIO along with the Service Pattern. 

Accordingly, I'm going to make another PR, to make this clear.

Please correct me if I'm wrong.

**Comment by adamgfraser** [comment]
I think the question is whether the ZIO environment even fits in here, at least in the initial discussion. I could rewrite your example as follows:

```scala
import zio._

class A {
  def foo = ZIO.succeed(42)
}

class B {
  def bar = ZIO.succeed("Hello!")
}

trait C {
  def run: ZIO[Any, Nothing, Unit]
}

final case class CLive(a: A, b: B) extends C {
  val run: ZIO[Any, Nothing, Unit] =
    for {
      r1 <- a.foo
      r2 <- b.bar
    } yield (r1, r2)
}

object MainApp extends ZIOAppDefault {

  def run =
    ZIO
      .serviceWithZIO[C](_.run)
      .provide(
        ZLayer.succeed(new A {}),
        ZLayer.succeed(new B {}),
        ZLayer.fromFunction(CLive(_, _))
      )
}
```

Basically if your main application logic is a layer then you never have to work directly with the environment except for actually launching your application, which could be factored slightly differently, or using capabilities such as `Scope`.

**Pull request merged**
