### PR TITLE
Rename ZStream#transduce, ZStream#aggregate, ZStream#aggregateWithin 

### LINKED ISSUE #1886: Rename ZStream#transduce, ZStream#aggregate, ZStream#aggregateWithin
These operations use sinks to aggregate elements and emit the results into the stream. The latter two operate asynchronously, and the last also uses timeouts from a schedule.

I noticed that `transduce` is not easily found; people usually gravitate towards `aggregate` for synchronous operations. I suggest doing the following renames:
* `transduce` => `aggregate`
* `aggregate` => `aggregateAsync`
* `aggregateWithin` => `aggregateAsyncWithin`

Would love to get some opinions before doing this.

### PR DESCRIPTION
**Pull request by simpadjo**
closes #1886

### CODE REVIEW

**Comment by simpadjo** [comment]
#1886

**Comment by vasilmkd** [comment]
Tip: edit the original comment to "Resolves #1886" in order to close the accompanying issue when this is merged.

**Comment by simpadjo** [comment]
done

**Comment by simpadjo** [comment]
Done

**Pull request merged**
