### PR TITLE
Add tests of serialization for all ZIO data types and make Promise serializable

### PR DESCRIPTION
**Pull request by jakubjanecek**
Closes issue #1739

### CODE REVIEW

**Comment by ghostdogpr** [comment]
@jakubjanecek this test was just migrated to ZIO Test. Can you rebase on master and adapt the new tests?

**Comment by jakubjanecek** [comment]
@ghostdogpr I did rebase the code and converted the tests to zio-test. I do have a problem with `ZTrace` test which fails very strangely. I've tested serialization of `ZTraceElement` and `Vector[ZTraceElement]` and it works fine. The problem is with `List[ZTraceElement]` which fails on `ClassNotFoundException` on its own and when I try it as part of the `ZTrace` test it fails on `java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field zio.ZTrace.executionTrace of type scala.collection.immutable.List in instance of zio.ZTrace`. There is a serialization proxy pattern used in `List` and that seems to be the problem but I really have no idea how to solve the problem. Any help?

**Comment by ghostdogpr** [comment]
@neko-kai any idea about what's going on with `ZTraceElement`?

**Comment by dkarlinsky** [comment]
Adding this to sbt setting seems to resolve the ZTrace issue:
```scala
.settings( Compile / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat )
```
This is from https://github.com/sbt/sbt/issues/89

**Comment by jakubjanecek** [comment]
@dkarlinsky Thank you for your help!

@ghostdogpr This PR is now ready to be merged I think.

**Comment by LGLO** [comment]
Well done!

**Comment by ghostdogpr** [comment]
@jakubjanecek thanks!

**Pull request merged**
