### PR TITLE
CI: split compile step by Scala version

### PR DESCRIPTION
**Pull request by sideeffffect**
old PR: https://github.com/zio/zio/pull/7045

### CODE REVIEW

**Comment by sideeffffect** [comment]
What do you guys think? @adamgfraser @mijicd 
In a way I hate this change because of how it spreads the configuration over sbt and GH Actions and how we have to explicitly group projects by Scala version and/or platform. But I just don't see any better way to do the split... :shrug:
The build is also much quicker now due to more parallelization.

**Comment by adamgfraser** [comment]
I think we need to build a little bit of a fact base first. My somewhat anecdotal observation is we seemed to be at around 30 minutes for the compile step before merging the Scala Native PR and breaching 60 minutes thereafter?

Is that right?

Does Scala Native really take that long or is adding that just the straw that breaks the camel's back by using more memory when we are already doing a lot?

If so, maybe we just need to add an extra Scala Native task?

**Comment by sideeffffect** [comment]
Let's have a look at the number arising from this PR.
```
CI / testPlatforms (17, Native) (pull_request) Successful in 8m
```
So Native on its own doesn't cause problems.
But if we look at
```
CI / compile (3.*) (pull_request) Successful in 22m 
```
, we can see that Native in combination with Scala 3 it can take a long time (22 mins).
The build at one point needs to use > 4.7 GB of swap (on top of full memory) and that's what's causing the build to be slow.
https://github.com/zio/zio/runs/7289407195?check_suite_focus=true#step%3A10%3A829=

Scala Native is just yet another axis of building and sbt is aggressively parallel. If sbt tries to build more projects than it has memory for, it will be either slow (caused by using swap) or die altogether.
People in the Scala community resolve this by splitting the build by Scala version and platform. With more granularity with bigger, more demanding, projects.

**Comment by adamgfraser** [comment]
Okay, I do wonder if we should just split out `native` and `scalajs` but don't feel strongly. I do think that the command aliases are useful for local development so would recommend keeping those.

@mijicd What do you think?

**Comment by sideeffffect** [comment]
> command aliases are useful for local development

The command aliases were superseded by the new custom root projects (`rootJVM212`, `rootJS`, ...). Is there something you would like to do that worked with the old command aliases but can't be done now with the "roots"?

**Comment by adamgfraser** [comment]
If I wanted to run all the tests on the JVM I could do `testJVM` from the root in a single command or if I wanted to compile everything I could do `compileJVM` which if I am understanding correctly would take two separate commands now.

**Comment by sideeffffect** [comment]
> all the tests on the JVM

`rootJVM/test`

> compile everything [on JVM, I assume]

`rootJVM/compile`

if everything everything, then just 

`compile`

This has also the advantage that we're working now with the built-in tasks from sbt that everybody is familiar with (`testJVM` or `compileJVM` were just our ow, ad-hoc, locally defined aliases).

**Comment by mijicd** [comment]
I share @sideeffffect's sentiment here: while ugly, this change seems necessary if we want our builds to be sustainable. However, to preserve "contributor experience", I would update the aliases instead of removing them.

**Comment by adamgfraser** [comment]
@mijicd Sounds good to me!

**Comment by sideeffffect** [comment]
> update the aliases

Fair enough. There are many of them. There are even some "rare" ones, like `testJS211` or `testJVMDotty`. Would you like to keep all of them or just some. If only some, please tell me which ones :pray:

**Comment by adamgfraser** [comment]
I think I would just keep them as is. Keep this focused on reducing the build time which is what motivated this in the first place.

**Comment by sideeffffect** [comment]
@adamgfraser I've reverted the aliases back.
Can you please restart that one failed build? Otherwise we're good to merge :muscle:

**Comment by adamgfraser** [comment]
@sideeffffect Yep just did! Thanks for your work on this! 🙏

**Comment by sideeffffect** [comment]
green :tada:

**Review by adamgfraser — APPROVED** [review]

**Comment by swoogles** [comment]
@sideeffffect I think this is causing issues with how/where we print failed test summaries.

Previously, when a stage would fail, we would get the summary and then that task would end. So a user investigating build failures would see all the relevant info at the end of the logs.

However, now we are continuing on with other stages after a failure. This means our test summary gets printed long before the end of the task, and is difficult to find.

Screen Shot 2022-08-30 at 11 22 07 AM

I would love to discuss further with you, since you clearly know far more about build configuration than me 🙂 
I added you on Discord @ Bill Frasure

**Comment by sideeffffect** [comment]
@swoogles I'm not entirely sure what you mean. Are you referring to the fact, that e.g. `root${{ matrix.platform }}211/test` runs all (or at least) some test suites it contains in parallel and thus their output (including failures) can be mixed together? Am I on the right track? Or do you mean something else?

EDIT: The CI setup is up for changing as far as I'm concerned, of course. The end goal of it is happiness and good experience of ZIO developers :wink:

**Pull request merged**
