### PR TITLE
Reduce Scala Native CI time to 13 mins (down from 25)

### LINKED ISSUE #8945: Scala Native CI takes too long to complete, degrading DX
Currently the Scala Native CI takes ~25 minutes to complete (10 minutes longer than the JS CI), which degrades DX as we often need to wait for it to complete so that we can merge in patches / quickfixes. This keeps getting worse (IIRC a few months ago it was taking just under 20 minutes).

Opening this ticket in hopes that someone has any ideas on what we can do to improve this. Or do we wait till we update to Scala Native 0.5 and see if it's improved?

### PR DESCRIPTION
**Pull request by kyri-petrou**
/closes #8945
/claim #8945

With this PR, the Scala Native CI time is reduced from 25 minutes down to ~12-13 mins. In addition ScalaJS time is reduced from 15 mins down to 11-12mins.

Summary of changes (in order of most impactful to least impactful) below.
_Note that these changes are only done for the JS/Native tests_

1. Size `Gen` with a `size=10` for Scala JS / Native (default is 100).
2. Avoid usage of `foreachPar` / `collectPar` in Scala JS / Native for suites that were taking a long time to run
3. Use a size=1 in `GenSpec`, which was taking a few minutes to run with the default size of 100
4. Use `nonFlaky` annotations only for JVM

### CODE REVIEW

**Comment by asr2003** [comment]
@kyri-petrou Seems this approach is working from CI Native test. It is now 13 minutes ~close to the JS CI test time.

I would like to colloborate with you for this issue to get solved.

**Comment by kyri-petrou** [comment]
> I would like to colloborate with you for this issue to get solved.

@asr2003 I'm not sure what you mean, the PR is already finished. The Scala Native CI take a bit longer than the Scala JS one but it's almost impossible to get it to be the same because building native executables (which the tests are using) takes longer than compiling to JS. Also, the Scala Native CI is now taking less time than what the baseline mentioned in the issue (15 mins)

**Comment by asr2003** [comment]
@kyri-petrou Thanks! I thought it needed big refactoring, in that case I mentioned to colloborate :)

**Review by asr2003 — APPROVED** [review]
LGTM

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
