### PR TITLE
Reimplement ZStream.repeat

### PR DESCRIPTION
**Pull request by luis3m**
Part of #4886

### CODE REVIEW

**Comment by jdegoes** [comment]
@luis3m Thank you! Can you look into the failure on 2.11.12?

**Comment by luis3m** [comment]
@jdegoes it's unrelated. @adamgfraser tried to fix this flaky test a few days ago.

**Comment by luis3m** [comment]
Rebased anyway. Now all passing. @jdegoes

**Review by iravid — APPROVED** [review]
Nice. Pure channels FTW.

**Pull request merged**
