### PR TITLE
add a ZState constructor with the fork and join parameters

### PR DESCRIPTION
**Pull request by paulpdaniels**
Adds a small helper to facilitate adding the fork/join parameters on FiberRef constructors for more advanced use cases.

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
I think we should just add another variant of `initial` that takes a `FiberRef`.

**Comment by paulpdaniels** [comment]
@adamgfraser do you still want to keep the `statefulWith` operator though?

**Comment by adamgfraser** [comment]
@paulpdaniels I would be tempted to overload `stateful` but regardless of the name it should take a `FiberRef` as an argument.

**Comment by adamgfraser** [comment]
Going to close this as it has been open a while and I just submitted a PR that adds this feature.

**Comment by adamgfraser** [comment]
@paulpdaniels Do you have a motivating use case for this?

**Comment by paulpdaniels** [comment]
@adamgfraser yeah I wanted to customize the fiberRef join behavior in a state so that the child fibers would combine on the way up

**Comment by adamgfraser** [comment]
@paulpdaniels Can you be more specific?

**Comment by paulpdaniels** [comment]
@adamgfraser so we had a pipeline where we had a `ValidationContext` which tracked stats for each sub process.

`case class ValidationContext(tracked: Int, uploaded: Int, errors: Chunk[String])`

We would run several validation phases in parallel across a stream

something like

```scala
loader.mapParUnbounded(20) { input =>
  (enrich1(input).tap(updateStats) <&> enrich2(input).tap(updateStats))
}
```

I wanted to add a new join behavior so that instead of simply taking the right most, it would combine them by adding the validation contexts from each fiber together (they have a custom associative defined for them).

**Comment by adamgfraser** [comment]
@paulpdaniels Thanks! 🙏

**Pull request closed without merging**
