### PR TITLE
Update Scalafmt

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Review by sideeffffect — APPROVED** [review]
Awesome :fireworks:

**Review by mijicd — APPROVED** [review]
Please remove the steward ignore as well, other than that LGTM.

**edit:** scratch the reminder, i didn't see that you already did it :).

**Comment by adamgfraser** [comment]
@mijicd Didn't I do that by deleting `.scala-steward.conf`? Or is there another file I missed?

**Comment by mijicd** [comment]
You did, sorry, see my edit :).

**Comment by adamgfraser** [comment]
😃

**Pull request merged**
