### PR TITLE
Avoid name clash on JDK 23 from java.io.IO

### PR DESCRIPTION
**Pull request by digy**
JDK 23 adds a new class java.io.IO which clashes with zio.IO. (https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/io/IO.html)

Use fully qualified path to disambiguate.

### CODE REVIEW

**Comment by hearnadam** [comment]
Can you instead remove `IO` from the import? Something like: `import java.io._` -> `import java.io.{ IO => _, _ }`

Or change the wildcard for explicit imports.

**Comment by kyri-petrou** [comment]
Agree with the change proposed by @hearnadam

**Comment by digy** [comment]
@hearnadam  @kyri-petrou changed to explicit imports.
Thanks for the suggestion, it is much cleaner.

**Review by hearnadam — APPROVED** [review]

**Review by kyri-petrou — APPROVED** [review]
Thanks!

**Pull request merged**
