### PR TITLE
Experiment with stepless Sink

### PR DESCRIPTION
**Pull request by vasilmkd**
Opening an experimental PR for #538. 

cc @iravid 

WIP.

### CODE REVIEW

**Comment by jdegoes** [comment]
Does it seem to eliminate some boxing or simplify code?

**Comment by iravid** [comment]
This is definitely looking simpler, and also eliminates the `Step` from the `initial` like we thought of doing. I'd say this is worth pursuing!

**Comment by vasilmkd** [comment]
@jdegoes I haven't profiled this code or anything. We also have to assume that some combinators will have to keep a more complex state (off the top of my head, a tuple with a `Boolean` for continuation, maybe an `Option[A0]` for the leftovers), which will incur some allocations (so in these cases probably nothing will be saved).

@iravid I got pretty used to the `Step` API, but yes, this literally took no time to implement, and I think it exposes less internal implementation. Also, reasoning about `cont` felt more natural when implementing this PR. I used to have to constantly double check the `Step` module for implementation details.

**Comment by jdegoes** [comment]
@vasilmkd @iravid Will close this for now, feel free to re-open if it survives the refactor.

**Pull request closed without merging**
