### PR TITLE
added iff to test/boolalgebra

### LINKED ISSUE #3046: ZIO Test: Add double implication
`(l <==> r) = (l ==> r) && (r ==> l)`

### PR DESCRIPTION
**Pull request by WesselVS**
Added double implication to BoolAlgebra of Test. Resolves #3046.

### CODE REVIEW

**Comment by WesselVS** [comment]
Seems I failed to apply some formatting rules, will check and fix

**Comment by adamgfraser** [comment]
You can run `set prepare` to lint.

**Comment by WesselVS** [comment]
Thanks! Sorry about that, skipped over that step in the contributer readme.

**Comment by adamgfraser** [comment]
Congratulations on your first contribution to ZIO!

**Pull request merged**
