### PR TITLE
Implement ZManaged#reserve

### PR DESCRIPTION
**Pull request by adamgfraser**
Implements `ZManaged#reserve` to allow separately accessing effects describing resource acquisition and release without having to work with the finalizer map directly.

### CODE REVIEW

**Comment by adamgfraser** [comment]
Is there something wrong with the binary compatibility checks? Shouldn't we be able to add a new method?

**Comment by iravid** [comment]
That’s weird. Must be a backwards/forwards compatibility misconfiguration. Will check soon

**Comment by iravid** [comment]
@adamgfraser Looks like a MiMa bug (opened https://github.com/lightbend/mima/issues/532). Can you add the suggested filter `exclude[DirectMissingMethodProblem]("zio.ZManaged.reserve")` to `mimaBinaryIssuesFilter` in `MimaSettings.scala`?

**Comment by jdegoes** [comment]
@adamgfraser Will let you take this one

**Pull request merged**
