### PR TITLE
Add `@@ withLiveClock` to documentation

### LINKED ISSUE #8735: Add TestAspect.withLiveClock to the docs
Hi 👋

I spend the whole morning figuring out why `.retry(Schedule ...)` doesn't work in my tests.

I think `TestAspect.withLiveClock` should be mentioned in :

- Info admonition at the Installing ZIO Test page. https://zio.dev/reference/test/installation/
- At the test clock page: https://zio.dev/reference/test/services/clock/
- Probably somewhere at the TestAspects sub-page https://zio.dev/reference/test/aspects/

It would save hours for many people.

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #8735
/claim #8735

### CODE REVIEW

**Comment by mobley-trent** [comment]
@jdegoes kindly review

**Comment by jdegoes** [comment]
This is a duplicate. Closed in favor of the original.

**Comment by mobley-trent** [comment]
@jdegoes This was the content from my original PR. I had to open a new PR

**Comment by mobley-trent** [comment]
@jdegoes kindly reopen

**Pull request closed without merging**
