### PR TITLE
Fix debounce to properly handle empty chunks

### PR DESCRIPTION
**Pull request by luis3m**
Resolves https://github.com/zio/zio/issues/3602

### CODE REVIEW

**Comment by reibitto** [comment]
I think that fixes that particular issue. 👍 

However, I think there's something else:

```scala
ZStream("a", "b", "c").debounce(1.second).runCollect
```

This returns all the elements when I'd expect it to only return `c`. I think if you receive a chunk with more than 1 element you only want to return the last element from it, right?

**Comment by luis3m** [comment]
@reibitto yes, I mentioned this particular difference in the previous PR I think. I can change this.

**Comment by iravid** [comment]
@luis3m Do you want to address @reibitto's comment here or in a follow-up?

**Comment by luis3m** [comment]
@iravid preferably a follow-up

**Pull request merged**
