### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hassanraza5214**
My organization is used zio (libraryDependencies += "dev.zio" %% "zio" % "2.0.15") please add my organization name here.

### CODE REVIEW

**Comment by adamgfraser** [comment]
@hassanraza5214 This looks like a duplicate of your previous pull request.

**Comment by hassanraza5214** [comment]
> @hassanraza5214 This looks like a duplicate of your previous pull request.

please share with me how my organization will be added to this list. your adopter list

**Comment by adamgfraser** [comment]
It looks like you were doing it in the right place in your previous pull request, just when I tried to access the URL you added through my browser I didn't see anything on the page so I was wondering if there was an issue with the address or your website.

**Comment by adamgfraser** [comment]
At least for me navigating to https://lkwfee.de takes me to a blank page.

**Comment by hassanraza5214** [comment]
Thanks, I will check this error.

**Comment by adamgfraser** [comment]
@hassanraza5214 Your website is working now. Merged your other pull request and will close this one.

**Pull request closed without merging**
