### PR TITLE
Implement adapter from Set to WeakSet

### PR DESCRIPTION
**Pull request by andrzejressel**
This is my take on #8076

When I started working on this task I've prepared specialised SkipMap that I've converted to Set with WeakReferences.

But instead of that I've prepared something different. While task says that this kind of collection is required who said it has to be the same?

So instead of creating single collection I've prepared two wrappers that converts Set to WeakSet with automatic WeakReference collection

- On JVM we have global thread that pulls from ReferenceQueue (similar in concept to `java.lang.ref.Cleaner`, but Cleaner is only for PhantomReferences)
- On JS we can received callbacks from Finalizer

The advantages (in my opinion) to #8093 are:
- We can use 100% lock free collection - ConcurrentSkipList
- We don't have to maintain custom collection - we use what is already in standard library
- My implementation cleans itself and does not require calls to actually invoke cleaning.

I've based my PR on #8093 since benchmarks were very useful. I've also rewritten tests so JS version can be also tested.

Native version could be created after https://github.com/scala-native/scala-native/issues/3165, fortunately native also seems to have bindings to GC.

When it comes to benchmarks they are very interesting:
```
[info] Benchmark                                                                            Mode  Cnt      Score   Error   Units
[info] ConcurrentWeakHashSetAddBenchmark.javaAddConcurrent                                 thrpt    2   1944,908          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.javaAddSerial                                     thrpt    2   2495,593          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.springAddConcurrent                               thrpt    2   1319,012          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.springAddSerial                                   thrpt    2   1690,170          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioAddConcurrent                                  thrpt    2   1593,438          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioAddSerial                                      thrpt    2   2212,194          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnConcurrentHashMapAddConcurrent          thrpt    2   2866,705          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnConcurrentHashMapAddSerial              thrpt    2   1862,884          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnSkipListAddConcurrent                   thrpt    2   1607,785          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnSkipListAddSerial                       thrpt    2    569,357          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.javaIterateConcurrent                         thrpt    2     75,072          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.javaIterateSerial                             thrpt    2     90,492          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.springIterateConcurrent                       thrpt    2    374,741          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.springIterateSerial                           thrpt    2     79,286          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnConcurrentHashMapIterateConcurrent  thrpt    2    348,188          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnConcurrentHashMapIterateSerial      thrpt    2     69,967          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnSkipListIterateConcurrent           thrpt    2    399,352          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnSkipListIterateSerial               thrpt    2     77,807          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioIterateConcurrent                          thrpt    2    344,830          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioIterateSerial                              thrpt    2     79,777          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.javaRemoveConcurrent                           thrpt    2   3863,736          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.javaRemoveSerial                               thrpt    2  12591,878          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.springRemoveConcurrent                         thrpt    2     78,446          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.springRemoveSerial                             thrpt    2      9,748          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnConcurrentHashMapRemoveConcurrent    thrpt    2  18300,532          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnConcurrentHashMapRemoveSerial        thrpt    2   8147,232          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnSkipListRemoveConcurrent             thrpt    2   3163,371          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnSkipListRemoveSerial                 thrpt    2    507,984          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioRemoveConcurrent                            thrpt    2   5892,924          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioRemoveSerial                                thrpt    2   6031,066          ops/ms
```

So blocking ConcurrentHashMap is after than non-blocking SkipListSet? I guess that `log(n)` is slowing it down there.

/claim #8076

### CODE REVIEW

**Comment by dzikoysk** [comment]
At first, I was thinking about using `ConcurrentHashMap` as underlying collection, but as far as I understood the initial issue, the request aimed for dedicated impl (just like e.g. zio.internal.Stack), not a wrapper 🤔 

The results from benchmarks are strange for me tho, e.g. `zioAddConcurrent` is worse than `javaAddConcurrent` and it never happened to me. Moreover, the SkipList (any non hash based structure) will always underperform there, but results from your `zioBasedOnConcurrentHashMap*` are also quite low - my implementation is partly based on older `ConcurrentHashMap` that was slower than the new one (jdk8+, used in your impl). What's your setup for benchmarks? It looks like it underperforms in this benchmark even for some of your test cases. I'll clone this branch & run the new benchmark spec in the same env as #8093.

Lastly, I'd like to leave some notes in response to listed advantages over my proposal:

> 1.We can use 100% lock free collection - ConcurrentSkipList

The lack of locking directly impacts the performance (and we see it in benchmark) and violates the requirements of equal/better results that `Collections.synchronizedSet([WeakMap...])`. `ConcurrentHashMap` that definitely wins here is still locking under the hood, so it's simply excluded from this.

> 2. We don't have to maintain custom collection - we use what is already in standard library

You still need to maintain custom collection that has some specific behavior. I'd agree it's simpler, but on the other hand we could say that `ConcurrentWeakHashSet` gives more control and area for further improvements in terms of performance/functionalities. I guess effectively it's negligible in the context of our proposals, especially having in mind the intention of #8076 & performance oriented aspect of zio in general.

> 3. My implementation cleans itself and does not require calls to actually invoke cleaning.

This is not really a true from 2 reasons:
1. In terms of this implementation: Cleaning is invoked by standalone thread, so it works quite the same, it's just called by the independent (from user) actor:
https://github.com/zio/zio/blob/bdc4f09f7106f3871f7a2023a8d37ac94594ddde/core/jvm/src/main/scala/zio/internal/JVMConcurrentWeakSetAdapter.scala#L57-L70
2. In terms of my implementation:
  - 2.1. Such approach would also work in `ConcurrentWeakHashSet`, but imo it exceeds the responsibility of regular collection. If user wants to force cleanup for more up-to-date state of collection, there's always `ConcurrentWeakHashSet#gc()`.
  - 2.2. Purging is optional tbh, it could be even fully disabled, but we have to keep in mind that it'll increase desync between methods like `size()/isEmpty()` & the real state.

**Comment by andrzejressel** [comment]
> At first, I was thinking about using `ConcurrentHashMap` as underlying collection, but as far as I understood the initial issue, the request aimed for dedicated impl (just like e.g. zio.internal.Stack), not a wrapper 🤔
> 

Yeah, but on the other hand `Concurrent collection for ScalaJS` is self-contradictory.

> The results from benchmarks are strange for me tho, e.g. `zioAddConcurrent` is worse than `javaAddConcurrent` and it never happened to me. Moreover, the SkipList (any non hash based structure) will always underperform there, but results from your `zioBasedOnConcurrentHashMap*` are also quite low - my implementation is partly based on older `ConcurrentHashMap` that was slower than the new one (jdk8+, used in your impl). What's your setup for benchmarks? It looks like it underperforms in this benchmark even for some of your test cases. I'll clone this branch & run the new benchmark spec in the same env as #8093.
> 
> Lastly, I'd like to leave some notes in response to listed advantages over my proposal:
> 
> > 1.We can use 100% lock free collection - ConcurrentSkipList
> 
> The lack of locking directly impacts the performance (and we see it in benchmark) and violates the requirements of equal/better results that `Collections.synchronizedSet([WeakMap...])`. `ConcurrentHashMap` that definitely wins here is still locking under the hood, so it's simply excluded from this.

Maybe I'm overestimating the requirement of no locking, but I'm still baffled with the results - maybe SkipList is better on lots of thread (like > 32?) with smaller collection size.

> 
> > 2. We don't have to maintain custom collection - we use what is already in standard library
> 
> You still need to maintain custom collection that has some specific behavior. I'd agree it's simpler, but on the other hand we could say that `ConcurrentWeakHashSet` gives more control and area for further improvements in terms of performance/functionalities. I guess effectively it's negligible in the context of our proposals, especially having in mind the intention of #8076 & performance oriented aspect of zio in general.

I guess, but on the other hand the code you haven't written is the code you don't have to maintain. I don't now - I like the idea of being able to swap to perhaps better collection in the future.

> 
> > 3. My implementation cleans itself and does not require calls to actually invoke cleaning.
> 
> This is not really a true from 2 reasons:
> 
> 1. In terms of this implementation: Cleaning is invoked by standalone thread, so it works quite the same, it's just called by the independent (from user) actor:
>    https://github.com/zio/zio/blob/bdc4f09f7106f3871f7a2023a8d37ac94594ddde/core/jvm/src/main/scala/zio/internal/JVMConcurrentWeakSetAdapter.scala#L57-L70

Yeah, I guess auto-cleaning could be also implemented in your solution.

> 2. In terms of my implementation:
> 
> * 2.1. Such approach would also work in `ConcurrentWeakHashSet`, but imo it exceeds the responsibility of regular collection. If user wants to force cleanup for more up-to-date state of collection, there's always `ConcurrentWeakHashSet#gc()`.
> * 2.2. Purging is optional tbh, it could be even fully disabled, but we have to keep in mind that it'll increase desync between methods like `size()/isEmpty()` & the real state.

In my opinion/implementation user should not bother with cleaning himself - if something is out collection should autoheal as fast as possible to maintain performance. I don't see a reason why user would want collection full of garbage elements.


I see your point and advantages of your collection (the main is that Native will work out of the box), but I wanted to see how  wrapping collection and binding to GC would work.

**Comment by dzikoysk** [comment]
Benchmark results that can be compared with #8093:

```
[info] Benchmark                                                                            Mode  Cnt      Score   Error   Units
[info] ConcurrentWeakHashSetAddBenchmark.javaAddConcurrent                                 thrpt    2   2701,006          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.javaAddSerial                                     thrpt    2   3160,852          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.springAddConcurrent                               thrpt    2   1989,349          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.springAddSerial                                   thrpt    2   2358,470          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioAddConcurrent                                  thrpt    2   3034,250          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioAddSerial                                      thrpt    2   3057,106          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnConcurrentHashMapAddConcurrent          thrpt    2   4141,971          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnConcurrentHashMapAddSerial              thrpt    2   2653,370          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnSkipListAddConcurrent                   thrpt    2   2219,081          ops/ms
[info] ConcurrentWeakHashSetAddBenchmark.zioBasedOnSkipListAddSerial                       thrpt    2    690,677          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.javaIterateConcurrent                         thrpt    2    119,002          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.javaIterateSerial                             thrpt    2    146,907          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.springIterateConcurrent                       thrpt    2    588,708          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.springIterateSerial                           thrpt    2    117,477          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnConcurrentHashMapIterateConcurrent  thrpt    2    578,926          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnConcurrentHashMapIterateSerial      thrpt    2    111,432          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnSkipListIterateConcurrent           thrpt    2    655,171          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioBasedOnSkipListIterateSerial               thrpt    2    131,103          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioIterateConcurrent                          thrpt    2    632,179          ops/ms
[info] ConcurrentWeakHashSetIterateBenchmark.zioIterateSerial                              thrpt    2    121,865          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.javaRemoveConcurrent                           thrpt    2   6132,813          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.javaRemoveSerial                               thrpt    2  18951,676          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.springRemoveConcurrent                         thrpt    2    113,021          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.springRemoveSerial                             thrpt    2     21,325          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnConcurrentHashMapRemoveConcurrent    thrpt    2  42897,696          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnConcurrentHashMapRemoveSerial        thrpt    2  11436,633          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnSkipListRemoveConcurrent             thrpt    2   5112,609          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioBasedOnSkipListRemoveSerial                 thrpt    2    946,363          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioRemoveConcurrent                            thrpt    2  14011,210          ops/ms
[info] ConcurrentWeakHashSetRemoveBenchmark.zioRemoveSerial                                thrpt    2   9127,235          ops/ms
```

Setup: AMD Ryzen 9 5900HX (8c/16t), 32GB 3200MHz, Win 10, 64bit (Laptop, so it may throttle randomly - I've run it 3 times & listed mid values). As expected, `ConcurrentWeakHashSet` performs like in #8093 & `ConcurrentHashMap` stands out, especially in `remove` scenario.

**Comment by andrzejressel** [comment]
To be fair - I also have 8/16 ryzen - I guess maybe it must be run in 64/128 cores to see any difference. I have no idea.

**Comment by dzikoysk** [comment]
> Yeah, but on the other hand Concurrent collection for ScalaJS is self-contradictory.

I see, that's kinda why I've also asked in my PR if that's the desired direction. As far as I see, most of the `ScalaJS` impl looks like a pretty heavy stub due to several limitations of this ecosystem.

> Maybe I'm overestimating the requirement of no locking, but I'm still baffled with the results - maybe SkipList is better on lots of thread (like > 32?) with smaller collection size.

Yeah, that's always the question with such impls 😅 There's also the whole conversation about init params for collection, like e.g. concurrency level for segments size etc. It pretty much depends on the final use-case, in most cases both our impls would be fine as no one use it like in benchmark scenarios (especially weak maps/sets). 

> I guess, but on the other hand the code you haven't written is the code you don't have to maintain. I don't now - I like the idea of being able to swap to perhaps better collection in the future.

I agree, and I also think it's a decent feature in general. I was purely referencing to the requirements as it was a base of several decisions I've made in the #8093.

> In my opinion/implementation user should not bother with cleaning himself - if something is out collection should autoheal as fast as possible to maintain performance. I don't see a reason why user would want collection full of garbage elements.

Likewise, I was talking more about the general possibility of it/alternatives. At this point, it's pretty much up to John's preferences, not the limitation of impl.

> To be fair - I also have 8/16 ryzen - I guess maybe it must be run in 64/128 cores to see any difference. I have no idea.

Idk what's the regular target setup of zio & this impl (it's internal, and I guess there are some plans to utilize it somewhere in the project once it's available). For complex scenarios, structures like `ConcurrentHashMap` should be also tuned for the expected traffic, so this estimation is beyond my scope atm, especially that my awareness in the Scala ecosystem + industry is relatively low as I'm still just a student.

**Comment by jdegoes** [comment]
@andrzejressel I think I'd like to merge in #8093 and then open to creating a new bounty for additional work of yours on top of this foundation (if you are interested). Please let me know. In any case, thanks for your very interesting work here on SkipList!

**Pull request closed without merging**
