### PR TITLE
Data type organization

### PR DESCRIPTION
**Pull request by khajavi**
Most of the work on this pull request is about data type organization.
I think it's not ready to merge but would like to get feedback as soon as possible.
In this merge request, I changed the URL of some pages (data types and resources/ecosystem), so the old URLs become broken. I found [this plugin](https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects) to redirect the URLs, I need to migrate the whole documentation to Docusarous V2.0, which is not stable yet.

Some ongoing work on documentation:
- [x] Improve IO to reflect the main ZIO data type and introduce all type aliases
  + [x] resource management
  + [x] Unswallowed Exceptions 
  + [x] Unstoppable Finalizers
  + [ ] Improve documentation of `Runtime` data type
- [x] Write about three different types of workloads that a ZIO Fiber can handle in ZIO.
- [ ] Add use case section for FiberRef
- [ ] Organize Runtime, Platform, ZLayer, Has, and Chunk data types.
- [x] Resouce Management section on ZIO data type
- [x] document RefM data type

### CODE REVIEW

**Comment by khajavi** [comment]
@jdegoes 
Would love to get your feedback on what I did so far.

**Review by jdegoes — DISMISSED** [review]

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@KadekM Given the amount of changes here, and given the fact the build passed, I went ahead and merged it. Please submit followup PRs for the remaining items.

Thank you for your work on this!

**Comment by assafj-wix** [comment]
Hi ppl, I've found some broken links in the Streaming section.

For example, on [Streaming Summary](https://zio.dev/docs/datatypes/stream/) the[ Stream link](https://zio.dev/docs/datatypes/stream/stream.md) is broken.

Would you prefer a new Github issue with my findings? @jdegoes @KadekM

**Comment by KadekM** [comment]
appreciate the mentions @jdegoes @assafj-wix but let me ping @khajavi who's behind all this work :-)

**Pull request merged**
