### PR TITLE
Add some current time variants

### PR DESCRIPTION
**Pull request by Fristi**
I had some functions already which were doing this already, would be nice if we can have these in the core package

### CODE REVIEW

**Comment by adamgfraser** [comment]
@Fristi Just wanted to check in on whether you are still interested in working on this. If so is there anything I can do to help?

**Comment by Fristi** [comment]
Yes, I'll check the `envOrElseWith` pattern and see if I can come with up something this week

**Comment by adamgfraser** [comment]
Just so you don't have to implement the same logic twice in the `Clock` and the `TestClock` since one you had it to the service anything that extends the service now needs to implement those methods.

**Comment by Fristi** [comment]
That would be smart! However `TestClock` is not providing any means to get the currentTime right? How would you apply it to `TestClock`?  `TestClock` is only for time travelling it seems :)

**Comment by adamgfraser** [comment]
No if you look at the [implementation](https://github.com/zio/zio/blob/e27a7ee701a7e8ba3f34cbf8f08742179a3c9296/test/shared/src/main/scala/zio/test/environment/package.scala#L273) it extends `Clock.Service` with `TestClock.Service`.

**Comment by fsvehla** [comment]
I think that the variants that return `Instant` can be unexceptional if they are not implemented in terms of `currentDateTime`

**Comment by Fristi** [comment]
I think it's a good suggestion, but would `Clock` be still the right place to supply these functions?

**Comment by jdegoes** [comment]
@Fristi Great idea! Some of these were already added. However, we welcome more following the same pattern as established in the existing code base (e.g. naming the methods after the corresponding `java.time` method). Now that we depend heavily on java.time, there's essentially no reason to have all the variants. Please re-open if you get a chance to work on this again!

**Pull request closed without merging**
