### PR TITLE
Remove redundant benchutils

### PR DESCRIPTION
**Pull request by shawjef3**

### CODE REVIEW

**Comment by adamgfraser** [comment]
@shawjef3 This seems to be a fairly stylistic change (moving an operator from pattern matching against the subtypes of a data type to being defined on the subtypes of the data type). Not sure it is worth the code churn.

**Comment by shawjef3** [comment]
@adamgfraser ya functionally it's a style change, but if you want to add or remove  a queue type, you only have to edit one file this way.

**Comment by adamgfraser** [comment]
@shawjef3 I'm not sure that is really a problem for something that is updated extremely infrequently. If anything the current style seems slightly more idiomatic though it is debatable.

**Comment by shawjef3** [comment]
@adamgfraser alright. Not a big deal.

**Pull request closed without merging**
