### PR TITLE
Test mapMPar ordering

### LINKED ISSUE #1367: ZStream.mapMPar(1) may process stream element out of order
Code to reproduce:
```scala
for {
  queue  <- Queue.unbounded[Int]
  _      <- Stream.range(0, 9).mapMPar(1)(queue.offer).runDrain
  result <- queue.takeAll
  _      <- if (result == result.sorted) putStrLn("Ok")
            else putStrLn(s"Out of order: ${result}")
} yield ()
```
With relatively high probability it prints something like:
```
Out of order: List(0, 1, 2, 3, 4, 5, 6, 7, 9, 8)
```
It doesn't violate any of the guarantees scaladocs give, but may be surprising.

### PR DESCRIPTION
**Pull request by vasilmkd**
Fixes #1367.

Interesting edge case.

`mapMPar` and `mapMParUnordered` have the exact opposite semantics when the parallelism factor is 1.

### CODE REVIEW

**Comment by iravid** [comment]
`mapMParUnordered` uses your previous fix :-)

**Comment by iravid** [comment]
Oh you noted that in the issue 😂

**Comment by vasilmkd** [comment]
Got it. `mapMParUnordered` is correct in all cases. We need to fix the ordering for `mapMPar`, i.e. the ordering must be preserved for all `n` parallelism factors. Working on it.

**Comment by vasilmkd** [comment]
@iravid Please take another look at the discussion #1367. This is ready for review.

**Pull request closed without merging**
