### PR TITLE
Implement ZTransducer#filterInput and ZTransducer#filterInputM

### PR DESCRIPTION
**Pull request by unclebob418**
@iravid ran into the need for this today and figured I'd have a crack at implementing it. Can you please review?

### CODE REVIEW

**Comment by adamgfraser** [comment]
`filterInput` and `filterInputM`?

**Comment by iravid** [comment]
Looks good! Like @adamgfraser mentioned, `filterInput/M` would be more suitable names as we're already using them elsewhere (ZQueue for example).

**Comment by unclebob418** [comment]
thanks @adamgfraser & @iravid, I've renamed/reshuffled

**Comment by iravid** [comment]
Thanks @unclebob418!

**Pull request merged**
