### PR TITLE
ZIO Test: migrate StreamSpec

### PR DESCRIPTION
**Pull request by regiskuckaertz**

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
Alright, aside from this flaky test in ZIO, I need to work on the few commented out ones that are timing out, I think because they rely on `Clock`.

**Comment by iravid** [comment]
@regiskuckaertz I wouldn't oppose a `.provide(Clock.Live)` to work around that :-)

**Comment by regiskuckaertz** [comment]
That is tempting 😈 👍

**Comment by regiskuckaertz** [comment]
Boom 🎉

**Comment by iravid** [comment]
Ugh sorry. I merged #1982 and some tests were added there.

**Comment by regiskuckaertz** [comment]
@iravid all green now 🕺

**Comment by regiskuckaertz** [comment]
🤠 yesssss!

**Pull request merged**
