### PR TITLE
Added zio-aws-s3 to ecosystem

### PR DESCRIPTION
**Pull request by tampler**

### CODE REVIEW

**Comment by saraiva132** [comment]
@tampler  Could you please format by alphabetic order please?

**Comment by tampler** [comment]
Done

**Comment by softinio** [comment]
Nit: Should be after `zio-amqp` :-)

**Comment by tampler** [comment]
@softinio You have an invalid sorter :-)

**Comment by tampler** [comment]
Done

**Comment by saraiva132** [comment]
@tampler what do you mean invalid sorter?

**Pull request merged**
