### PR TITLE
Upgrade Izumi Reflect Version

### LINKED ISSUE #7489: Defect: Could not find service in ZEnvironment with scala 3
Following snippet using scala3 & zio 2.0.3 fails with error
```
Defect in zio.ZEnvironment: Could not find package::Registry::Service inside ZEnvironment(package$::Registry$::Service -> zio.metrics.prometheus.package$$anon$3@c27ac23)
```

Changing scala to 2.13.10 or zio to 2.0.2 helps.

```scala
#!/usr/bin/env scala-cli
//> using scala "3.2.0"
//> using lib "dev.zio::zio:2.0.3"
//> using lib "dev.zio::zio-metrics-prometheus:2.0.0"

import zio._
import zio.metrics.prometheus.Registry


final implicit class RunSyntax[A](private val io: ZIO[Any, Any, A]) extends AnyVal {
    def unsafeRun: A =
      Unsafe.unsafe { implicit unsafe =>
        Runtime.default.unsafe.run(io).getOrThrowFiberFailure()
      }
}

val effect = ZIO.service[Registry].flatMap(ZIO.debug(_))

effect.provideLayer(Registry.live).unsafeRun
```

### PR DESCRIPTION
**Pull request by adamgfraser**
Resolves #7489.

### CODE REVIEW

**Comment by narma** [comment]
Not sure it really helps. Have tested with izumi-reflect 2.2.1 - still fails.

**Comment by adamgfraser** [comment]
I think you may need to override the dependency version. I was able to replicate your issue with `izumi-reflect-2.2.0` but not with changing the ZIO dependency to `izumi-reflect-2.1.3` or `izumi-reflect-2.2.1`.

**Comment by narma** [comment]
Hm, have tested it in 3 ways, all unsuccessfully.

First with scala-cli snippet.
```scala
//> using scala "3.2.0"
//> using lib "dev.zio::zio:2.0.3"
//> using lib "dev.zio::izumi-reflect:2.2.1"
//> using lib "dev.zio::zio-metrics-prometheus:2.0.0"
```

Second with 
```
dependencyOverrides ++= Seq(
      "dev.zio" %% "izumi-reflect" % "2.2.1"
    ),
```

Third with rebuild zio with these changes locally and set this version in project.

**Review by jdegoes — APPROVED** [review]

**Comment by celetium** [comment]
I tried:
zio 2.0.3 with izumi-reflect 2.2.0  ... and 
zio 2.0.4 with izumi-refect 2.2.1, both are UNSUCCESSFUL.
zio 2.0.0-2 with refect 2.1.3, are OK.

**Comment by neko-kai** [comment]
I suspect recompiling zio with newest reflect `2.2.2` will fix that. @adamgfraser @celetium - this looks like breakage from compatibility change in scala 3 prefix hanling int2.2.0 - https://github.com/zio/izumi-reflect/releases/tag/v2.2.0 - and there's another fix to prefixes in 2.2.2. so you want to update to that instead. https://github.com/zio/izumi-reflect/releases/tag/v2.2.2

**Comment by adamgfraser** [comment]
@neko-kai Thanks! Just submitted a PR to upgrade to the latest `izumi-reflect` version.

@celetium You need to upgrade to the latest version of `zio-metrics`.

**Pull request merged**
