### PR TITLE
Add back test for effectBlockingInterrupt

### PR DESCRIPTION
**Pull request by fsvehla**
I’ve noticed that `effectBlockingInterrupt` has an `ignore`d test.
I think I came up with a test that is not flaky—it ran locally for some time without issues.

### CODE REVIEW

**Comment by fsvehla** [comment]
I’m really happy that the commit message didn’t jinx the build

**Comment by adamgfraser** [comment]
Nice! Will take a look.

**Comment by mlangc** [comment]
I've looked into this, and I think that the test is actually fine - starting something, and then cancelling it with a timeout of 0 should always work. If I'm guessing correctly, the flakiness comes from a race condition in `zio.blocking.Blocking.Service#effectBlockingInterrupt`: If `ensuring(interruptThread *> awaitInterruption)` is executed before the fiber that executes the actual effect has started, `awaitInterruption` will wait forever, because no one will ever set the barrier. In my opinion we should fix the implementation, not tweak the test.

**Comment by adamgfraser** [comment]
We also have the issue that this was potentially not running on the correct thread poo before (see https://github.com/zio/zio/pull/2862) so there are several moving pieces here. But completely agree that looking at both the implementation and the test needs to be in scope here.

**Comment by adamgfraser** [comment]
Looking at this more I think @mlangc is correct. @fsvehla Your test demonstrates the problem but we need to push this logic into `effectBlockingInterrupt` so the user can be confident that a blocking effect can be safely interrupted without having to invoke external coordination mechanisms. Do you want to take a crack at this?

**Comment by fsvehla** [comment]
Yes!

**Comment by jdegoes** [comment]
@fsvehla What's the status of this one?? /cc @adamgfraser

**Comment by fsvehla** [comment]
I’m down with a cold. This looks like something that should be fixed before the next RC, so it would be good if someone else could pick it up

**Comment by jdegoes** [comment]
@fsvehla No worries. Please get well soon!

**Pull request closed without merging**
