### PR TITLE
Parameterized environment on zio.Canceler

### LINKED ISSUE #1762: zio.Canceler should be parameterized
Canceler should be changed to
```scala
  type Canceler[R] = URIO[R, _]
```

### PR DESCRIPTION
**Pull request by ajaychandran**
Fixes #1762

### CODE REVIEW

**Comment by adamgfraser** [comment]
I think we are trying to avoid existential types for Dotty compatibility so we would want to use `Any` instead of `_` in type parameters.

**Comment by neko-kai** [comment]
@adamgfraser Wildcards are fine, dotty drops only explicit `forSome` syntax

**Comment by adamgfraser** [comment]
@neko-kai Ah, I misunderstood. Thanks!

**Comment by ajaychandran** [comment]
@neko-kai 
Hi,
I just noticed that the call to `Runtime.unsafeRunAsync_` in `ZStream.effectAsyncInterrupt` could be simplified.
```scala
// Current
                             runtime.unsafeRunAsync_(
                               k.foldCauseM(
                                 Pull.sequenceCauseOption(_) match {
                                   case None    => output.offer(Pull.end).unit
                                   case Some(c) => output.offer(Pull.halt(c)).unit
                                 },
                                 a => output.offer(Pull.emit(a)).unit
                               )
                             )
```
```scala
// .unit calls removed
            r.unsafeRunAsync_(k.foldCause(Pull.sequenceCauseOption(_) match {
              case None    => Pull.end
              case Some(c) => Pull.halt(c)
            }, Pull.emit) >>= q.offer))

```
Should this be changed?

**Comment by neko-kai** [comment]
@ajaychandran
Sure, makes sense to me :+1:

**Comment by ajaychandran** [comment]
Removing the `.unit` calls would shave off 1 `flatMap` per `Pull`. So I went with that version.

**Pull request merged**
