### PR TITLE
remove CanFail constrain from STM orElse combinator (and related combinators)

### PR DESCRIPTION
**Pull request by swachter**

### CODE REVIEW

**Comment by adamgfraser** [comment]
Can you sign the CLA?

**Comment by swachter** [comment]
> Can you sign the CLA?

I signed the CLA. Maybe the problem is that my email was not setup correctly. Will try to resolve the problem.

**Comment by adamgfraser** [comment]
Thank you!

**Comment by swachter** [comment]
had wrong email address set in my git config. tried to fix history. seems not to work out nicely. will close this pull request and create a new one.

**Pull request closed without merging**
