### PR TITLE
Implement ZLayer#reloadable

### LINKED ISSUE #8075: Leverage proxy macro to build dynamically-reloadable services
Depends on #7556. 

This ticket consists of 2 parts. The first part is to provide an implementation of a "service reloader" class that can handle registration of services, as well as reloading of (registered) services.

Something along the lines of this:

```scala
trait ServiceReloader {
  def register[A: Tag](serviceLayer: ZLayer[Any, Any, A]): UIO[Unit] 

  def reload[A: Tag]: IO[ServiceReloader.Error, Unit]
}
object ServiceReloader {
  sealed trait Error extends Throwable
  final case class ServiceNotRegistered(serviceTag: LightTypeTag) extends Error
  final case class ServiceInitializationError(error: Any) extends Error

  val live: ZLayer[Any, Nothing, ServiceReloader] = ???
}
```

The second part is to implement a `reloadble` method on `ZLayer`, which utilizes the service reloader, together with the proxy macro, to enable a service to be reloaded dynamically.

For example:

```scala
val clockLayer: ZLayer[Any, Nothing, Clock] = ???

val reloadableClockLayer: ZLayer[ServiceReloader, Nothing, Clock] = clockLayer.reloadable

def example(reloader: ServiceReloader) = 
  (Clock.instant *> reloader.reload[Clock] *> Clock.instant).provide(ServiceReloader.live, relodableClockLayer)
```

In essence, the service reloader has some sort of map from tag to `ScopedRef`, which back the registered services, and it also keeps track of the layers that can build the services, and it can re-instantiate a layer and register the newly-initialized service, cleaning up the resources of the old service, as necessary.

**Note**: This is just a sketch and when implementing this issue, it may be things cannot be implemented exactly in this way. The goal, however, is to provide a very robust and simple means of taking an ordinary service, and making it reloadable "upon request". Other tickets can address common reloading use cases, such as reload-on-config-change, reload-every-n-minutes, etc.

### PR DESCRIPTION
**Pull request by adamgfraser**
/claim #8075

### CODE REVIEW

**Review by jdegoes — COMMENTED** [review]
This is ready for plugging in the real implementation and testing!

**Comment by adamgfraser** [comment]
I think we have a problem here because we can't use macros in the same compilation unit they are defined in. But we want to use the macro in the implementation of `ZLayer.reloadable` in `zio` and the macro itself depends on `ScopedRef` in `zio`.

**Comment by adamgfraser** [comment]
Also the Scala 3 macro implementation uses experimental features and so cannot be used from code that is not marked as experimental.

**Comment by adamgfraser** [comment]
Okay this is ready to go. The last commit shows `ServiceReloader` is working but we need to move it out of ZIO Core so that it doesn't depend on a macro defined in the same compilation unit. Opened a PR to ZIO Config to do that. Once we merge this I can update that to depend on a snapshot version of ZIO and we can merge that in. I think there is a little more iterating we can do on naming but would like to do that afterwards.

**Review by jdegoes — APPROVED** [review]

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
ZIO Config may be a really weird place to put this. Maybe we should introduce `zio-macros` here in core and we can have a one-import `zio.macros._` that add all sort of extension methods that use macros, such as `reloadable`?

If ZIO comes to use macros more and more, this will be a common problem. And then ZIO Config can depend on `zio-macros` in order to add a hook that ties in reloading with config somehow.

What do you think?

**Comment by guersam** [comment]
An additional question, should we deprecate [zio.Reloadable](https://github.com/zio/zio/blob/v2.0.13/core/shared/src/main/scala/zio/Reloadable.scala) in favor of `ZLayer#reloadable` or does it have its own purpose?

**Comment by guersam** [comment]
Added a final touch to `ServiceProxy` to reflect its changed relationship with `ServiceReloader`. https://github.com/adamgfraser/zio/pull/13

**Comment by adamgfraser** [comment]
@jdegoes I don't think we can do that because the macro needs to use ZIO data types, in particular `ScopedRef`. So `reloadable` can be somewhere other than ZIO Config but it needs to be something that is downstream of ZIO.

**Comment by jdegoes** [comment]
@adamgfraser Right, I imagined `zio-macros` being a new top-level project in this repository, which depends on `core`, and the user would add that project to their dependency.

**Comment by jdegoes** [comment]
@guersam 

> An additional question, should we deprecate [zio.Reloadable](https://github.com/zio/zio/blob/v2.0.13/core/shared/src/main/scala/zio/Reloadable.scala) in favor of ZLayer#reloadable or does it have its own purpose?

I think it could be considered deprecated after these changes because it forces you to go through `get`, which is not a pleasant user experience. However, for backward compat reasons we can't remove it anytime soon.

**Comment by adamgfraser** [comment]
@jdegoes Yes we could do that. It is a bit odd because the functionality that it actually exposes would just be this `reloadable` operator but I guess you could think of it as "macro powered functionality provided by ZIO" so sure.

**Comment by jdegoes** [comment]
> Yes we could do that. It is a bit odd because the functionality that it actually exposes would just be this reloadable operator but I guess you could think of it as "macro powered functionality provided by ZIO" so sure.

I can go either way. But I think if we're going to have more things like this, then it may make sense to have a project that contains them all, because that could improve discovery versus pushing "macro core" functionality into different projects across the ZIO ecosystem.

An example is RPC: it would be nice to have some functionality in ZIO that lets you easily do RPC with a ZIO service. It requires similar macros to here. It could be added as an extension method on ZLayer, e.g. `ZLayer.gRPC[MyService]`.

**Comment by jdegoes** [comment]
@adamgfraser Take your pick on where to put that, I'm good either way.

**Comment by adamgfraser** [comment]
👍

**Comment by guersam** [comment]
Maybe I missed the context, but doesn't `zio-macros` [already exist](https://github.com/zio/zio/blob/v2.0.13/build.sbt#L327-L335) in this repo?

**Comment by adamgfraser** [comment]
@guersam It does. Right now it just contains the macros for generating service accessors. So it goes back to the idea that it becomes a little bit of a hodge hodge of somewhat unrelated functionality that is connected by the "how" versus the "what" but maybe that is the best we can do.

**Comment by adamgfraser** [comment]
Anyway, will certainly make it easier to iterate on this if we are doing in one project.

**Review by jdegoes — DISMISSED** [review]

**Comment by adamgfraser** [comment]
I think this is ready to go now.

**Review by jdegoes — APPROVED** [review]

**Comment by yarosman** [comment]
Does documentation exist about this new feature?

**Comment by adamgfraser** [comment]
@khajavi Can you add?

**Pull request merged**
