### PR TITLE
Introduction to the ZIO libraries

### PR DESCRIPTION
**Pull request by khajavi**
This pull request contains an introduction to the ZIO libraries and their use cases.

### CODE REVIEW

**Review by jdegoes — DISMISSED** [review]

**Comment by adamgfraser** [comment]
Love this!

**Comment by khajavi** [comment]
@jdegoes 
It is ready to be reviewed

I will send another pull request for ZIO Query section.

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@khajavi Thank you! Can you fix the conflicting build.sbt file?

**Comment by khajavi** [comment]
> @khajavi Thank you! Can you fix the conflicting build.sbt file?

Fixed

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
