### PR TITLE
Ensure that two chunks can be compared for equality and hash code #1159

### PR DESCRIPTION
**Pull request by Vilkina**

### CODE REVIEW

**Comment by jdegoes** [comment]
@Vilkina Looks superb! 

Just one small change: in order to _run_ the tests, they must be in the specification, which is a string at the beginning of a class (this is because we use `Specs2` for running tests, and this is the format it requires). 

So at the beginning of `ChunkSpec.scala`, you can see:

```scala
def is: SpecStructure =
    "ChunkSpec".title ^
      s2"""
  chunk apply $apply
  chunk length $length
  chunk equality prop $equality
  chunk inequality $inequality
  flatMap chunk $flatMap
  map chunk $map
  materialize chunk $materialize
  foldLeft chunk $foldLeft
  filter chunk $filter
  drop chunk $drop
  take chunk $take
  dropWhile chunk $dropWhile
  takeWhile chunk $takeWhile
  toArray $toArray
  foreach $foreach
  concat chunk $concat
  An Array-based chunk that is filtered empty and mapped must not throw NPEs. $nullArrayBug
  toArray on concat of a slice must work properly. $toArrayOnConcatOfSlice
  toArray on concat of empty and integers must work properly. $toArrayOnConcatOfEmptyAndInts
  Chunk.filter that results in an empty Chunk must use Chunk.empty $filterConstFalseResultsInEmptyChunk
    """
```

You can add a line in the "spec string" for each test, something like:

```
Chunk reflexivity $testReflexivity
...
```

etc. Then run `testOnly *ChunkSpec*` from `sbt`, to confirm the tests are being run.

Then we'll be ready to merge!

**Comment by Vilkina** [comment]
Screen Shot 2019-07-11 at 4 52 33 PM

**Comment by jdegoes** [comment]
@Vilkina Thank you for the contribution! 🎉 

giphy

**Comment by Vilkina** [comment]
@jdegoes, looking forward for next ticket)

**Comment by jdegoes** [comment]
@Vilkina How about [this one](https://github.com/zio/zio/issues/1164)? 😉

**Pull request merged**
