### PR TITLE
zio.stream.Take could use a scaladoc (#2684)

### PR DESCRIPTION
**Pull request by peterlopen**

### CODE REVIEW

**Comment by peterlopen** [comment]
@adamgfraser please, how can I tell CircleCI not to use my account to build this? (I do not have required plan)

**Comment by adamgfraser** [comment]
@peterlopen When Circle CI runs here the ZIO organization is responsible for the account.

**Comment by adamgfraser** [comment]
@softinio Can you look at what is going on with CI here?

**Comment by peterlopen** [comment]
@adamgfraser I disconnected my fork from circleci to get all builds green. hope we can merge and close it then. thank you.

**Comment by softinio** [comment]
@adamgfraser Build looks all green now. Was there an underlying issue I need to look into?

**Comment by adamgfraser** [comment]
@softinio There was a strange situation I hadn't seen before where it looked like Circle CI tried run the CI on the contributor's own Circle CI account and not the ZIO organization one. This resulted in an unfortunately situation where the contributor didn't have the right plan for the settings we use but we also weren't able to rerun because it wasn't our account. @peterlopen resolved this time by disconnecting his fork from Circle CI but don't know if there is something we can do to prevent in the future.

**Pull request merged**
