### PR TITLE
Zio1 stream bench

### PR DESCRIPTION
**Pull request by justcoon**
added some stream bench

### CODE REVIEW

**Comment by adamgfraser** [comment]
Can you fix the compilation failures?

**Comment by justcoon** [comment]
yes, I will check that

**Comment by justcoon** [comment]
@adamgfraser 

fix pushed, can you run build?

**Comment by adamgfraser** [comment]
@justcoon Can you mark that test as flaky and open an issue for it?

**Comment by justcoon** [comment]
created issue for flaky test #6520

**Review by vigoo — APPROVED** [review]

**Pull request merged**
