### PR TITLE
Fix refill bucket token (#7982)

### LINKED ISSUE #7982: [question] `throttleEnforce` does not work as expected
### Sample code

```scala
Unsafe.unsafe { implicit unsafe =>
  Runtime.default.unsafe.run(ZStream
    .fromSchedule(Schedule.spaced(100.millis) >>> Schedule.recurs(10))
    .map(_ + " : " + Instant.now().toString)
    .throttleEnforce(1, 200.millis) { _.size }
    .foreach(i => Console.printLine(i))
    .as(ExitCode.success)
  ).getOrThrowFiberFailure()
}
```
### Expected behavior 
Every 100 milliseconds, stream will emit one long item 10 times.
then even numbers item will be ignored by `throttleEnforce(200 millis) { _.size }`
```
0 : 2023-04-04T13:42:22.287807Z
2 : 2023-04-04T13:42:22.505317Z
4 : 2023-04-04T13:42:22.713895Z
6 : 2023-04-04T13:42:22.923393Z
8 : 2023-04-04T13:42:23.129721Z
```

### Current behavior 
```
0 : 2023-04-04T13:42:50.566159Z
```

### Setup

Scala version : 3.2.2
ZIO : 2.0.10

Maybe i'm using it wrong? I came here because I didn't know where to ask.

### PR DESCRIPTION
**Pull request by enif-lee**
Refill the bucket based on the last rejection.

### CODE REVIEW

**Comment by adamgfraser** [comment]
@enif-lee Already fixed in #7983.

**Comment by enif-lee** [comment]
@adamgfraser That's right. However, wouldn't the method of calculating tokens based on the last rejection be a little more efficient than the method of accumulating floating-point numbers?

**Comment by adamgfraser** [comment]
@enif-lee We're already using floating point numbers, we're just throwing away the fractional part now.

**Review by adamgfraser — DISMISSED** [review]

**Comment by adamgfraser** [comment]
@enif-lee Can you format?

**Comment by adamgfraser** [comment]
@enif-lee I think your previous implementation was fine.

**Comment by enif-lee** [comment]
@adamgfraser I came here while thinking about how to implement a new token to be issued precisely without floating point. I'll revert again!

**Review by adamgfraser — DISMISSED** [review]
Thanks for your work on this! 🙏

**Comment by enif-lee** [comment]
@adamgfraser Haha sorry, I fixed the broken format while reverting it again

**Review by adamgfraser — APPROVED** [review]

**Comment by adamgfraser** [comment]
@enif-lee No worries! 😃

**Pull request merged**
