### PR TITLE
Upgrade Dotty Version

### PR DESCRIPTION
**Pull request by adamgfraser**
Another release of Dotty just hit, so upgrades to that and fixes an error I had made in #1531 where I did not update the Dotty version in the CI configuration. Thanks to @smarter for pointing both out!

### CODE REVIEW

**Comment by adamgfraser** [comment]
@regiskuckaertz Sorry I didn't close the loop on this. I filed a bug report with the Dotty team related to this and they made some changes a couple of days ago to fix it so just getting a chance to test those changes now.

**Comment by adamgfraser** [comment]
Okay, so this is working now. Only issue is there was a bug in the release so we are compiling against a nightly after the bug got fixed. Are we okay with doing that or do we want to hold off until the next release in another five weeks?

**Comment by ghostdogpr** [comment]
Since we are not releasing for dotty yet, I'd say it's fine?

**Comment by adamgfraser** [comment]
I think so.

**Pull request merged**
